### ISSUE TITLE
When I try to calibrate temp sensor nothing happens what are the steps to calibrate the temp sensor in 3.0

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1013]
sw

**Comment by gminton86** [comment]
Sorry I forgot to reboot after calibrating
For the future you have to 
1.) Disable the temp sensor.
2.) Calibrate to the desired value you want.
3.) Save and then enable the temp sensor again.
4.) Reboot the system.

**Comment by gminton86** [comment]
actually im still having an issue with this ranjib can you help me? After a reboot my calibration went away for my temp sensor and I still cant get it right its 2 degrees off and in the calibration I make it +2 and it changes nothing?

**Comment by ranjib** [comment]
Sorry for the delay @gminton86 .Can you share some details like a screen shot  and sample logs showing the temperature values from reef-pi

**Comment by gminton86** [comment]
![Capture3](https://user-images.githubusercontent.com/22088453/74092579-123fae80-4a94-11ea-85b9-6abd9894a619.JPG)
![Capture](https://user-images.githubusercontent.com/22088453/74092580-12d84500-4a94-11ea-9c06-0fef5d7f802c.JPG)
![Capture2](https://user-images.githubusercontent.com/22088453/74092581-12d84500-4a94-11ea-8352-570fca68b9ca.JPG)

**Comment by gminton86** [comment]
i disable the temp sensor 
hit calibrate
my temp sensor is off by 2 degrees so i enter 2
hit apply and then reenabe the temp sensor and it stay the same 
if i enter 77.31 into the set temperature box I get an error

**Comment by gminton86** [comment]
can anybody help me

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/issues/1087

**Comment by Ranthalion** [comment]
Fixed by #1211
