### ISSUE TITLE
[Request] button or input to run macro

### ISSUE THREAD

**Issue by lironalm** [reef-pi/reef-pi#1018]
It would be nice to have a macro running upon an input trigger, like a button for feed macro

**Comment by ranjib** [comment]
Can you elaborate? Theres button to trigger macro from UI. ATO, pH and temperature can also trigger macro. You can use the ATO logic for spst style buttons as well. Are you looking for a physical button to on/off a  macro?

**Comment by lironalm** [comment]
Yes, a momentary physical button to run a macro. 
I can't seem to find a way to get the ato to run a macro.
If you mean to choose it in the control pump it doesn't have a macro option

**Comment by ranjib** [comment]
what version of reef-pi you are running?

**Comment by burningbaal** [comment]
related to issue #848

**Comment by burningbaal** [comment]
I'd be interested to see if I could tinker with the idea of a few physical buttons. I really like the idea of something like this: https://www.adafruit.com/product/3844
we'd get 16 for free, maybe reserve the * and # for something special and universal (like reload reef-pi if pressed in sequence `#*#*` and reboot pi if `**##**##` or something)

I'm new to go and a total newbie with browser stuff (I'm a C# and WPF guy), but this seems like something I could help with

**Comment by Ranthalion** [comment]
I agree that physical buttons would be nice.  In my opinion, the main limitation is that reef-pi uses polling for gpio.  I'd love to see the gpio driver replaced or updated with char dev functionality in order to detect pin changes via interrupts or events.  

I started an effort to port libgpiod to go, but haven't moved much with it.  If interested, take a look at https://github.com/Ranthalion/golibgpiod, or maybe there's another go based char dev library out there now.

**Comment by ranjib** [comment]
For go mmaped gpio driver example check this: https://github.com/warthog618/gpio or github.com/stianeikeland/go-rpio . I am not sure if these are exposed as interrupts for inputs. 
I want to keep the physical interface (button, lcd screen etc) as separate code base under reef-pi/phys repository and let it use reef-pi API for interaction. This reduces the risk to break existing thing and help us test these driver independently while opening up the possibility to reboot/restart /hotspot pi without reef-pi running. Does that make sense?

**Comment by lironalm** [comment]
> what version of reef-pi you are running?

Running latest 3.0

**Comment by lironalm** [comment]
![image](https://user-images.githubusercontent.com/46749273/71870700-9dd5c080-311f-11ea-9be8-88121fd2b3e7.png)

**Comment by lironalm** [comment]
![image](https://user-images.githubusercontent.com/46749273/71870748-c493f700-311f-11ea-886c-f4b58077b389.png)

**Comment by lironalm** [comment]
Timers screen does not have a macro option either
![image](https://user-images.githubusercontent.com/46749273/71871016-83e8ad80-3120-11ea-8de5-f1107709ad0b.png)

**Comment by ranjib** [comment]
Can you upgrade to 3.1, this was a new feature added very recently (ato -> macro trigger)

**Comment by lironalm** [comment]
sure, i'll do it now and get back to you

**Comment by ranjib** [comment]
FYI: The function dropdown in timer, use that to choose macro instead of equipment

**Comment by lironalm** [comment]
I can confirm it works in 3.1
thanks
