### ISSUE TITLE
Componentize driver configuration ui

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#1019]
Right now reef-pi used a single text box for drivers specific configuration during the create or modify logic. This works for some cases , like ph driver has only one configuration (i2c address) but  sub-optimal for some other drivers, e.g. pca9685 have i2c address and port. 

Make driver create/modify UI componentized, as in each driver should be able to specify thei own configuration UI.

**Comment by Ranthalion** [comment]
I have a branch that goes down this path.  It moves parameters, validation, and order to the driver.  I don't mind picking this up if it can wait about 2 weeks to start.   I think I would have it complete by end of January.

**Comment by ranjib** [comment]
All of these can wait for much longer. these are all slated for 4.0 :-)
