### ISSUE TITLE
validate address before saving

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#1024]
wrong adddres when saved, will cause UI to fail as api will not be able to start up (http server address in wrong). validate this on client side.

**Comment by burningbaal** [comment]
@ranjib is it important to do it client-side or can the server check before actually saving and respond with an error appropriately?

**Comment by ranjib** [comment]
@burningbaal preferably both. Definitely on server side. I'll make sure we get this done in 3.x

**Comment by zekth** [comment]
What about this regex https://www.regextester.com/94502 ?

**Comment by Ranthalion** [comment]
If the port is not provided, it should default based on protocol to 80 or 443.  I though we did that as part of 3.0 release, so I'll also review to see if it's a regression defect.

**Comment by zekth** [comment]
May we still add a fallback route? like localhost:7777 for example?
