### ISSUE TITLE
[Request] API for current light levels on diurnal setting

### ISSUE THREAD

**Issue by sfgabe** [reef-pi/reef-pi#1041]
Currently I can only get diurnal lighting info about start / end time and min/max values. Is it possible to get a current reading (ie: time: 10:30 value: 35%, time: 14:30 value: 65%, etc)?

It seems like the info is in there somewhere, I'm wondering if its easy to parse out in the API?

**Comment by ranjib** [comment]
Its not exposed via api. I think its a good idea to add that. Let me add it in the TODO list

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1285
