### ISSUE TITLE
Add support for humidity sensor [Request] 

### ISSUE THREAD

**Issue by driverinla** [reef-pi/reef-pi#1051]
Great job on the project.

I would like to add an environment temperature and humidity sensor such as AM2302. I believe it would be great to have these additional data around the reef and have a better understanding of what is going on related to outside environment of the aquarium.

Would it be possible to include these options in a future release?
Thanks!

**Comment by ranjib** [comment]
Temperature sensor support we already have. I have plans to add support for one of the adafruit humidty sensor breakout board. I am updating ticket to reflect this. Let me know if you have any thoughts. The recent work on HAL makes it easy to support new drivers.

**Comment by inktomi** [comment]
A humidity sensor support would be nice for my use as well, where I'm using a ReefPi to control several poison dart frog terrariums.

**Comment by ranjib** [comment]
I have added support for sht31d driver. It will expose two analog channels . Channel 0 will provide temperature, while channel 1 will provide humidity values. These can be hooked up to ph controller for the time being and used for charting/equipment control

**Comment by inktomi** [comment]
Thank you! This will be great, and there are even weather-sealed SHT31-D solutions out there, if they come back into stock.. I'm looking forward to wiring one up!

**Comment by bensbrowning** [comment]
I would love this also. I am building a massive system of FW planted paludariums (a bunch of different sizes and compositions connected by pumps and a shared sump) in my foyer and am orchestrating the whole thing from pi. It would be nice to have this available and not have to hack something together for the above-ground bits of the environment.
