### ISSUE TITLE
Temperature Probe Data Should have Year in the Database

### ISSUE THREAD

**Issue by adityaduggal** [reef-pi/reef-pi#1052]
**Describe the bug**
I have checked the json files for the temperature probe in reef-pi v3.2 and found that the chart data and historical data have date in format Mon-Day-HH:MM, now this is missing the most important part of the date which is YEAR. I would request you to kindly add the year PART since the change of the year the graphs became invalid

This is the sample of the json in `/api/tcs/id/usage`

`time': u 'Feb-13-18:00'`

**Expected behavior**
The data should be as below:
`time': u 'Feb-13-2020-18:00'`

**Desktop (please complete the following information):**
 - Device [pi0w]
 - reef-pi version [3.02]
 - Browser [any]

**Comment by ranjib** [comment]
We are going with this format: Feb-13-18:00, 2020
