### ISSUE TITLE
Temperature Calibration Lost After Edit

### ISSUE THREAD

**Issue by clownfish44** [reef-pi/reef-pi#1053]
I was editing the temp to turn on notifications and it lost the calibration. 
![image](https://user-images.githubusercontent.com/15145228/74998132-ecb48c80-5425-11ea-9381-8b64654d9783.png)

v3.2

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/issues/1013

**Comment by Ranthalion** [comment]
Fixed by #1211
