### ISSUE TITLE
Water Test Recording Chart / Graph [Request] 

### ISSUE THREAD

**Issue by spaelectronics** [reef-pi/reef-pi#1070]
I think it would be beneficial to have a place to record your test results from manual test kits... Like just a place to record and keep a history of test results... along with maybe some graphs?

**Comment by ranjib** [comment]
I like the idea.Im not sure if graph will be useful, since there is no way to enforce testing an periodic intervals.

**Comment by spaelectronics** [comment]
That's true. We can do it without a graph.

**Comment by cnidus** [comment]
I think the graph would be cool though. It wouldn't _need_ to be enforced at intervals, but perhaps you could send alerts/reminded though to encourage it.

**Comment by inktomi** [comment]
Over time you could graph the results, since you'd capture the time the result was entered and the numerical value. Any number of graphing libs should be able to present that kind of data visually.

**Comment by ranjib** [comment]
@inktomi its not a series graph, individual datapoints can have different time interval in between them, hence plotting them as normal time series may not make sense. But yes, we can assume /treat the measurements as consistent interval and plot it in that way. 
I have release 3.4 with a complete API of journal subsystem. This will allow user to add/remove/update parameters which can then have records (individual observations). We only have the basic CRUD UI for the parameters and not for the records for individual parameters. Once thats done (most likely next release), I'll close this ticket and consider it as done.

**Comment by ranjib** [comment]
@zekth @Ranthalion i could use some help with implementing the record ui for individual parameters  that will allow users to add an individual observation for a specific parameter.
Let me know if any of you interested  :-)

**Comment by Ranthalion** [comment]
> @zekth @Ranthalion i could use some help with implementing the record ui for individual parameters that will allow users to add an individual observation for a specific parameter.
> Let me know if any of you interested :-)

I'm working through a couple of other features (light profiles and ADS1015/ADS1115), so it would be a while before I could tackle this.

**Comment by Craigo1972** [comment]
Would love this, and be able to add graphs to dashboard, I see there is a journal tab but can't enter values or is the Journal tab for something else

**Comment by zekth** [comment]
Is the API available now?

**Comment by ranjib** [comment]
@zekth yes, here is the crud api: https://github.com/reef-pi/reef-pi/blob/master/controller/modules/journal/api.go#L9
and here is the details of domain object: https://github.com/reef-pi/reef-pi/blob/master/controller/modules/journal/parameter.go#L10

The crud API allows users to define `Parameter` objects. and once added user can add entries against existing parameters. The idea is user will create parameters like Mg, Ca , Part A, Part B etc.. and then can add how many ml dosed as individual entries. 
Thanks @zekth

**Comment by Craigo1972** [comment]
Sorry newbie question again, So I have set up parameters but how do I add entries against the parameters?

**Comment by ranjib** [comment]
journal ui is in master, it will be shipped with 5.0 release
