### ISSUE TITLE
Emit metric on equipment status changes

### ISSUE THREAD

**Issue by pvpacheco** [reef-pi/reef-pi#1071]
**Is your feature request related to a problem? Please describe.**
Currently, there is no telemetry metric been emitted when changing the on/off status of outlet configured equipment. It makes it impossible to put equipment status on external Prometheus/Grafana dashboards.

**Describe the solution you'd like**
I'm new to the project so, unfortunately, I don't have a development environment available yet, but I took a look at the code: is an `EmitMetric` call on the `Equipment` module all it takes?

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1077
