### ISSUE TITLE
LCD screen not working

### ISSUE THREAD

**Issue by Simonv92** [reef-pi/reef-pi#1073]
**Describe the bug**
I cannot use an integrated display attached by HDMI to see reef-pi dashboard. I'm running fine reef-pi on raspbian with desktop.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Device  Pi3
 - reef-pi version 2.0.
 - Browser Firefox

**Additional context**

**Comment by ranjib** [comment]
reef-pi dashboards is exposed as any other website. So if your pi's desktop ui is visible via the HDMI, then just open the browser and access the UI. Im closing this as it does not seem to have any reef-pi specific issue. Feel free to reopen this if thats not the case
