### ISSUE TITLE
Issue when adding Multiple PH Drivers

### ISSUE THREAD

**Issue by spaelectronics** [reef-pi/reef-pi#1082]
**Describe the bug**
I get an error when adding a second PH Driver with a different address.

However, if I add it using the default address, it will add fine, then I have to go edit it, and change the address.

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Drivers'
3. Click on '+'
4. Select 'ph-board or ph-ezo'
5. Enter an address different from default. (68 for ph-board, or 69 for ph-ezo)
6. See error when saving.

**Comment by ranjib** [comment]
@spaelectronics my sincere apologies for responding so late. I just tried this and was able to add ph-board with different address that the default one. Can you please provide a screen shot if this is still happening?

**Comment by ranjib** [comment]
Closing this, please feel free to reopen if you are still encountering this issue
