### ISSUE TITLE
3.3.1 Error creating : Remote I/O error

### ISSUE THREAD

**Issue by stvnmbr1** [reef-pi/reef-pi#1083]
**Describe the bug**
fresh install of reef-pi latest version.

**To Reproduce**
adding PCA6985, 1000 PWM freq, 40 address
HTTP 500 error / Error creating : Remote I/O error

**Expected behavior**
adds driver

**Screenshots**

sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: 70 -- -- -- -- -- -- --

**Additional context**

Raspberry Pi 3 Model B Plus Rev 1.3

tried deleting all folders, removing DB, 
enabling dev mode lets me add the driver but it doesn't seem to work when i turn it off aswell.

**Comment by stvnmbr1** [comment]
edit:
it does work when using  the suggested address when creating the driver (64), dunno why it starts doing this. it used to work with 0x40 or 40.

upgraded to latest, still works

if this is not a bug in reef-pi with the address set, you can close this :)

**Comment by spaelectronics** [comment]
I posted about this bug the other day, except I was trying to add a ph driver. Nice to know I'm not the only one.

**Comment by stvnmbr1** [comment]
I see but you could change the address after adding the driver. I still need to use the default address 64 instead of 40. If i change it to 40 it stops working.

**Comment by spaelectronics** [comment]
Yeah, I thought it worked, but it didn't.

I guess I thought it worked when it updated successfully.

**Comment by ranjib** [comment]
The UI has always been using decimal values instead of hexadecimal. Which means 0x40 is 64. This has been bit confusing since the beginning but its consistent. You can check the reference here, where Im using 99 as EZO i2c address. 
So, to summarize its always decimal equivalent of the hexadecimal address. Im closing this, if your problem persist or you think theres other issue, feel free to reopen
