### ISSUE TITLE
Temperature calibration resetting after 2 minutes 

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1087]
When I calibrate my temp probe it resets back to what it was before calibration. If its reading 74 but actually supposed to be 77 I hit calibrate make it 77 and it will change the temp to the right temp then a few minutes later it resets. Here is a picture of it happening.
![ptemp  calibration resetting](https://user-images.githubusercontent.com/22088453/77819004-d85f5180-70ad-11ea-8fbc-f6df41b335b9.JPG)

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/issues/1053

**Comment by gminton86** [comment]
I dont know why but now it has fixed itself and the calibration has finally stuck

**Comment by Ranthalion** [comment]
Fixed by #1211
