### ISSUE TITLE
Lighting : no extra profiling available in settings / Diurnal ignores MIN setting

### ISSUE THREAD

**Issue by stvnmbr1** [reef-pi/reef-pi#1088]
Fresh install of latest reef-pi on RPI3

I can only see fixed, interval, diurnal as set options.

I would like to use my own interval settings for sunset and rise, as I leave the Royal blues at 1% at nights. There used to be 24 sliders but I can't seem to get them back

Did not find any usefull info except https://github.com/reef-pi/reef-pi/issues/859
Did not find a guide explaining how to set up the other profiles as well?

Diurnal ignores the MIN setting and shuts everything down at "End time", I can see in the logs that it does take MAX setting in account
Interval does not fade to set intensity point, it just switches to the set intensity at the set time.

**Comment by ranjib** [comment]
Fixed, interval, diurnal are the only profiles currently available via the UI. Rest is only configurable using API. We intend to bridge that gap in 4.0. I'll track it using this: https://github.com/reef-pi/reef-pi/issues/1089. Lets start a separate thread on docs or r2r thread if you want to try those using API.
We never supported 24 sliders in the UI. It used to be 12 sliders at 2 hours interval. The current interval profile can replicate that exact ui. If you provide a specific example we can detail it.

The min setting is used to  bring down PWM values to 0 below the "min threshold". It is used to avoid flickering , as certain lights flicker beyond a certain pwm values. Dont use it  (set it to 0). 
Can you share the details of interval profile you are trying, and what you were expecting at a given time vs what reef-pi is actually doing.  it will help me understand the issue.

**Comment by stvnmbr1** [comment]
Ok, wasn't sure if this was an issue on my side. So i have to PUT the profile settings through API, as shown in #859. I'll try to get my interval going first and afterwards i'll try to add composite. I should be able to find the info on how to this is in the API docs.

I've set the MIN setting to 0 again. Thanks for clarifying .


Example interval.
![rpi](https://user-images.githubusercontent.com/9010189/77903883-e49d0780-7283-11ea-89a0-bad19f81e768.png)

Start lights at 8:30 in the morning, ramp up to midday, shutdown at 11:30 in the evening.
Whites off at 10:00 PM, blues and Royal stay lit until 11:30 in the evening. Royals at 1% during night.

Royal blue shutsdown at end time. leaving a half hour gap of no light. 
Tried 00:00:00 and 23:59:59 as start and end times but this messes up the times on the sliders.
in previous versions you could just set the slider (12 sliders :) ) every 2 hrs.

Right now, EG. WW does not  fade or transition at from 100% at 14:00 to 75% at 16:00.
At 16:00 it sets WW to 75%, instead of gradually dimming from 100% to 75% over 2hrs timespan.

**Comment by ranjib** [comment]
I have tested this with dirurnal settings and it honors min./max settings. We have added UI support for sine, lunar , random profile. Rest will be only supported by API
