### ISSUE TITLE
ATO Usage rollover , alert and disable on alert inconsistency

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#1104]
- Hourly usage of ato data in reef-pi metric system resets usage: Establish correct behavior. If reset is required, make it more explicit (tooltip for "alert on disable")
- Alerts when configure for usage, along with "alert limit" rolls over and does not reset hourly. Unsent alerts are flushed in the beginning of new hour: Investigate, reproduce and make behavior consistent with to usage metric

**Comment by Simonv92** [comment]
Don't know if you've already figure it out, on 3.3.1 the ATO "disable on alert" doesn't works fine. If I set a value below 100s ATO turn OFF immediately after a sensor trigger, if I set a value of 120 or greater the ATO will never be disabled.

**Comment by ranjib** [comment]
I have pushed a fix recently that I think will resolve this issue https://github.com/reef-pi/reef-pi/pull/1121

**Comment by ranjib** [comment]
Fix available in current release
