### ISSUE TITLE
[Request] CodeBlock support in Macros

### ISSUE THREAD

**Issue by cnidus** [reef-pi/reef-pi#1107]
**Is your feature request related to a problem? Please describe.**
More complex tasks involving multiple sensors like AWC currently seem to require nested reversible macros and frankly are pretty unintuitive as they are currently. I understand the desire to keep it all GUI and simplify things for new users, but macro's in their current form seem to penalize both basic and advanced users.

**Describe the solution you'd like**
Rather than GUI, allow basic code blocks as an 'advanced mode' for macros. CodeBlocks should be able to do basic programmatic structures like "If-else" statements, refer to multiple sensors, outputs, other macros and access basic math libraries etc. 

For example, I'd like to write an auto-water-change function, that would look something like this in a codeblock:
For this pseudo-code, assume I have three optical level sensors; ATO-Low, ATO-High & AWC-Low. I presume the ATO would fill between ATO-Low & ATO-High (to prevent too much pump cycling w/ a single sensor), AWC empties from ATO-High down to AWC-Low, then refills.

<triggered by Timer>

```
def AutoWaterChange:
    #AutoWaterChange Macro v0.1

    #First let's check the ATO is at full level before we start the empty&fill cycle, to make sure salinity is not going to get affected by the influx of fresh salt water.
    if Inlet('ATO_High') == True:
        #Shutoff the ATO macro till we're done.
        Macro('ATO').status = 'Disabled'
        #Emit a log entry
        print "ATO Disabled"

        #Start to empty down to the AWC-Low level.
        #TODO: add some timeout logic in here as well to deal with overly long-running pumps / failure. For now just K.I.S.S...
        while Inlet('AWC_Low') == True:
            print "AWC starting to empty"
            Equipment('AWC_EmptyPump').status = 'On'
            time.sleep(1)   #Slow down the loop a little
            #End While loop
        #Done emptying, stop the pump!
        Equipment('AWC_EmptyPump').status = 'Off'
        print "AWC empty cycle complete"

        #Start to fill, up to ATO_High level
        while Inlet('ATO_High') == False:
            print "AWC starting to fill"
            Equipment('AWC_FillPump').status = 'On'
            time.sleep(1)   #Slow down the loop a little
            #End While loop
        #Done filling, stop the pump and re-enable the
        Equipment('AWC_EmptyPump').status = 'Off'
        print "AWC fill cycle complete"
        Macro('ATO').status = 'Disabled'
        print "ATO Re-enabled"
        print "AWC cycle complete!"
```

**Describe alternatives you've considered**
Using multiple macros, and apparently 'reversible' is a requirement if they're triggered and not just manual.

**Additional context**
This adds an additional advanced 'choose your own adventure' path for advanced users . It will hopefully allow for more concise sharing of macros between users. It's also a similar implementation to other commercial controllers, so hopefully will ease the transition for users of those systems as well.

**Comment by spaelectronics** [comment]
This is exactly what I've been wanting!
This would be the perfect feature!

**Comment by ranjib** [comment]
We'll not be adding [DSL ](https://en.wikipedia.org/wiki/Domain-specific_language) style extensibility in reef-pi. Back in 2.0 we decided to go with UI based macros instead of language based ones. For embedded systems where you dont have access to the underlying system and theres no API, the DSL style make sense. But reef-pi has a full blown API, which means you can do this exact thing with any programming language (python for example) and run it on the same pi as systems unit. That route is way more powerful and elegant. We would prefer to put the effort in making a python client library and document how to do this (i.e. build your own macro with very specific controls and logic).

I am closing this since we don't intend to work on this. But I am open to all feedback.

**Comment by cnidus** [comment]
Ok that makes sense. Native python with a documented client library is fine. The only enhancement I could see is some way to trigger those external code modules from reef-pi and have them visible as stubs in some way within the reef-pi UI. So there's some meeting of worlds.

For example if I was to write my AWC code as an external python script, and wanted it to be on a schedule, i'd probably set it up in crontab, but that would be completely external to the reef-pi UI. It would be nice to still use the reef-pi timers (with the UI ability to disable them etc) but target the external script.

i realize there are obvious security concerns about such things though.

**Comment by richievos** [comment]
@ranjib did any further thoughts/changes around this space materialize? I see your comments about not wanting to have a built-in DSL and instead handle this from outside, so I'm wondering if that happened.

To me, when I first started using Reef-Pi my core expectation was that I'd obviously be able to run some sort of code on events. I just assumed that was what a Macro was. I honestly was expecting I could just setup some Python to trigger on events.

I understand how that can have gotchas though, particularly just the idea of getting stuck with support tickets when people send random tasks in. However for the more advanced user I think getting out of the point and click UI would be very preferable.

Towards the library idea, that does seem useful, but it seems like that idea leads to thinking of reef-pi purely as a Driver system. If reef-pi was just a library for interacting with the API, you'd seemingly need to deal with setting up your own cron jobs, locks (which would require reef-pi capabilities to be added), and idiosyncracies around network call error handling.

I do think creating a complete, reef-pi focused programming language / DSL would likely be a PITA, but I think having reef-pi handle the event detection, and allowing a script to control acting on those events, would be a very powerful combo.

**Comment by richievos** [comment]
Also as a relatively minor note, that I think signifies big value from this. In some of these discussions in issues here and in reef2reef people give out tips suggesting how to setup a macro to do something. It'd be wonderful if they could just send a macro snippet of text that the other person could copy-paste in. Even if that just meant the macro builder UI switched from a UI of components to a text box equivalent with each line in the box representing a step in the macro.
