### ISSUE TITLE
Email Alert for PH (coding is displayed in email)

### ISSUE THREAD

**Issue by spaelectronics** [reef-pi/reef-pi#1108]
The text in the email for the PH Alerts shows code in the text of the email.

See screenshot below:

![20200410_230529](https://user-images.githubusercontent.com/2513149/79033931-50367d00-7b80-11ea-92bb-66abdb2dbbb5.jpg)

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1111

**Comment by ranjib** [comment]
Fix is merged in master, we'll ship it in next release
