### ISSUE TITLE
My reef pi froze up for the first time in a year

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1114]
at 3 am my reef pi encountered a 500 internal server error and I had to unplug it to get it to come back online.

![internal server error](https://user-images.githubusercontent.com/22088453/79473619-622a7c80-7fd3-11ea-9c17-8f2fbc7ad318.JPG)
![CPUMemory](https://user-images.githubusercontent.com/22088453/79473625-648cd680-7fd3-11ea-9620-1123d0cbbf13.JPG)

**Comment by gminton86** [comment]
I feel like it has something to do with an update that firefox has implemented might want to look into it more cause it could possibly cause a tank crash

**Comment by gminton86** [comment]
my tanks temperature dropped to 74 before I noticed it

**Comment by ranjib** [comment]
Do you have system log or something that we can use to deduce whats going on?

**Comment by gminton86** [comment]
How do I get it and Ill upload it

**Comment by gminton86** [comment]
it doesnt have anything listed under log or errors
