### ISSUE TITLE
Invalid password

### ISSUE THREAD

**Issue by steve-techno** [reef-pi/reef-pi#1116]
When trying to login to reef-pi after no login problems you get Invalid username or password.
returning to the origional WiFi address no login problems occur when running reef-pi 3.3.1

**To Reproduce**
From a running reef-pi change the wifi connection using raspi-config
in raspi-config  goto network
in network change ssid and wifi password
ok
exit and reboot

This now results in the user name/password issue.

Returning to the original Wifi connection results in no login issues.

cli login in both cases results in no issues

**Desktop (please complete the following information):**
 - Device Pi zero W
 - reef-pi version 3.3.1
 - Browser [Google Chrome is up to date
 - Version 81.0.4044.113 (Official Build) (64-bit)]

**Additional context**
IP Address changes between the 2 networks but retains the default gateway and service provider

**Comment by ranjib** [comment]
Apologies for responding so late. reef-pi uses session based authentication using cookie. Cookies are saved by the browser and i think that is what messing things up here. If you refresh your cache/cookie this should resolve. One way to diagnose this will be to try logging in from a new tab in incognito (chrome) or private (safari) mode. Feel free to reopen if this is not the case,
