### ISSUE TITLE
Setup dev environment, build fails

### ISSUE THREAD

**Issue by markus902** [reef-pi/reef-pi#1126]
Hi everybody,

I'm kind of new to go and react. I tried to follow the guide to setup the dev environment, but the build fails. 

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! reef-pi@1.0.0 build: `webpack -d`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the reef-pi@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
make[1]: *** [build-ui] Error 2
make: *** [bin] Error 2

Tried: 

- updating NPM

Thanks for your help.

**Comment by zekth** [comment]
Which version do you use?
Did the `make install` worked properly?

**Comment by markus902** [comment]
Did not run `make install` before. Now I did and it worked fine. Node version is 6.14.4 . Same issue persists. When running make, build fails.

**Comment by zekth** [comment]
Yeah i'll make an update on the document. You may need to use node >=10. Also regarding the nodejs version management i highly recommend to use nvm: https://github.com/nvm-sh/nvm

**Comment by markus902** [comment]
Sorry, i looked up the npm version, which is 6.14.4. Node is on 12.1.0. I updated everything just to be sure. The error persists.
Here is the error section where the build fails:

[./front-end/assets/sass/style.scss] 3.06 KiB {main} [built] [failed] [1 error]

ERROR in ./front-end/assets/sass/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, scandir '/Users/markus_kuehn/go/src/reef-pi.nosync/node_modules/node-sass/vendor'


Does that tell you anything?

**Comment by zekth** [comment]
I'll dig into but Node 12 has instroduced some breaking changes for some libraries. Could you try Node 10? Sorry for that.

**Comment by markus902** [comment]
Thanks, you've been a great help so far. Installed NVM and downgraded to 10.0.0. But that was not the issue. I had to run `npm rebuild node-sass` to fix it.

Ok, now the last step. How do I start up the program and the server. The docs are not very precise. How do I run `./bin/reef-pi.yml -config reef-pi.yml` ?

**Comment by zekth** [comment]
> Thanks, you've been a great help so far. Installed NVM and downgraded to 10.0.0. But that was not the issue. I had to run `npm rebuild node-sass` to fix it.

That's because the `node_modules` were already there and compiled for node 12.

Regarding the startup of the server maybe @ranjib or @Ranthalion can help?

**Comment by ranjib** [comment]
@markus902  i am running node 10.16.3 and npm 6.9.3.
make start-dev should start a local reef-pi backend and make ui-dev will start the webpack dev server. those two should be enough to get reef-pi running in local setup, after everything is installed.

**Comment by ranjib** [comment]
this doc calls out start-dev command. I think we should add make ui-dev as well https://github.com/reef-pi/reef-pi/blob/master/docs/development_environment.md

**Comment by ranjib** [comment]
@markus902 is this still an issue?

**Comment by markus902** [comment]
Thanks a lot, I think I'm all set.
