### ISSUE TITLE
Bad sensors (temperature) list

### ISSUE THREAD

**Issue by Vadech** [reef-pi/reef-pi#1127]
My sensor doesn't appear in sensor selector:

I've found the code in the repository:
`func (t *Controller) sensors(w http.ResponseWriter, r *http.Request) {
	fn := func(id string) (interface{}, error) {
		fs := []string{
			"/sys/bus/w1/devices/28-04177049bcff",
			"/sys/bus/w1/devices/28-2392abcabcabc",
			"/sys/bus/w1/devices/28-f0a0a0abbd4f",
		}
		if !t.devMode {
			files, err := filepath.Glob("/sys/bus/w1/devices/28-*")
			if err != nil {
				return nil, err
			}
			fs = files
		}
		sensors := []string{}
		for _, f := range fs {
			sensors = append(sensors, filepath.Base(f))
		}
		return sensors, nil
	}
	utils.JSONGetResponse(fn, w, r)
}`

But my sensor is 28-0300a279dec3

How can i add this is the list ?

![image](https://user-images.githubusercontent.com/6782832/80751202-acf6d900-8b29-11ea-965d-d976e0408f9e.png)

![image](https://user-images.githubusercontent.com/6782832/80751245-bb44f500-8b29-11ea-9385-f34b3c94cc84.png)

I've find this method but i don't know how to call it:
![image](https://user-images.githubusercontent.com/6782832/80751325-dc0d4a80-8b29-11ea-9401-e8c61e2a43ab.png)

Thank's by advance for your help.

**Comment by Ranthalion** [comment]
This looks like you are running reef-pi in Dev mode.  Make sure you don't have your installation running with Dev Mode enabled.
![image](https://user-images.githubusercontent.com/1632746/80768988-df98d580-8b19-11ea-981b-e49a178b682e.png)

**Comment by Vadech** [comment]
Yes, thank's a lot. It's ok now. 

![image](https://user-images.githubusercontent.com/6782832/80769292-09b7bb00-8b4d-11ea-8367-6bb17f9f3299.png)
