### ISSUE TITLE
Error when I turn on Display 

### ISSUE THREAD

**Issue by Simonv92** [reef-pi/reef-pi#1129]
I've build a system with a Raspberry Pi 3 B+ running last version of Raspbian Buster with desktop
Version: February 2020
Release date: 2020-02-13
Kernel version: 4.19

I then attach an original Raspberry Pi 7" LCD,
Reff-pi works just fine after the installation, when I activate the Display in the configuration tab I have this error:

{"error":"strconv.Atoi: parsing \"117\\n\": invalid syntax"} | HTTP 404

Brightness control works fine but the slide doesn't always move, after that I've tryed to connect to "myhostname".local with Chromium and Firefox directly on the Raspberry Pi and with both browser I can reach the Reef-Pi Dashboard

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1139

**Comment by ranjib** [comment]
Fixed. Available in latest release
