### ISSUE TITLE
Camera not functioning

### ISSUE THREAD

**Issue by indymx** [reef-pi/reef-pi#1141]
**Describe the bug**
Camera does not work. 

**To Reproduce**
Click on the checkbox in configuration, refresh and click on the Camera in the menu.

**Expected behavior**
I expect the camera to work. 

**Screenshots**
![image](https://user-images.githubusercontent.com/882893/81112161-3a507980-8eec-11ea-93cc-4e5f7f2d1e32.png)

**Desktop (please complete the following information):**
 - Device Pi3, Pi4 
 - reef-pi version 3.1.1
 - Browser Chrome 81.0.4044.129
 - Raspberry Pi NoIR Camera Board v2 - 8 Megapixels

**Additional context**
Tried on fresh clean installs of the OS and Reef-Pi. Camera is verified working by using raspbian command line apps

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1145

**Comment by ranjib** [comment]
Fix is landed on master. Available in the current release
