### ISSUE TITLE
Timers not triggering macros

### ISSUE THREAD

**Issue by zielit73** [reef-pi/reef-pi#1142]
Timers I create can trigger on/off only separate equipment. When I set it up to run macro nothing happens. I tried with both reversible and non-reversible macros, so sadly no subsystems or modules can be started/stopped via timers.

Macros run fine when triggered manually. Trigger runs fine when equipment option has been choosen.

1. Go to 'Macros'
2. Create macro with multi steps to trigger equipment and/or subsystem (ATO for example)
3. Go to "Timers"
4. Create the time to run for example every 2h and run macro created in step 2

**Expected behavior**
Macro being executed automatically by timer

**Screenshots**
Macro
![image](https://user-images.githubusercontent.com/64910827/81189751-efcf0b80-8f84-11ea-9dc9-e95180417edb.png)

Timers (test runs OK, System startup doesn't)
![image](https://user-images.githubusercontent.com/64910827/81189940-3290e380-8f85-11ea-8524-8befe704d68e.png)

**Desktop (please complete the following information):**
 - Device Pi0W
 - reef-pi version 3.0
 - Browser Chrome
 - Version 81.0.4044.129 

**Additional context**

**Comment by ranjib** [comment]
Set minute to 1 or any other fixed value . * stands for every minute..

**Comment by ranjib** [comment]
@zielit73 can you verify if this is an issue with the latest version of reef-pi ?

**Comment by zielit73** [comment]
That doesn't solve the problem (seting minute to value), Timer with exactly same settings works fine when running single equipment, only when macro option is selected it doesn't run it.

I have pulled the code 2 weeks ago so I assume is the latest, About page says it is 3.0

**Comment by ranjib** [comment]
The latest reef-pi release is 3.3.1, can you install it and let us know if the problem still persist.

**Comment by zielit73** [comment]
I did the upgrade to 3.3.1 unfortunately that didn't solve the issue.

**Comment by CTYReef** [comment]
I have this same issue with Reef-Pi version 3.3.1.  Macros run as intended when triggered manually, But when triggered by a timer, they don't run.  

I found by accident that when I make Macros reversible most of them will run, but individual steps are skipped consistently.

Device Pi0W
reef-pi version 3.3.1
Browser Chrome
Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by CTYReef** [comment]
I have seen another effect that might not be exactly aligned with this issue, but when I tried to set up nested macros, and manually trigger the top level macro, the nested macro doesn't work unless the "Turn On/Turn Off" option for that nested macro is set to "Turn Off".

**Comment by ranjib** [comment]
Folks, i just tried to fix this, but was not able to reproduce this issue. I am able to successfully trigger a macro with a timer. Follow is the example i am  trying: 
![macro](https://user-images.githubusercontent.com/316306/82294983-d904bd80-9963-11ea-8f5d-b0a3434c8f5e.png)


![timer](https://user-images.githubusercontent.com/316306/82294986-d99d5400-9963-11ea-9299-6cbda28c91f0.png)


Logs indicating this is working as expected:
```
2020/05/18 23:58:00 macro subsystem. Running: Feed Start
2020/05/18 23:58:00 macro-subsystem: executing step:  equipment id: 2  state: false
2020/05/18 23:58:00 Euipment: 2 On: false
2020/05/18 23:58:00 macro-subsystem: executing step: sleep for 3 seconds
2020/05/18 23:58:03 macro-subsystem: executing step:  equipment id: 2  state: true
2020/05/18 23:58:03 Euipment: 2 On: true
2020/05/18 23:58:03 macro subsystem. Finished: Feed Start

```

Can you share the exact details of the timer and macro thats not working? The example shared in the first post has a wrong timer field.

**Comment by zielit73** [comment]
For me still doesn’t work, where is location of that log? It would help in investigation for sure.

 

Mikolaj

**Comment by zielit73** [comment]
OK So you remember I had version 3.0 and upgraded to 3.3.1. The macros that I have created under 3.0 still cannot be triggered via timer, but we have some progress.

 

I did try with fresh macro created under 3.3.1 and it worked but only if it’s exactly steps as your - 1 equipment on, pause and then same equipment off. But if I have different equipment  it won’t work (even if I edit macro that just worked with single equipment).

 

Mikolaj

**Comment by CTYReef** [comment]
Ranjib, have you tried it with with the macro set to non-reversible? The set of nested macros (both initially created as non-reversible) in the images below work fine when run manually (Although note that I had to set the first step in the "Dual Drain" macro that calls the "Pool Drain" macro to "Turn Off".  If it is set to "Turn On", that called macro will not run.  Why is that even an option for a non-reversible macro?)
![Dual Drain Macro](https://user-images.githubusercontent.com/49430745/82448118-8b24ae00-9a66-11ea-911a-d8526d7f1ab1.JPG)
![Pool Drain Macro](https://user-images.githubusercontent.com/49430745/82449041-d68b8c00-9a67-11ea-9372-0eeb500225f0.JPG)

When I try to trigger the "Dual Drain" macro with a timer, nothing happens.  However, when I make "Dual Drain" reversible, then it does start running from a timer, but does not execute any of the steps after the call to the "Pool Drain" macro. Then, when I make both macros reversible, it does start running from a timer, does execute the macro call in the first step and executes the remaining steps in the "Dual Drain" macro, EXCEPT for the fourth step (the 17 second "Wait").

And, yes, I am trying to use Reef Pi as pool controller.

**Comment by mtorzews** [comment]
I am having the same issue. Timer is not triggering Macros.
I have Version 3.3.1

I tried the timer and macro as written by Ranjib on May 19th. This worked as expected. 

But when trying to trigger my actual macro nothing happens. Maybe this has to do with multiple actions or actions involving doser.

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/49848602/89556894-06813a80-d7e0-11ea-8120-960495371495.png">
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/49848602/89557034-36304280-d7e0-11ea-96b4-c49a745235d7.png">

**Comment by mtorzews** [comment]
Update, I had left the test timer set to trigger my real macro with month = *, week = *, day = *, hour = *, minute = *, and second = 0 on. 10 minutes later while I wasn't paying attention the real macro started. 

Now I'm wondering if it has to do with pi being too busy at the timer trigger time and missing it. ????  My original timer had one opportunity per day. The test timer tried every minute and it caught on approximately the 10th try. I am running a pi-zero. CPU is normally around 0.2 usage but peaks to 0.6 at times. Memory is around 25%.

**Comment by ltoolio** [comment]
I'm having the exact same issue, but I'm a completely new user to Reef-pi.

Running it on a Pi4B, Reef-pi 3.4.  Created a macro that turns something off, waits 20 seconds, turn it back on.  Set the timing to run every 0 second.  And nothing happens.

**Comment by ranjib** [comment]
Non - reversible macros can not be triggered via Timers. This is by design. Timer internally works by a simple up/down feature  for macro this maps to reverse execution of the steps : 1  on -2 on ->3on ->3 off ->2 off -1 off. This may not make sense for all macros, which is why users have to explicitly call out a macro as reversible, after which it can be used by timer. We have to do a better job to help user understand that the macro needs to be reversible, instead of silently failing it.

**Comment by ranjib** [comment]
Folks, do let me know if you are still experiencing this issue, after making the timer reversible. I did another round of checks without encountering any bugs. If macro+ timer still not working for you, please share an example that I can use to reproduce. 

Macros are complex. Since they allow sleep time , when used with timer be careful to ensure overall macro run time is significantly smaller than the interval.

**Comment by mtorzews** [comment]
Hi Ranjib, I read your comment and still didn't understand. I went searching on reef2reef and found this post. https://www.reef2reef.com/threads/reef-pi-an-opensource-reef-tank-controller-based-on-raspberry-pi.289256/post-7104116

From that I was able to get my macro+timer working the way I intended. 

I don't know what you mean about sleep time, and overall macro run time. Can you explain or point me to where it is explained?

Thanks, Mike

**Comment by ltoolio** [comment]
> Folks, do let me know if you are still experiencing this issue, after making the timer reversible. I did another round of checks without encountering any bugs. If macro+ timer still not working for you, please share an example that I can use to reproduce.
> 
> Macros are complex. Since they allow sleep time , when used with timer be careful to ensure overall macro run time is significantly smaller than the interval.

I can confirm in my case that making the timer reversible that everything worked as expected.  I'll presume a case of RTFM.

**Comment by CTYReef** [comment]
> Folks, do let me know if you are still experiencing this issue, after making the timer reversible. I did another round of checks without encountering any bugs. If macro+ timer still not working for you, please share an example that I can use to reproduce.
> 
> Macros are complex. Since they allow sleep time , when used with timer be careful to ensure overall macro run time is significantly smaller than the interval.

Hello Ranjib,
Yes, following the instructions of making the macros reversible, writing the macro steps in reverse, and inverting the On/Off state of the individual steps did resolve the the issues I was having.  Thank you for the clarification.

**Comment by CTYReef** [comment]
> > Folks, do let me know if you are still experiencing this issue, after making the timer reversible. I did another round of checks without encountering any bugs. If macro+ timer still not working for you, please share an example that I can use to reproduce.
> > Macros are complex. Since they allow sleep time , when used with timer be careful to ensure overall macro run time is significantly smaller than the interval.
> 
> I can confirm in my case that making the timer reversible that everything worked as expected. I'll presume a case of RTFM.

Hello Itoolio,
Was there a manual or site reference that explained this?  If so, I am also guilty and need to know where that manual/reference resides.  If not, don't beat yourself up.
