### ISSUE TITLE
Prometheus Prefix issue

### ISSUE THREAD

**Issue by indymx** [reef-pi/reef-pi#1173]
I noticed today that the prometheus metrics are getting the prefix from the Adafruit Telemetry page. 

```
# TYPE reefpiwhite_bar_front_channel_1 gauge

 reefpiwhite_bar_front_channel_1 67.49801345846507
```

Would it not be better to set the prefix from the Configuration page Name field as pretty much everyone will have that set and not everyone will set it in the Adafruit Telemetry?

The reason I feel it should be changed is that for those of us who are using multiple installs, I have to set a prefix on Adafruit Telemetry to get the prefix set so that my Grafana/Prometheus dashboards are not a mess.

**Comment by ranjib** [comment]
I concur. The current telemetry abstraction was built for adafruitio, which does not have any notion of tags, and then later retrofitted to accommodate prometheus. I am thinking of refactoring that module to address this and similar structural challenges. I do not plan to work on this soon, but expect this to be rolled up in 4.0 or 5.0 series, for sure, as part of the larger telemetry refactoring

**Comment by ranjib** [comment]
BTW, the name prefrix was there to distinguish between different reef-pi from same user.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1281 
prom metrics will not have adafruit specific prefix anymore
