### ISSUE TITLE
PH Equipment Control Only During X - Y Time/Date

### ISSUE THREAD

**Issue by zer0signa1** [reef-pi/reef-pi#1189]
Looking to see if it would be possible to allow the PH Control section to only run during certain times a day.  This would be a great benefit for Planted tanks, where using the PH Controller to control the Co2 Gas Injection rate. 

**Describe the solution you'd like**
I would like to allow the Ph Control function to run only during a certain window.  This could be toggled on an off for people that would not require this window.   But this will allow Planted Tank people, that inject Co2 to use the PH Probe to hit their Target PH Level only during a certain window. 

Example: PH is 7.5 in the AM, but need to hit 6.5 from 12PM -> 7PM.  The controller enables the kasa smartplug to turn on the Co2.  But only during that defined window, if the PH reaches 6.4, it turns off the Smart Plug and stops injecting Co2 in the water.  Then after 7PM the controller stops functioning, and allows the tank/system to gas off and return the PH to normal.

**Comment by zer0signa1** [comment]
My only hack/solution to this right now, would be to have a custom crontab setup in Raspbian.  That executes an IPtables command to block the IP of the kasa smart plug during Off hours, and removes that block during Co2 On hours.

**Comment by Ranthalion** [comment]
You might also be able to handle this through macros.  Schedule a macro to turn off the pH subsystem and outlet at 7pm, and another macro to turn the pH subsystem back on in the morning (or whenever).  The big drawback with this option is that it will disable all pH reading during that time.

![image](https://user-images.githubusercontent.com/1632746/87797079-38723300-c818-11ea-86ab-ecf8c1df18f0.png)

**Comment by zer0signa1** [comment]
Thank You;  Yeah, I was hoping to continue to receive the PH readouts/charting during off hours.

**Comment by Ranthalion** [comment]
Another idea could be to create 2 pH entries using the same analog input.  
![image](https://user-images.githubusercontent.com/1632746/87799614-71f86d80-c81b-11ea-8e0a-c63330534f09.png)

Then Turn off the controlled one in the macro.
![image](https://user-images.githubusercontent.com/1632746/87799569-6311bb00-c81b-11ea-9788-de4e130f8c3a.png)

**Comment by zer0signa1** [comment]
That is a solution I could get behind!  Thank You!

**Comment by ranjib** [comment]
Im closing this since there is not action item from our end. Feel free to reopen this ticket if you want to discuss
