### ISSUE TITLE
Connectors configuration error after running  "apt full-upgrade"

### ISSUE THREAD

**Issue by Robbyts** [reef-pi/reef-pi#1190]
Connectors stoped working after running  "apt dist-upgrade". Configuration/connectors page displays: TypeError: Cannot read property 'analog-input' of null.

https://prnt.sc/tmj0g1
https://prnt.sc/tmj11e

**Comment by ltoolio** [comment]
Same issue here with the same resultant error message in the UI.

**Comment by ScottMinn** [comment]
I'm also having the same issue - can't get the lights working again

**Comment by ltoolio** [comment]
I just did a complete wipe of my Reef-pi Pi, installed Buster, performed all OS updates via terminal, installed Reef-pi, reconfigured my Equipment and same error persists.

**Comment by gminton86** [comment]
Its probably an issue with the analog input and not the Reef-pi software.

**Comment by zer0signa1** [comment]
Using Raspberry PI OS - 2020-08-20-raspios-buster-armhf-lite - causes the same issue as full upgrade.

**Comment by AlexReefPi** [comment]
Anyone found a solution to : Configuration/connectors page displays: TypeError: Cannot read property 'analog-input' of null. ?

Tried various solutions (update, database replacement ...) with no success so far.

Any help welcome.

**Comment by zer0signa1** [comment]
> Anyone found a solution to : Configuration/connectors page displays: TypeError: Cannot read property 'analog-input' of null. ?
> 
> Tried various solutions (update, database replacement ...) with no success so far.
> 
> Any help welcome.

For me it was reverting back to Raspberry PI OS from May of 2020

**Comment by DeeEmm** [comment]
I have the same issue here.

**Comment by ranjib** [comment]
Are you all using 3.5 with pi4? I know we had this issue on pi 4, but fixed it with 3.5 release. Please share specific 
raspberry pi and reef-pi version. If this is still an issue.

**Comment by zer0signa1** [comment]
My issue was with 3.4, PI4, and latest Raspberry OS.

**Comment by DeeEmm** [comment]
I was experiencing this issue on Orange Pi with all OS / Reef-Pi 3. But I've now come to learn that Orange Pi is unsupported so have switched to a RPi 3B+ which is fine.

**Comment by ranjib** [comment]
Im closing this since this is fixed on 3.5
