### ISSUE TITLE
After I calibrate the temp sensor I cannot change the check frequency or it will reset my calibration. 

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1191]
**Describe the bug**
If I change the check frequency of the temp sensor after calibrating. It will lose the calibration.

Reef Pi 3.3.1

**Comment by gminton86** [comment]
Just did it again to me I can reproduce it everytime I try

**Comment by Ranthalion** [comment]
The calibration data is stored as part of the temperature controller object.  This may be a defect based on updating the tc object without carrying the calibration data with it.  I'll see if I can confirm that over the weekend.
