### ISSUE TITLE
Can we add an Auto Water Change Capability? 

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1193]
What is the best way to implement an auto water change system on the Reef Pi and can we add a dedicated tab for it.

**Comment by kevinmic** [comment]
I have been using a couple of dosing pumps to make small daily water changes using the dosing pump functionality. It isn't perfect but so far has worked pretty well. My reef-pi auto changes about 1 gallon per day (Its been doing this for over a year without any major issues)

What sort of system did you have in mind?

**Comment by mr-ma** [comment]
I managed to set up a continuous water change routine by extending reef-pi with two self-implemented features (https://github.com/mr-ma/reef-pi):
- Support a direct dose step as a macro step
- Added a wait for temperature step in the macro subsystem
Afterward, I created a macro with a set of actions that, when the reservoir's temperature is good, doses out a small amount (1 Litre) of water from the aquarium and refills it. I have another macro that controls a solenoid valve to fill up the reservoir when it is empty. I use another doser pump to add AquaSafe conditioner to the reservoir on every (tap) water fill-up.
I set a bunch of timers to trigger the water change and reservoir fill-up on arbitrary frequencies. 
I think, as  @gminton86 suggested, having a dedicated tab for water change would simplify things.

**Comment by ranjib** [comment]
Thats super cool @mr-ma  I'll try my best to incorporate some of those in the actual reef-pi. I am taking notes on the dedicated UI tab and thinking if we can roll it up under broader UI customization. Where user can compose custom tab with arbitrary control units (ato, macro, ph, temp etc). @Ranthalion thoughts?

**Comment by ranjib** [comment]
Folks, we have added some more improvements in the macro system and we plan to continue evolving that and not have dedicated water changing system and instead recommend macros for this. Im closing this since i dont plant to work on it. Feel free to reopen this issue if you want still want to discuss this,.
