### ISSUE TITLE
Reject out of range readings for DS18B20

### ISSUE THREAD

**Issue by Ranthalion** [reef-pi/reef-pi#1205]
DS18B20 will occasionally return an invalid value.  The [datasheet](https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf) states the valid range as -55°C to +125°C.  reef-pi should reject any readings outside of this range and retry a few times.

**Comment by ranjib** [comment]
@Ranthalion +1. Are you working on a fix, else I'll pick this up.

**Comment by Ranthalion** [comment]
I am.  I should have a PR for it within a day or 2.

**Comment by gminton86** [comment]
Awesome! Thank You, I have been saying this for a while.
 I rewired my temp sensor to get some noise out but every once in a while I still get a reading of about 200 F then it goes back to normal

**Comment by Ranthalion** [comment]
I'm not sure it will help with the issue described by @gminton86  since the valid range is -67 to 257 F. 

I'm reworking the temperature calibration next, so this may be something I can add to that change.  Perhaps include an expected range for a temperature sensor as well as calibration values.
