### ISSUE TITLE
Light graph 

### ISSUE THREAD

**Issue by Kulawka2** [reef-pi/reef-pi#1221]
Hi, I found a problem in dashboard, if you try setting up light chart, it is impossible to set up light graphs when you try to do it it's change to "Health" straight away.

**Comment by ranjib** [comment]
@zekth do you think you'll get a chance to look into this? :-0) , I'll understand if you are occupied.

**Comment by ranjib** [comment]
We are tracking this here: https://github.com/reef-pi/reef-pi/issues/1236 , please continue the discussion there
