### ISSUE TITLE
Power / current monitoring of AC ports

### ISSUE THREAD

**Issue by elmo2002** [reef-pi/reef-pi#1222]
**Describe the solution you'd like**
Would it be possible to add power monitoring of specific AC output ports? To allow for example power monitoring a return pump to work out cost but also allow an alert if consumption goes up or down meaning a pump has blocked or failed.
Could also be used to monitor that a heater is working correctly, drawing current when outlet is on.

**Comment by ranjib** [comment]
This is a driver specific thing. HS300 driver provides this by exposing 6 outlet (for controlling equipment) and 6 analog inputs (for reading current). The current readings can then be used as ph probes for any control mechanism or just charting.

**Comment by elmo2002** [comment]
Do you have any guides or instructions on how to do this?
