### ISSUE TITLE
Why wont it let me update to 3.4?

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1229]
pi@raspberrypi:~ $ sudo dpkg -i reef-pi-3.4-pi3.deb
dpkg: unrecoverable fatal error, aborting:
 loading files list file for package 'python-pkg-resources': cannot open /var/li                                       b/dpkg/info/python-pkg-resources.list (Structure needs cleaning)

**Comment by ranjib** [comment]
this is not a reef-pi issue. it looks like raspberry pi's  apt is not in good state. run `sudo apt-get update -y --fix-broken`
