### ISSUE TITLE
[Request]  REST Api Endpoints & Documentation

### ISSUE THREAD

**Issue by inktomi** [reef-pi/reef-pi#1230]
I would like to build an open source mobile app that can serve as a front end, replacing the functionality found on the website. 

In order to do so, it would be great to have, or to document, the endpoints that can be used to power a front end like this. It would be up to users to expose their Reef Pi publically - and I wouldn't be planning on providing any information on doing that as I think it's somewhat risky - but even internally at home on wifi it would be nice to have a mobile app. 

Could this be something that's added? 

Maybe we could use Swagger or some similar system to document the endpoints, as then the model objects and api services could even be autogenerated off the schema. It would also allow for a series of tests on the reefpi build side to ensure that the schema matches reality and doesn't change over time without a corresponding change in docs.

**Comment by Ranthalion** [comment]
Hi.  We added OpenAPI/Swagger documentation in https://github.com/reef-pi/reef-pi/pull/1148.  
You can view the swagger doc using redoc online at 
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/reef-pi/reef-pi/master/swagger.json

**Comment by ranjib** [comment]
We'll be adding the apidocs to debian packages as well. Any reef-pi user will be able to see the relevant api docs straight from their controller under /assets/api.html

**Comment by inktomi** [comment]
Thank you! We can consider this solved. Sorry for the delay in responding.
