### ISSUE TITLE
[Request] pH Settings

### ISSUE THREAD

**Issue by Kulawka2** [reef-pi/reef-pi#1237]
Is it possible to add in pH tab "Off" function in settings when setup treshold for example when you setting up lower or upper treshold, because for now its only turn equipment on if you reach upper or lower treshold , it will be fantastic to have chance to turn off something if reach limit. Sorry for my english, hope everything is understable. Thank you

**Comment by ranjib** [comment]
Im not sure i understand. Do you mean "disable" the control mechanism completely? "One shot " controllers will disable them selves once they reach their desired range. And user have to manually start them or trigger them via macro. 

Another way of doing this will be to define multiple controller using the same probe, and use one of them as monitory only to trigger a macro which in turn enable/disable the other ph controller.

**Comment by DevinTesla** [comment]
I think He's asking to have a way to flip the behaviour 
so as is  if you go above the upper limit you turn *device* on and if you go back down it turns back on
I think he wants to turn somting off when he goes over the high limt or below the low limit 
( note I do this but I use a high limit for a low limit you can also just use the reverse the equipment in the config)

**Comment by ranjib** [comment]
Ad @DevinTesla  mentioned, It is possible to configure outlets in *reverse* mode , thus on will actually switch off equipment while off will switch on the equipment. Im closing this since i am not taking any work items from this issue. Please feel free to reopen if you feel otherwise.
