### ISSUE TITLE
Backup-restore reef-pi database

### ISSUE THREAD

**Issue by JimmyKer** [reef-pi/reef-pi#1247]
It would be nice if we could **download** the reef-pi database from the configuration (admin tab) for backup purpose (for example after config changes)

Even better we also can **upload** a previous backup for restoring to a previous configuration.

**Comment by DevinTesla** [comment]
Very much would like

**Comment by lepetitnicolas64** [comment]
that would be a very good feature.

**Comment by gminton86** [comment]
I would love this i've had to re-enter my configuration about 10 times in the last 2 years running this reef-pi so I would love this enhancement.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1272
