### ISSUE TITLE
Lights - temporarily override profile

### ISSUE THREAD

**Issue by JimmyKer** [reef-pi/reef-pi#1248]
I would be nice if the lights profile, in may case interval, could be temporarily overruled for tank maintenance, or show off to guests 👍

**Comment by Ranthalion** [comment]
This is available as Manual/Auto mode.  Switching from Auto to Manual allows you to override a profile.
![image](https://user-images.githubusercontent.com/1632746/98390272-231d5080-2023-11eb-9951-5b5ff143a725.png)

![image](https://user-images.githubusercontent.com/1632746/98390398-4e07a480-2023-11eb-9b6e-4dea133789ac.png)

I'm closing this issue, but feel free to reopen with more details if this does not resolve this requests.
