### ISSUE TITLE
PH hysteresis

### ISSUE THREAD

**Issue by DevinTesla** [reef-pi/reef-pi#1249]
**Describe the bug**
Can't set PH control hysteresis

**To Reproduce**
1. Go to PH
2. set up a ph control (checked on Macro and Equipment)
3. Set a hysteresis value other then 0
4. Save
5.open and see hysteresis = 0
same on 3.4 and 3.5 
Hardware Robotank Delux

**Expected behavior**
a value of 1-0.1 to be saved

**Screenshots**
![Screenshot from 2020-10-11 13-46-46](https://user-images.githubusercontent.com/72705258/95686014-59ed7b80-0bc9-11eb-8c18-97d56050cb92.png)

**Desktop (please complete the following information):**
 - Device Pi3 B
 - reef-pi version [3.4 and 3.5]
 - Browser [chrome, Firefox]
 - Version [Chrome 86.0.4240.75 64 bit,Firefox 81 64 bit,]

**Comment by robotfish42** [comment]
I'm also encountering this, on a Pi 4 with the same version of reef-pi.

**Comment by gminton86** [comment]
I noticed this also.

**Comment by ranjib** [comment]
Thank you for reporting this. It was a bug in the UI code that was not passing the hysteresis value to API/Controller. Fix will be shipped in 4.0.
