### ISSUE TITLE
Can't turn off dev mode

### ISSUE THREAD

**Issue by DevinTesla** [reef-pi/reef-pi#1251]
**Describe the bug**
Turned on Dev mode to see if I could get any more info on the ph problem I had can't turn back on from the ui

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to configure
2. Click on dev mode
3. hit update 
4. reload config 
5. Go to configure dev mode is still checked and nothing work ( as true on dev mode)

**Expected behavior**
Dev mode turns off

**Desktop (please complete the following information):**

    Device Pi3 B
    reef-pi version [3.4 and 3.5]
    Browser [ Firefox]
    Version [Firefox 81 64 bit,]

I ended up removing the database file and rebuilding it.

**Comment by ranjib** [comment]
@DevinTesla i just confirmed this.  This is an UI bug. The configuration is actually being saved in the backend / database. The UI is not showing the correct state due to some bug (yet to pin point it). Controller should work as expected, otherwise. Thank you for reporting this. I'll look into it shortly

**Comment by ranjib** [comment]
@DevinTesla i spent some more time on this, it turned out this is not a reef-pi bug, at least for my case. For me, reef-pi was saving the dev_mode settings, but the reload button from UI was not working as expected. This happens sometime (i.e. reef-pi is not able to reload/reboot ), and is separate issue. After I manually reloaded devmode setting persisted as expected. Please re-open this issue if you are still facing it

**Comment by dlennox24** [comment]
This may still be a bug. While I was attempting to resolve some CORS issues (attempting to build a custom UI), I did a similar thing as Devin and then could not turn off dev mode. I attempted both reloads and reboots within the admin panel, as well as directly sending a POST request to the settings endpoint via Postman.

I was ultimately able to resolve this without blowing away and rebuilding the DB. The way I did this was the following:
1. Delete the devmode temperature sensor (not sure if this had any impact or not)
2. Turned off dev mode and triggered a reload via the UI
3. Turned off `reef-pi.service` (`systemctl stop reef-pi.service`)
4. Validate the `capabilities.dev_mode` value was `false` with the command `reef-pi db list reef-pi` (it was set to false)
5. Attempted to start the reef-pi service with `systemctl start reef-pi.service` (this appeared to not work, service came back up but dev_mode was still stuck on)
6. Reboot the Pi
7. Checked the status of `/api/settings` and `/api/capabilities` to see if they were in sync. They were not (like below)
8. Updated the settings via an HTTP POST to `/api/settings` and a reload via `/api/admin/reload` with Postman
9. Repeated steps 3 and 4, `dev_mode` was still showing `false`
10. **Restarted** the `reef-pi.service` (`systemctl restart reef-pi.service`) 
    -  Using a restart over a stop/start may be why it started working again but that's a bit of a guess
12. It was working as normal once the service recovered, I cleared  the browser cache, and refreshed the page

I have no idea how this happened or why it relatively suddenly started working again but hopefully, if someone from a Google search finds this, the above troubleshooting steps might be reproducible.

**Specs**
- RPi 4B rev1.4, running DietPi v8.24.1
- reef-pi v6.0
- Chrome Version 120.0.6099.71 (64-bit) and FireFox 120.0.1 (64-bit)

There appears to be a mismatch in the endpoint responses when it was stuck in dev_mode, as well. Not sure if it's related, but they did align once I resolved the issue.
```
curl -b cookie.txt http://192.168.2.100/api/settings
{
    "name": "reef-pi",
    "interface": "wlan0",
    "address": "0.0.0.0:80",
    "display": false,
    "notification": true,
    "capabilities": {
        "dev_mode": false,
        "dashboard": false,
        "health_check": false,
        "equipment": false,
        "timers": false,
        "lighting": false,
        "temperature": false,
        "ato": false,
        "camera": false,
        "doser": false,
        "ph": false,
        "macro": false,
        "configuration": false,
        "journal": false
    },
    "health_check": {
        "enable": false,
        "max_memory": 500,
        "max_cpu": 2
    },
    "https": false,
    "pprof": false,
    "rpi_pwm_freq": 100,
    "prometheus": false,
    "cors": true
}
```
vs
```
curl -b cookie.txt http://192.168.2.100/api/capabilities
{
    "dev_mode": true,
    "dashboard": true,
    "health_check": true,
    "equipment": true,
    "timers": true,
    "lighting": false,
    "temperature": true,
    "ato": true,
    "camera": true,
    "doser": false,
    "ph": false,
    "macro": true,
    "configuration": true,
    "journal": false
}
```
