### ISSUE TITLE
Setup Development environment on Ubuntu 20.04 LTS - Using Windows 10 WSL 2

### ISSUE THREAD

**Issue by JimmyKer** [reef-pi/reef-pi#1254]
Hi,

I'm trying to get the development running using Ubuntu running from a Windows Subsystem for Linux.
1. Ive followed the WSL 2 guide here:
[`https://docs.microsoft.com/en-us/windows/wsl/install-win10`](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
2. I've followed the guide here:
[`https://github.com/reef-pi/reef-pi/blob/master/docs/development_environment.md`](https://github.com/reef-pi/reef-pi/blob/master/docs/development_environment.md)
What comes down to (for my own reference):
`sudo apt-get update`
`sudo apt install golang-go`
`sudo echo "export GOPATH=/Users/testuser/gospace" >> .bash_profile`
`sudo echo "export PATH=$PATH:$GOPATH/bin #to make goimports available" >> .bash_profile`
`sudo apt-get update`
`sudo apt install npm`
`sudo apt install nodejs`
`sudo chown -R testuser /Users/testuser/gospace`
`cd $GOPATH/src/github.com/reef-pi/reef-pi`
`make install`
`sudo chown -R testuser /Users/testuser/gospace`
`npm audit fix`
`make`
`make start-dev`

As you can see, the make works fine, dev mode gets started, login using curl works.
**But the web-interface is empty.**

Any ideas what I'm doing wrong?

![image](https://user-images.githubusercontent.com/24880770/97194006-ed1dd800-17a9-11eb-9d79-d78654e43841.png)

**Comment by ranjib** [comment]
did you run `make install` and `make ui` ?

**Comment by ranjib** [comment]
https://reef-pi.github.io/additional-documentation/development/

**Comment by JimmyKer** [comment]
> did you run `make install` and `make ui` ?

Nope, this did the trick, all works as expected now 👍
