### ISSUE TITLE
Can we fix the temp so it doesnt show up with any more than 2 decimal points?

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1269]
just 1 or 2 would be fine but 14 decimal points is too much.
![raspitemp](https://user-images.githubusercontent.com/22088453/98431782-6f4dac80-2086-11eb-9908-aedbe0a2ce94.JPG)

Can we round up and never display temp with more than 2 decimal points. 

Same with pH

**Comment by ranjib** [comment]
which version of reef-pi you are running?

**Comment by gminton86** [comment]
3.5

**Comment by 5ft24dave** [comment]
not sure why, but in 3.5 and now 4.0 I haven't had display of more than 2 decimal places.

**Comment by 5ft24dave** [comment]
nevermind.  now that I did a calibrate on the temp, its constantly showing 14 decimal places...

**Comment by prsws** [comment]
I submitted a PR a few days ago (which was accepted and merged into master) that rounds the temp and pH values to 2 decimals. Ranjib improved on that with the min/max and color changes to the temp charts. Please wait until the next official release to get it but if you're in a hurry you can build your own binary from source.

**Comment by ranjib** [comment]
this is fixed in 4.2. Feel free to reopen if its still an issue
