### ISSUE TITLE
Reef Pi not working right

### ISSUE THREAD

**Issue by Mosterhout** [reef-pi/reef-pi#1271]
Not sure what is going on, i have a new install of 2020-08-20-raspios-buster-armhf-lite, and I installed reef Pi 3.5, on Raspberry Pi 4 Model B Rev 1.1 
Day1 On initial setup everything worked as it should, the only thing i have right now is 1 dosing pump that i use as a timed ATO everyday. I setup a macro to turn the pump on wait 100 seconds then turn the pump off.
Then i setup a timer to run the macro everyday at 13:00:00 everything worked great the first day.

Day 2 Timer never triggers the daily ATO macro, then i wanted to setup the email alerts so i would know if it triggered,  I setup a new gmail account and setup the reef-pi email section and sent a test email all seemed ok. I test the on/off of the pump in the equipment tab and it turns the pump on and off fine. Manually triggerd the macro and it works as it should, thought maybe it was some config fluke, Rebooted the PI

Day 3 Timer missed again today so i created a new timer and set it 5 mins later and it still didn't trigger.
Email is now broken also, Dashbaord isn't working and as i switch pages i am getting 404 errors.
Looking at the systemctl status i am seeing 

Nov 10 13:17:30 SaltySeaDogs reef-pi[9594]: 2020/11/10 13:17:30 API Request:'   GET /api/me' from: xx.xx.xx.10:49742 (I removed the first 3 octests)
but my pi IP ends in 80 not 10. i do have a live nod at 10 but that is a google home speaker.

is there some sort of built in web server that has the wrong IP?

My address is 0.0.0.0:80 in the console

**Comment by Mosterhout** [comment]
known bug for reef pi 3.5

**Comment by gminton86** [comment]
Why do you use a timer and macro for ATO? there is a whole tab dedicated to ATO.

**Comment by gminton86** [comment]
I use the ATO tab and a float switch but you can use any input to trigger the ATO

**Comment by Mosterhout** [comment]
At this time i only have a pump no input devices, i tested the ATO funtion with a jumpered GPIO pin and works as it should. Just dont have a water level sensor yet

On November 11, 2020 8:21:18 AM CST, gminton86 <notifications@github.com> wrote:
>I use the ATO tab and a float switch but you can use any input to
>trigger the ATO
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/reef-pi/reef-pi/issues/1271#issuecomment-725449992

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Mosterhout** [comment]
Do you have anything setup to have a "feed" or "clean" button that  watches a gpio pin for input and when triggered will stop all outlets for 10mins for feeding and either 30mins or until i push the button again for cleaning, this could be accomplished by having a button that clicks on/off also

On November 11, 2020 12:16:31 PM CST, Mike Moreno-Osterhout <mosterhout85@gmail.com> wrote:
>At this time i only have a pump no input devices, i tested the ATO
>funtion with a jumpered GPIO pin and works as it should. Just dont have
>a water level sensor yet
>
>On November 11, 2020 8:21:18 AM CST, gminton86
><notifications@github.com> wrote:
>>I use the ATO tab and a float switch but you can use any input to
>>trigger the ATO
>>
>>
>>-- 
>>You are receiving this because you modified the open/close state.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/reef-pi/reef-pi/issues/1271#issuecomment-725449992
>
>-- 
>Sent from my Android device with K-9 Mail. Please excuse my brevity.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
