### ISSUE TITLE
Tasmota driver [Request] 

### ISSUE THREAD

**Issue by stvnmbr1** [reef-pi/reef-pi#1273]
**Is your feature request related to a problem? Please describe.**
I already talked about tasmota / esp components, controlled by reef-pi. They act similar to the HS plugs and can use HTTP requests. MQTT could be used to for more security (mqtt server with encryption like mosquito)

http://<ip>/cm?cmnd=Power%20TOGGLE
http://<ip>/cm?cmnd=Power%20On
http://<ip>/cm?cmnd=Power%20off
http://<ip>/cm?user=admin&password=joker&cmnd=Power%20Toggle

**Describe the solution you'd like**
adding a driver for tasmota

**Describe alternatives you've considered**
I started a fork to figure out how the HS drivers work, and added some test data json responses from tasmota for reference.
https://github.com/stvnmbr1/drivers/tree/master/tasmota

i could use some direction on what needs to be changed. I know the json attributes need to be described, but not sure how the commands parts work, as they only control one component.

**Additional context**
https://tasmota.github.io/docs/Commands/

i'm waiting for my components to arrive like temp sens and tds to get more specific

**Comment by ranjib** [comment]
@stvnmbr1 i like this idea. I think it will be awesome to have a tasmota driver. We need to figure out these:
 - What all feature this driver will have? Outlet? Inlet? PWM? Analog Input .. any one of these or multiple or all.
 - Test json payload for all the features we want to implement
- Any docs on API mechanism (http, json, auth scheme etc)

Thank you for filing this. We'll work on this post 4.0 release (this thanksgiving tentatively)

**Comment by stvnmbr1** [comment]
I use a wemos D1 mini with tasmota. ESPeasy has the same approach with almost the same http and mqtt, i use this for my other diy led. Could be a next-up

This setup would give you 5 channel led pwm control (needed in my case), 1 floater switch with relay control and 1 ds18b20 with relay control. led pwms can be swapped with pca9685 for extra pwm outputs if needed (still need to test it out but i have a spare laying around).
I think this covers the basics of a standard reeftank. ato, temp control and light control. I do need to test if everything works, but pwm control and relais does.

I've added some testdata jsons, looks similar approach as the HS plugs. all info can be gathered by reading json responses. "http://tasmotaip/cm?cmnd=Status 0" or relevant numbers to get specific info.
Relay/switches can be controlled by http request "http://tasmotaip/cm?cmnd=Power1 On-Off" or "http://tasmotaip/cm?cmnd=Power1 0-1"
Every pwm output has a corresponding POWER which can be used to toggle pwm(lights) on or off
PWM can be controlled by http request "http://tasmotaip/cm?cmnd=Channel1 0-100"

This looks very similar to controlling the relay in the HS plugs if i read the scripts correctly. HS300 has mutiple plug but i copied the HS100 folder;


https://github.com/stvnmbr1/drivers/tree/master/tasmota/testdata
holds testdata json responses

https://tasmota.github.io/docs/Commands/
shows all commands.

something tricky to keep in mind is, if the setup changes, eg one less relais (POWERX), all channels for pwm (CHANNELX)  will drop incremental as it counts POWER (switches and such) first and pwm after that. This is the same for MQTT

POWER1
POWER2
POWER3
CHANNEL3

POWER1
POWER2
CHANNEL2

Would you approach this via mqtt or http? i know hassio and such have discovery with SetOption19 on tasmota
http can have a password but it's included in plain text in the request for tasmota and espeasy. mqtt would be a more secure approach but this also add an extra layer where something can go wrong. I noticed the delivery confirmation didn't always work when adding prio to mqtt

**Comment by ranjib** [comment]
Closing this since we have it in master. Create new issue for any additional feature request. Much appreciated @hectorespert
