### ISSUE TITLE
adafruit.io no data in feeds

### ISSUE THREAD

**Issue by virtualGain** [reef-pi/reef-pi#1275]
**Describe the bug**
I am able to connect to my adafruit.io account and it creates the feeds I would expec to see. However the only feed that has data in it is CPU load. The rest of the feeds are getting null data and nothing is showing up in the graphs or history. I even tried this with a premium account.

**To Reproduce**
1. Go to 'adafruit.io'
2. Click on 'feeds'
3. Note that only the cpu load and memory usage feed are checking in on consistent basis and no other feeds have any data at all.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Device [e.g. Pi3] Pi 3b
 - reef-pi version : 3.5
 - Browser [e.g. chrome, safari] All

**Additional context**

**Comment by dmolavi** [comment]
Make sure your feed prefix doesn't have an underscore,  that fixed it for me

**Comment by virtualGain** [comment]
I did not have a prefix set. I tried setting one and it did not resolve unfortunately.

**Comment by ranjib** [comment]
can you provide some more details for an exact missing metric. Sometime if the name contains space that can lead to similar issues. reef-pi should log when this happens

**Comment by virtualGain** [comment]
I just resolved this by changing the names of my ato, temperature gauges, etc to not include spaces. I am still getting blank readings for a few things but i am not even sure what they would read if they could to be honest. Like what would the "reading" metric be for ATO for example? Also thanks for your help!

![image](https://user-images.githubusercontent.com/6516692/99828811-70241b00-2b29-11eb-94df-bfaf133a62c1.png)

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1291
there was a bug as well. It will be shipped in 4.0

**Comment by virtualGain** [comment]
Cool thanks for the help btw!
