### ISSUE TITLE
ESPeasy driver [Request] 

### ISSUE THREAD

**Issue by stvnmbr1** [reef-pi/reef-pi#1283]
**Is your feature request related to a problem? Please describe.**
similar usage to the tasmota driver, it could be handy to include this one as well. It has a similar approach to tasmota

**Describe the solution you'd like**
same-ish driver, but an other http command

http://espeasyip/control?cmd=<command>
MQTT subscribe template/cmd 

GPIO,gpio,value                             http://espeasyip/control?cmd=GPIO,12,0 or GPIO,0...16,0...1
PWM,GPIO,state,duration          http://espeasyip/control?cmd=PWM,13,500,optional or PWM,0...15,0...1023

**Additional context**

commands
https://www.letscontrolit.com/wiki/index.php/ESPEasy_Command_Reference

GPIO (mainly used)
https://www.letscontrolit.com/wiki/index.php?title=GPIO

**Comment by ranjib** [comment]
closing this due to incactivity. feel free to reopen if you want to discuss this
