### ISSUE TITLE
Invalid metric name causes reef-pi.service to panic after enabling Prometheus when a sensor name begin with a digit

### ISSUE THREAD

**Issue by chrisleavoy** [reef-pi/reef-pi#1318]
**Describe the bug**
Invalid metric name causes reef-pi.service to panic after enabling Prometheus when a sensor name begin with a digit.

**To Reproduce**
1. Name temp sensor beginning with a digit
2. Enable Prometheus
3. Restart

**Expected behavior**
Expect reef-pi to not panic.

**Logs**

Dec 23 20:51:58 reef systemd[1]: reef-pi.service: Scheduled restart job, restart counter is at 10.
Dec 23 20:51:58 reef systemd[1]: Stopped raspberry pi based reef tank controller.
Dec 23 20:51:58 reef systemd[1]: Started raspberry pi based reef tank controller.
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 driver-subsystem: registering driver id: rpi Name: Raspberry Pi
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 driver-subsystem: registering driver id: 1 Name: pH
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 driver-subsystem: registering driver id: 2 Name: Extra Ports
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Successfully started subsystem: temperature
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Successfully started subsystem: lightings
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Successfully started subsystem: phprobes
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Successfully started subsystem: macro
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 INFO: equipment subsystem: Finished syncing all equipment
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Successfully started subsystem: equipment
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Successfully started subsystem: ato
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Successfully started subsystem: timers
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Successfully started subsystem: journal
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Successfully started subsystem: system
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Successfully started subsystem: doser
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 reef-pi is up and running
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Starting http server at: 0.0.0.0:80
Dec 23 20:51:58 reef reef-pi[1230]: Methods: [GET]
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 API Doc path: /api/settings
Dec 23 20:51:58 reef reef-pi[1230]: 2020/12/23 20:51:58 Starting health checker
Dec 23 20:52:08 reef reef-pi[1230]: 2020/12/23 20:52:08 Reading temperature from device: 28-01193838a8b7
Dec 23 20:52:08 reef reef-pi[1230]: 2020/12/23 20:52:08 Reading temperature from device: 28-01193a28443d
Dec 23 20:52:08 reef reef-pi[1230]: 2020/12/23 20:52:08 ph sub-system: ERROR: Failed to read probe: ph . Error: write /dev/i2c-1: remote I/O error
Dec 23 20:52:08 reef reef-pi[1230]: 2020/12/23 20:52:08 ato-subsystem: sensor: 4 state: 0
Dec 23 20:52:08 reef reef-pi[1230]: 2020/12/23 20:52:08 ato-subsystem: sensor: 4  usage: 0
Dec 23 20:52:08 reef reef-pi[1230]: 2020/12/23 20:52:08 ato-subsystem: sensor: 5 state: 0
Dec 23 20:52:08 reef reef-pi[1230]: 2020/12/23 20:52:08 ato-subsystem: sensor: 5  usage: 0
Dec 23 20:52:08 reef reef-pi[1230]: 2020/12/23 20:52:08 ato-subsystem: sensor: 6 state: 0
Dec 23 20:52:08 reef reef-pi[1230]: 2020/12/23 20:52:08 ato-subsystem: sensor: 6  usage: 0
Dec 23 20:52:09 reef reef-pi[1230]: 2020/12/23 20:52:09 temperature sub-system:  sensor 2 value: 80.49
Dec 23 20:52:09 reef reef-pi[1230]: panic: descriptor Desc{fqName: "2_reading", help: "Module:2 Item:reading", constLabels: {}, variableLabels: []} is invalid: "2_reading" is not a valid metric name
Dec 23 20:52:09 reef reef-pi[1230]: goroutine 34 [running]:
Dec 23 20:52:09 reef reef-pi[1230]: github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x25ab340, 0x25d8220, 0x1, 0x1)
Dec 23 20:52:09 reef reef-pi[1230]: #011/home/ranjib/gocode/pkg/mod/github.com/prometheus/client_golang@v1.8.0/prometheus/registry.go:401 +0x80
Dec 23 20:52:09 reef reef-pi[1230]: github.com/prometheus/client_golang/prometheus/promauto.Factory.NewGauge(0x7a4ed0, 0x25ab340, 0x0, 0x0, 0x0, 0x0, 0x2770560, 0x9, 0x25dc3e0, 0x15, ...)
Dec 23 20:52:09 reef reef-pi[1230]: #011/home/ranjib/gocode/pkg/mod/github.com/prometheus/client_golang@v1.8.0/prometheus/promauto/auto.go:297 +0xc0
Dec 23 20:52:09 reef reef-pi[1230]: github.com/prometheus/client_golang/prometheus/promauto.NewGauge(...)
Dec 23 20:52:09 reef reef-pi[1230]: #011/home/ranjib/gocode/pkg/mod/github.com/prometheus/client_golang@v1.8.0/prometheus/promauto/auto.go:191
Dec 23 20:52:09 reef reef-pi[1230]: github.com/reef-pi/reef-pi/controller/telemetry.(*telemetry).EmitMetric(0x255edc0, 0xba7f12, 0x1, 0x6ac73a, 0x7, 0x28f5c28f, 0x40541f5c)
Dec 23 20:52:09 reef reef-pi[1230]: #011/home/ranjib/gocode/src/github.com/reef-pi/reef-pi/controller/telemetry/telemetry.go:194 +0x528
Dec 23 20:52:09 reef reef-pi[1230]: github.com/reef-pi/reef-pi/controller/modules/temperature.(*Controller).Check(0x24ac720, 0x24da600, 0x2, 0x0, 0x1, 0x1472c)
Dec 23 20:52:09 reef reef-pi[1230]: #011/home/ranjib/gocode/src/github.com/reef-pi/reef-pi/controller/modules/temperature/control.go:33 +0x430
Dec 23 20:52:09 reef reef-pi[1230]: github.com/reef-pi/reef-pi/controller/modules/temperature.(*Controller).Run(0x24ac720, 0x24da600, 0x26be6c0, 0x0, 0x1)
Dec 23 20:52:09 reef reef-pi[1230]: #011/home/ranjib/gocode/src/github.com/reef-pi/reef-pi/controller/modules/temperature/tc.go:204 +0x130
Dec 23 20:52:09 reef reef-pi[1230]: created by github.com/reef-pi/reef-pi/controller/modules/temperature.(*Controller).Start
Dec 23 20:52:09 reef reef-pi[1230]: #011/home/ranjib/gocode/src/github.com/reef-pi/reef-pi/controller/modules/temperature/controller.go:91 +0x1c4
Dec 23 20:52:09 reef systemd[1]: reef-pi.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 23 20:52:09 reef systemd[1]: reef-pi.service: Failed with result 'exit-code'.

**Comment by chrisleavoy** [comment]
work around to disable Prometheus without wiping the database:

```shell
sudo cp /var/lib/reef-pi/reef-pi.db ~/reef-pi-backup.db
sudo systemctl stop reef-pi
sudo reef-pi db show reef-pi settings > reef-pi-settings.json
jq '.prometheus=false' reef-pi-settings.json | sudo reef-pi db update reef-pi settings
sudo systemctl start reef-pi
```

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1360
thank you for reporting this. Fix will be released in next release
