### ISSUE TITLE
Dev support - Windows - bad function signature

### ISSUE THREAD

**Issue by Paul-Baertlein** [reef-pi/reef-pi#1319]
**Describe the bug**
Bad Function signature 

**To Reproduce**
Compile issue in windows.

1. On windows use make.   - Generates errors in api.go lines 204 and 231.
You can see in systemd_windows.go the signature is SystemdExecute(command string, _ bool), where in api.go it is passing 3 parameters.

**Expected behavior**
Should build

**Desktop (please complete the following information):**
 - Windows
 - reef-pi version  4.0-34-ge8d7a78
 - Chrome
 - Version 87.0.4280.88

**Additional context**
Easy enough to fix by changing the signature in the systemd_windows.go file.   Not like it does anything useful.  Not sure what the procedure is for pull requests or I would have made one.

I did get it up and running in windows.

**Comment by ranjib** [comment]
We use the bug label for reef-pi software feature related bug. This is related to developer experience and is not encountered by normal reef-pi users. Hence relabeling this to devex. 
We have to add build tags with to exclude this file for windows and incorporate a windows specific no op file.

**Comment by ranjib** [comment]
@Paul-Baertlein im closing this since im not using windows to build and hence will not be able to maintain the support unless someone is actively developing using windows. Ok for any PR with signature fixes.
