### ISSUE TITLE
Reef-pi has gone unreliable

### ISSUE THREAD

**Issue by usernamestaken** [reef-pi/reef-pi#1322]
I have an issue with my reef-pi, in that it has gone completely unreliable. It will work for a week or a few weeks flawlessly, and then all of a sudden it does something terrible, like freeze during a timer or fail to operate the ATO. Last night it froze during an auto water change sequence on the "drain" function and emptied about 20 gallons of water until the pumps kicked off for self-protection. What it did was during execution of a macro that was started by a timer, it just kind of stopped in the middle of the sequence. 

I don't know why it is freezing like this, but I have to unplug it and plug it back in fairly often. I have a screen that is attached to it permanently, could this be the issue? Or is it possible it's some sort of bug in the programming?

**Comment by ranjib** [comment]
moved from docs/website repo to code repo

**Comment by ranjib** [comment]
@usernamestaken are you still interested in addressing this?

**Comment by usernamestaken** [comment]
I figured out that it had to do with a power issue, trying to run a screen off the same power supply. Once I removed it the problem went away.

**Comment by ranjib** [comment]
thank you for getting back, Im closing this issue
