### ISSUE TITLE
Shorter intervals for ato usage

### ISSUE THREAD

**Issue by MikeBurkePhD** [reef-pi/reef-pi#1337]
First, thanks so much for developing and maintaining Reef-Pi.

Currently "ato_usage" tracks the use of an ATO pump within 1-hour intervals. For example, Reef-Pi tracks the total number of seconds that the ATO was used from 10:00 am - 11:00am. The issue with this approach is the user can never know exactly when the ATO was triggered or how many times within that hour. It could have been triggered 10 times or one time and Reef-Pi would just show the total number of seconds. 

This is generally fine, but an enhancement would be if the user could select shorter intervals for tracking "ato_usage" to more finely examine when and for how long the ATO is being used. This would allow the user to potentially discover issues with the ATO like a snail bumping against the float switch or better understand variation of when the ATO is being used.

**Comment by ranjib** [comment]
reef-pi's built in dashboard is very minimal, and the ato chart right now only shows hourly usage. In my experience, this has been enough to understand the ato usage pattern.
<img width="1413" alt="Screen Shot 2021-01-02 at 10 50 53 PM" src="https://user-images.githubusercontent.com/316306/103473491-192b7b80-4d4e-11eb-9501-d585067f38b1.png">
But we emit metrics over Prometheus and MQTT that can be used for any arbitrary charting. This includes what you asked and much more. Here is an example of grafana chart that shows the highest granularity, 15s ato usage time
<img width="1406" alt="Screen Shot 2021-01-02 at 10 49 57 PM" src="https://user-images.githubusercontent.com/316306/103473453-b20dc700-4d4d-11eb-8e81-8c3de8ffa70f.png"> . 

We are planning to do some improvement on the UI/Dashboard, and an enhanced ATO chart with such details will be useful. But I am also thinking if we should recommend Prometheus/grafana installation (and have code to automate that) instead for the advance use cases (with pi 4) and keep the built in dashboard bare bone. This will also keep resource usage low.

**Comment by MikeBurkePhD** [comment]
Thanks @ranjib. I did setup Prometheus and Grafana and it is great (dashboard pic attached).

The issue I was having was that my ATO pump runs for about 4 seconds at a time, so if Prometheus wasn't getting the metrics while the ATO was running, it wouldn't catch my ATO pump use. I could set Prometheus to get the metrics at 2 second intervals, but this seems like overkill. This is an issue with my particular setup though.

My read of the Reef-Pi community is that Prometheus and Grafana are not widely understood and adopted. This is unfortunate because they are such a major enhancement to Reef-Pi. Maybe I can work on a how-to guide on setting them up on an rpi. The other benefit I have found is that you can use Real VNC or Teamviewer to remotely connect to the rpi running Grafana so I can access the dashboards even when outside the network. This is another awesome enhancement that I think folks don't totally understand.

So I agree that keeping the native Reef-Pi dashboard minimal to save resources and complexity, however, it would be great to say that this is being done because Prometheus and Grafana are available and here is how to set them up. 

![grafana_dashboard](https://user-images.githubusercontent.com/39815108/104039459-67080f80-51a4-11eb-9b35-038565668076.png)

**Comment by ranjib** [comment]
@MikeBurkePhD thank you for sharing the details and apologies for getting back late. I would love to see any documentation on prom/grafana + reef-pi.  Grafana and prometheus is very popular in software industry, but not so much beyond that. reef community are unlikely to be aware of it by n large. We can change that for tech focused folks by advocating and documenting it.

All metric systems (such as prometheus, telegraph  or stated) will buffer it for 10s or so. and none of them are real time. It will. not be real time. 
Im closing this as I don't have any action item to take from . Please feel free to reopen if you would like to discuss further
