### ISSUE TITLE
Translation: Fill up spanish translation

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#1345]
https://github.com/reef-pi/reef-pi/blob/master/front-end/assets/translations/es.csv

@sabbene @hectorespert you think you can help us with this?

**Comment by hectorespert** [comment]
Yes, I can help. Could you assign me this issue?

**Comment by hectorespert** [comment]
Some words translated: https://github.com/reef-pi/reef-pi/pull/1349
