### ISSUE TITLE
Disabling Ph Sensor w/ Android Chrome Fails

### ISSUE THREAD

**Issue by fuzzewuzze** [reef-pi/reef-pi#1347]
Using a Samsung Galaxy A5 w/ Chrome.
Edit PH Probe item, change Ph Status to Disable, press Save.
Your returned with this page and the probe is not disabled.

[Picture](https://www.dropbox.com/s/6n7zalnavs74r2p/2021-01-11%2021.03.14.jpg)

**Comment by ranjib** [comment]
hi. this was fixed in master recently, will be released as part of 4.3
