### ISSUE TITLE
strConv Error spam while calibrating PH probe.

### ISSUE THREAD

**Issue by fuzzewuzze** [reef-pi/reef-pi#1350]
On desktop chrome when calibrating my PH probe and the calibration screen is up, i repeatedly see these errors spammed in the background.  I dont think they are affecting the calibration but are confusing.  This is using 4.0, and happened with 2 different probes.  Using Robotank.

![image](https://user-images.githubusercontent.com/685435/104407330-33b3e080-5516-11eb-924b-604ec42eb838.png)

**Comment by ranjib** [comment]
@fuzzewuzze which ph probe you are using?
sorry for getting back to this late. I am using ezo as well as the opensource board and have not experienced this yet,

**Comment by ranjib** [comment]
is this probe using ezo circuit? im not able to reproduce this. does atlas scientific python libraries work?

**Comment by ranjib** [comment]
hi, reef-pi only support ezo protocol right now. I am able to use the ph setup with 5.2 build. Feel free to reopen if you still hitting this issue. We have another ticket on this, im closing this ,we;ll track it there
