### ISSUE TITLE
Ato to target dosing pump

### ISSUE THREAD

**Issue by mtorzews** [reef-pi/reef-pi#1357]
Allow ato to turn on a dosing pump. Or allow equipment to use pwm and have an power setting. I am using a dosing pump for rodi top off water. I want to run this pump at 75%.

**Comment by d-portero** [comment]
you can do this by adding an outlet and using the pin that controls the dosing pump as the outlet. This is how I control a dosing pump using the ATO system.

**Comment by ranjib** [comment]
I use a 12V dosing pump as ato, but I power it using a dedicated 12C adapter, which in turn is modeled as equipment.

**Comment by ranjib** [comment]
@mtorzews im closing this since  i am not taking any work items from this issue. please feel free to reopen if you want to discuss this further
