### ISSUE TITLE
Chart colors do not change

### ISSUE THREAD

**Issue by 5ft24dave** [reef-pi/reef-pi#1359]
On release 61, when it to configure, tank temperature, set chart color to blue, changed high and low limits of chart, saved, reloaded, and limits are changed, but the color is not.  I have tried changing it multiple times to multiple different colors and it stays the default green.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1363
thank you for reporting this, fixed. will be released in next release
