### ISSUE TITLE
Temp Chiller Hysteresis °C/°F

### ISSUE THREAD

**Issue by Bachschmied** [reef-pi/reef-pi#1367]
After upgrading from 4.0 to 4.1 the chiller cool down 0.55°C on a hysteresis of 1°C so it seems it´s a problem of °C/°F

**Comment by ranjib** [comment]
@Bachschmied sorry for your trouble. and aplogiies for the late response. Ill verify this and get back to you.

**Comment by ranjib** [comment]
i was not able reproduce this with 4.3. Please let me know if you are still encountering this
