### ISSUE TITLE
suggestions ore reef 

### ISSUE THREAD

**Issue by loksiklubos** [reef-pi/reef-pi#1371]
-Instead of timers, show the position of the open / closed swimmer,
-Add the clock and date to the worksheet
-error when entering 1-7 days in weeks in timers
-Change wifi networks via website in setup
-creation of buroks for lighting
-function for factory setting reef pi, to delete all stored data in the reef pi
-warning for sound warnings inspiration robotank

**Comment by ranjib** [comment]
Well, there are quiet a few things in this ticket. We have to break it down them into individual pieces, and triage them independently (bug, feature etc) before picking up the development work,

**Comment by loksiklubos** [comment]
I would welcome to choose other DC ports than PWM in dosing. Since I have 8x LED lighting connected to the pwm, it does not leave me room for dosing pumps instead. It would be nice if the pumps stayed in the dosing group

**Comment by ranjib** [comment]
@loksiklubos you can use the standard timer module with an equipment to switch on/off dc power . Im closing this since theres no itemized work i am taking from this. Please feel free to reopen if you want to discuss further
