### ISSUE TITLE
Can't call API from browser due to CORS

### ISSUE THREAD

**Issue by cmjacques** [reef-pi/reef-pi#1373]
Hi there,

I've created a simple Angular app and am trying to make API requests from the browser. Unfortunately these fail because of CORS ([Cross-Origin Resource Sharing](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)).

I know I could proxy the browser requests to a server/backend and make the API calls from there however I would much rather make them directly.

Would it be possible/feasible to remove CORS from the API? Or maybe it's possible to disable CORS at the web server level?

Thank you for all your hard work on reef-pi!

**Comment by zekth** [comment]
You can't disable CORS but the server needs to return the proper headers for this:
```
Access-Control-Allow-Origin:
Access-Control-Allow-Methods:
Access-Control-Allow-Headers:
```

**Comment by ranjib** [comment]
We'll add a feature, enable CORS for this.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1376

**Comment by cmjacques** [comment]
Thanks very much @ranjib - appreciate it!
