### ISSUE TITLE
Unable to calibrate ph probe V3.5

### ISSUE THREAD

**Issue by chrispo1** [reef-pi/reef-pi#1387]
Unable to calibrate ph probe, calibrate button disabled.

Driver: ph-ezo

**Comment by gminton86** [comment]
You have to disable the probe before you can calibrate it.

**Comment by ranjib** [comment]
@chrispo1 is this still an issue? Have you tried calibration after disabling the probe? Please close this issue if its resolved,

**Comment by chrispo1** [comment]
Totally my bad.
