### ISSUE TITLE
My ph on dashboard keeps saying something went wrong?

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#1391]
![321CFA7E-833B-407E-B4E7-EAF9F7C9991F](https://user-images.githubusercontent.com/22088453/107156400-16730600-694c-11eb-8c60-d793ac9c49ab.jpeg)

**Comment by ranjib** [comment]
What device you are using? Are you experiencing this across all devices, or specific ones. We have seen this happen on few specific devices (older android specifically) or when the chart involves missing sensor (still its a software bug). Is this the equipment chart that's breaking?

**Comment by Cylus7** [comment]
I find that this happens on an iPhone 12 when opening the screen in portrait mode (landscape mode makes it work fine)

**Comment by gminton86** [comment]
This is in Firefox on my desktop. And it finally went away and has been working fine but I see it randomly.

**Comment by ranjib** [comment]
hmm.. i dont know how to address this. we can try reproducing it, but this will be hard. we also know some responsive UI issues that keep popping up in mobile devices. Im thinking through a better strategy to address this holistically

**Comment by epicfatigue** [comment]
Same issue here, Google Chrome on an android oppo A52, works in landscape

**Comment by ranjib** [comment]
https://github.com/recharts/recharts/issues/2385

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1520
