### ISSUE TITLE
reef pi problem with web

### ISSUE THREAD

**Issue by ruddii** [reef-pi/reef-pi#1392]
help me today did not load my website for cliff pi. I tried to reinstall everything without change. I am disappointed

**Comment by loksiklubos** [comment]
After all, I'm not the only one with this mistake. I have the same problem. It helps me when I remove the sd card via disk part, install rasbian and then reefpi and it works for me again. I don't get it because raspbian with graphics software works fine

**Comment by ranjib** [comment]
Do you see any errors in the log?
https://reef-pi.github.io/guides/troubleshooting/

**Comment by ranjib** [comment]
This does not look like a bug, but more like a troubleshooting or help request. We use the github repository for the code development/issues. Use reef2reef or Facebook group for help.
