### ISSUE TITLE
Kaza HS303 no longer seems to work with reef-pi

### ISSUE THREAD

**Issue by indymx** [reef-pi/reef-pi#1393]
It appears that TPLink may have removed API access to the HS303 smart power strip.

I get this error when trying to access is thru the reefpi GUI..

{"error":"Failed to update. Error: can't update 18 - can't get output pin"} | HTTP 500

I have the following version::
  "sw_ver": "1.0.10 Build 200828 Rel.162602",
  "hw_ver": "1.0",
  "model": "KP303(US)",

Version: 4.1-11-g2f5dd6e2
Website: http://reef-pi.com
Github: https://github.com/reef-pi/reef-pi
Copyright © 2021 Ranjib Dey
Status
Current time: Sun Feb 14 15:24:05
Uptime: 4 days ago
IP: 10.167.15.10

EDIT ***** I have a 4.1 build that is working ok, may not be a Kaza issue at all . 

This is something I dug up with a quick google search:

https://www.reddit.com/r/TPLinkKasa/comments/k26v9l/psa_tp_link_is_shutting_down_local_api_access/

**Comment by ranjib** [comment]
So.. is this still relevant? If not, please close this issue

**Comment by indymx** [comment]
Well, it would seem that something has changed since the 4.1 release to break the Kaza HS300 driver. Until that's fixed, yes, it would seem to be relevant

**Comment by ranjib** [comment]
@indymx is it still broken? I am thinking if i should investigate this or close this ticket.

**Comment by indymx** [comment]
I'll do a new build tomorrow and test.

**Comment by indymx** [comment]
Finally got a good build, will let you know if it continues to have an
issue. So far I'm not seeing the issue that I was having.

**Comment by indymx** [comment]
this issue seems to be resolved with the current build.
