### ISSUE TITLE
Merges to master since last release broke dosing

### ISSUE THREAD

**Issue by prsws** [reef-pi/reef-pi#1397]
Hi:

I've been working on UI changes and recently for the first time activated the Dosing module. I noticed that neither the calibration feature works (it doesn't even display the modal) and also the timed dose fires properly but doesn't last through the specified duration; in my case, it turns off the dosing pump immediately after turning it on so only a single drop is delivered.

Looking at the current master branch source I noticed that changes were made about 25 days ago as compared to the master branch of the last release (4.1) back in January. It seems that the official 4.1 release is ok. My question is, has something been broken since then? Please let us know.

Thanks,

José

**Comment by ranjib** [comment]
@prsws i suspect this change that i made: https://github.com/reef-pi/reef-pi/pull/1388/files#diff-277ad4a07818cc365354fe1ebe40ac359839c64f1cfbc786e6303a9b174cba30L54

**Comment by prsws** [comment]
Hello:

I suspected as much and reverted the changes in my copy. This resulted in the calibration modal working again, but the duration is still too short. The React code seems fine but I don't understand the Go code fully yet. Thank you.

**Comment by prsws** [comment]
Hello:

I just submitted PR https://github.com/reef-pi/reef-pi/pull/1411 that reverts the code changes and solves the issue. Please check it out, thanks.

**Comment by ranjib** [comment]
fixed through this: https://github.com/reef-pi/reef-pi/pull/1525
