### ISSUE TITLE
Temperature reading accuracy suddenly reduced

### ISSUE THREAD

**Issue by robotfishe** [reef-pi/reef-pi#1412]
A couple of weeks ago, my reef-pi dashboard, as well as the prometheus output at x/metrics, has reduced the temperature accuracy to 0.5 degree increments. Where before it would read two decimal places at all times, now I only get 25, 25.5, or 26 degrees C.

Around the time this happened I made some changes to the prometheus and grafana setups I have running on a separate machine to display data from reef-pi, but I made no changes within reef-pi itself (at least, as far as I'm aware).

I've tried updating to the latest reef-pi 4.1 and rebooting the pi - no change.

You can see in the historical graph that it's having a real impact on my tank's temperature stability because the system can't react to temperature changes smaller than half a degree now: https://i.imgur.com/1Zah1md.png

**Comment by robotfishe** [comment]
Update: it turns out this wasn't happening within reef-pi, but rather something had somehow been changed in the device driver settings for my DS18B20s. Somehow they'd been set to a 9-bit resolution, which only gives 0.5-degree accuracy. I was able to fix the issue by opening /sys/bus/w1/devices/[sensor ID]/resolution in a text editor, and changing "9" to "12". Not sure if there's a way the bit depth setting can be integrated into reef-pi somewhere, but maybe this can be investigated?

**Comment by ranjib** [comment]
yes. I have heard about this couple of time. Im glad you got this detected. reef-pi does not set the precision bit. its likely due to some kinda system upgrade. Im closing this since there is no work item I'm taking from this. please feel free to reopen if you want to discuss more
