### ISSUE TITLE
Feature Request: Temperature using ezo-rtd

### ISSUE THREAD

**Issue by JohnRudolfLewis** [reef-pi/reef-pi#1414]
I have a whilelabs tentacle t3 with ph, temperature, and conductivity modules.

I am currently reading the temperature with my own code running along side of reef-pi, but I would like to be able to have reef-pi use the ezo-rtd either directly, or via file-analog.

**Comment by Melo1964** [comment]
hello, I have the Tentacle t3 Atlas with ph and temperature I don't have the possibility to configure everything and I manage sensors separately with Atlas Iot and the rest with reefpi

**Comment by ranjib** [comment]
We have to write a driver for the rtd sensor. I am gauging how many folks are interested in this, I am hesitatent to develop this just for a handful of folks, and I personally don't use it, hence don't know how I'll be able to test it effectively .

**Comment by CTYReef** [comment]
Respectfully request such a driver.  The rationale I use is that the quality of the DS18B20 varies wildly, depending on the source with some being unrelible out of the package.  I had one that was stable for months but then got stuck on the -1 reading reported by other users.  I did not notice it and I lost two corals that got cooked by the heater.  Also for saltwater aquarium use, even the stable ones will start rusting and leaking after several months.  The Atlas probes will provide a much more stable solution for Reef- Pi.

**Comment by ranjib** [comment]
Hey, i just checked the rtd ezo circuit documentation. We should be able to use it as it is via the ph module, since the i2c protocol is same. You have to perform calibration/i2c mode conversion outside reef-pi.
Im closing this since the software support is sufficient. We'll not implement ezo specific calibration in lieu of reef-pi's built in calibration. The ph module is a generic analog sensor module, let us know if its not usable, we can then track it as bug,

**Comment by CTYReef** [comment]
Hello,
I have not been on github for a few months and just today saw your post about using the PH ezo driver.  I have been doing that for two years but the temperature reading is only available in the PH tab (where it does work fine for displaying the temperature) but I do not see a way to use that input as the sensor source for reef pi's temperature function which is what I really want to do as it can then support the heater/cooler control function.   I may just be ignorant of the additional steps needed.   Thank you for addressing this matter.
