### ISSUE TITLE
Merges to master since last release broke pH calibration

### ISSUE THREAD

**Issue by prsws** [reef-pi/reef-pi#1417]
I received  an issue from a user that my modified versions (based on latest master branch) could not display the pH calibration dialog. I confirmed the problem and traced it to front-end/src/ph/calibration_wizard.jsx line 113. As per the latest master it reads:
`<button role='confirm' type='button' className='btn btn-primary' ref={this.props.confirm} onClick={this.handleConfirm}>`

This passes npm run standard but inhibits the dialog from displaying. Changing the "ref=" directive to:
`<button role='confirm' type='button' className='btn btn-primary' ref='confirm' onClick={this.handleConfirm}>` as it was in official release 4.1 fixes the problem but npm run standard complains: "/reef-pi/front-end/src/ph/calibration_wizard.jsx:113:78: Using string literals in ref attributes is deprecated."

I tried a couple of alternatives but was not able to fix the issue without the warning. Please look into it.

Thanks,

José

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1525/files
