### ISSUE TITLE
Boiling the fish when unreliable temp sensor

### ISSUE THREAD

**Issue by scoff3r** [reef-pi/reef-pi#1467]
My temperature sensor (or it's reading) seems to stop sometimes.. at least couple times a day.

That's ok that I can't read temperature everytime and it's even fine if heater isn't working for that period since water temperature doesn't change so quickly.

What is not ok, is that heater is running full when temperature sensor is not being able to read and it shows -1 reading. Couple of days ago my tank temperature went from 25.6 to 28 and it was already close to disaster.

Any ways to prevent heater activating when temperature sensor is not working or the reading is clearly out of range?

**Comment by gminton86** [comment]
My temp sensor is never reliable also. I wish they would change to a more reliable sensor.

**Comment by scoff3r** [comment]
I think one good option would to put two sensors but it would need some sort of IF/OR condition into interface. Like "only heat/chill water IF both sensors show too cold too hot"

**Comment by schwabix-1311** [comment]
This is the sensor DS18S20?
I found it to occasionally throw in 85 (°C) readouts. In another software I simply suppress such measurements. I don't know whether this would be the same value for systems configured to use Fahrenheit though. A better approach is to read several times in a loop, sort measurements and discard outliers.
Both approaches would need a driver change.

**Comment by scoff3r** [comment]
Mine is actually DS18B20 but using Celsius measurements too.
Reading many times doesn't really help because when it disappears, it disappears for longer period, usually hours while it never can read it because the system doesn't find the sensor at all.

**Comment by schwabix-1311** [comment]
One more try to improve your temp sensors. I use ~10 of them in different applications, all in parasitic power mode, all except 1 work flawlessly.
How are your sensors powered?
I now found a hint to additionally ground the red wire (for encapsulated sensors) or pin 3 (for "naked" sensors). This should increase reliability. For 3-wire operation this is of course not applicable.
Hope this helps ...

**Comment by ranjib** [comment]
This is a complicated topic. There are cases where we don't want the heater to be off. This is because the ambient temperature is colder and most reef tank grade heaters ships with their own thermostat. But I agree there are cases where this is not the case. Im thinking of a middle ground where we let user decide how to respond to such cases (i.e. keep the equipment on or off in case of sensor failure).

**Comment by Furze** [comment]
Somethings to think about..
 * adding a calibration option (I know my thermostat reads x under)
 * alerting if it has been heating for x hours and hasn’t hit a target temp (like inkbirds do) 
 * If averaging the last 3 reads and if a new read is 10-20% out something is up (ignore/alert)

**Comment by ranjib** [comment]
friends, im closing this ticket as I am not taking any specific itemized work based on this (for the reef-pi software). We are fixing a bunch of ui, and driver reliability glitches that we believe will help in cases like this, but at the end we believe unfortunate things can happen specifically when the dependent things (network, electronics) goes unreliable. In this case, we recommen preset heater (with slightly higher but still safe temperature target) and notification for safe guard
