### ISSUE TITLE
health-stats time axis corrupted

### ISSUE THREAD

**Issue by schwabix-1311** [reef-pi/reef-pi#1468]
Hi, unsure how to describe what I found: 
noticed fat line segments in health-stats charts. Drilling down revealed jumps in time back and forth for exactly these time ranges.
The following raw data from api/health_stats shows such jumps in time.

{"cpu":0.22,"memory":7.64,"time":"Jun-20-**16**:55, 2021","throttle":0},{"cpu":0.14,"memory":7.73,"time":"Jun-20-**14**:56, 2021","throttle":0},{"cpu":0.18,"memory":7.63,"time":"Jun-20-**16**:56, 2021","throttle":0},{"cpu":0.24,"memory":7.71,"time":"Jun-20-**14**:57, 2021","throttle":0},{"cpu":0.18,"memory":7.62,"time":"Jun-20-16:57, 2021","throttle":0},{"cpu":0.27,"memory":7.74,"time":"Jun-20-14:58, 2021","throttle":0},{"cpu":0.14,"memory":7.61,"time":"Jun-20-16:58, 2021","throttle":0},{"cpu":0.27,"memory":7.73,"time":"Jun-20-14:59, 2021","throttle":0},{"cpu":0.11,"memory":7.6,"time":"Jun-20-16:59, 2021","throttle":0},{"cpu":0.24,"memory":7.72,"time":"Jun-20-15:00, 2021","throttle":0},{"cpu":0.12,"memory":7.59,"time":"Jun-20-17:00, 2021","throttle":0},{"cpu":0.19,"memory":7.74,"time":"Jun-20-15:01, 2021","throttle":0},{"cpu":0.17,"memory":7.63,"time":"Jun-20-17:01, 2021","throttle":0},{"cpu":0.18,"memory":7.77,"time":"Jun-20-15:02, 2021","throttle":0},{"cpu":0.29,"memory":7.7,"time":"Jun-20-17:02, 2021","throttle":0},{"cpu":0.15,"memory":7.76,"time":"Jun-20-15:03, 2021","throttle":0},{"cpu":0.29,"memory":7.69,"time":"Jun-20-17:03, 2021","throttle":0},{"cpu":0.12,"memory":7.75,"time":"Jun-20-15:04, 2021","throttle":0},{"cpu":0.24,"memory":7.68,"time":"Jun-20-17:04, 2021","throttle":0},{"cpu":0.18,"memory":7.69,"time":"Jun-20-15:05, 2021","throttle":0},{"cpu":0.21,"memory":7.68,"time":"Jun-20-17:05, 2021","throttle":0},{"cpu":0.33,"memory":7.73,"time":"Jun-20-15:06, 2021","throttle":0},{"cpu":0.17,"memory":7.67,"time":"Jun-20-17:06, 2021","throttle":0},{"cpu":0.27,"memory":7.72,"time":"Jun-20-15:07, 2021","throttle":0},

**Comment by ranjib** [comment]
I am unsure if this is a bug. CPU and memory can jump due to some usage, either by reef-pi or by something else running on the pi. Can you be more specific. Since this is  not directly indicate any issue with reef-pi I'm closing this. Feel free to reopen if you think otherwise, and we can to do some work to address  it from reef-pi side

**Comment by schwabix-1311** [comment]
I think I found the root cause. This only happens when I restart after some downtime (several hours, next day, ...). Therefore I think it overlaps two different days, as it somehow does not detect the earlier data being from previous day.
Internal storage is a relative age, not absolute date-time? 
As restarts with large gaps are not a common use case, it's not important.
