### ISSUE TITLE
Sensors reported erratic data after reboot or reload

### ISSUE THREAD

**Issue by atrumblood** [reef-pi/reef-pi#1469]
I have the latest release of reefpi running on robotank with raspberry pi. 

When I reloaded/rebooted the web interface the sensor data is reporting erratic readings. 

It was reading consistently between 8.23 and 8.26. After rebooting every reading jump between 8 and 10. 

The temperature is doing the same thing. Rebooting again has not fixed it.

**Comment by atrumblood** [comment]
[
![Annotation 2021-06-23 144515](https://user-images.githubusercontent.com/39076117/123165604-ae701880-d431-11eb-8852-17d2657c051d.jpg)
](url)

**Comment by ranjib** [comment]
Did you enabled dev mode by any chance ?

**Comment by atrumblood** [comment]
Yes actually. It didn't appear to change anything on the front end. 

I am guessing there is a known issue with that? 
I wasn't able to correct the issue until I power cycled the controller.

**Comment by ranjib** [comment]
Any changes in the settings section will require reload/reboot of the controller. Let me know if this problem still exists or if you think this is a bug, for us to be able to treat this as a bug and work on it, we have to be able to reproduce it. Please reopen if you can reproduce this as a bug
