### ISSUE TITLE
Building reef-pi on arm64

### ISSUE THREAD

**Issue by PerilousApricot** [reef-pi/reef-pi#1471]
Hello,

I was planning to use a Jetson Nano as my reef-pi machine. The 40-pin connector is pin-compatible with the rpi, however the processor is arm64 and not armhf. I attempted the follow the [build instructions](https://reef-pi.github.io/additional-documentation/development/) to make the package locally, however it appears the go packages never get pulled, yielding:

```
meloam@reefpi:~/gospace/src/github.com/reef-pi/reef-pi$ make
make go
make[1]: Entering directory '/home/meloam/gospace/src/github.com/reef-pi/reef-pi'
go build -o bin/reef-pi -ldflags "-s -w -X main.Version=4.1-184-gc4795a4"  ./commands
controller/utils/systemd.go:10:2: cannot find package "github.com/coreos/go-systemd/v22/dbus" in any of:
	/usr/lib/go-1.10/src/github.com/coreos/go-systemd/v22/dbus (from $GOROOT)
	/home/meloam/gospace/src/github.com/coreos/go-systemd/v22/dbus (from $GOPATH)
controller/utils/systemd.go:11:2: cannot find package "github.com/coreos/go-systemd/v22/util" in any of:
	/usr/lib/go-1.10/src/github.com/coreos/go-systemd/v22/util (from $GOROOT)
	/home/meloam/gospace/src/github.com/coreos/go-systemd/v22/util (from $GOPATH)
<snip>
```

With a ton of dependencies then listed afterwards. Is that dev doc up-to-date? I'm not very familiar with the go ecosystem, so I'm unsure if I've done something wrong.

Thanks!

**Comment by ranjib** [comment]
what version of go you are using ?Looks like packages are not being installed. newer versions of auto-download these packages

**Comment by PerilousApricot** [comment]
Hello,

go version reports `go version go1.10.4 linux/arm64`. This is an nvidia jetson nano running their custom ubuntu variant called

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

thanks!

**Comment by ranjib** [comment]
Please upgrade to go 1.16 . This is a go module issue.

**Comment by ranjib** [comment]
im closing this since this is not a reef-pi bug. For assistance related to development, lets sync up on slack or via email/reef2reef thread
