### ISSUE TITLE
Disable alerts in macro

### ISSUE THREAD

**Issue by Cylus7** [reef-pi/reef-pi#1481]
Hi, 

I have a macro setup for water changes; is there anyway I can, as part of the macro, disable alerts for the ato? The macro works great for the water change but I end up with a heap of ato usage alerts.

Cheers

**Comment by ranjib** [comment]
This will be little hard. Since macro steps are not aware of underlying details/properties of its components. How about create a dedicated ato that has all the same settings except the alert and use it with the macro ? Its little complicated , but should do the job

**Comment by Cylus7** [comment]
Thanks Ranjib, I hadn’t thought of creating another dedicated ato for my water change.

**Comment by ranjib** [comment]
Im closing this since i dont have any plans to implement any specific feature for this. Feel free to reopen if you want to discuss further
