### ISSUE TITLE
On reboot function

### ISSUE THREAD

**Issue by epicfatigue** [reef-pi/reef-pi#1498]
Hey all,

A fantastic enhancement which is pretty simple would be a on reboot function for ATO functions.

Basically you can have on 
reboot enable or on reboot disable.

This would be awesome for functions you only want to come on after  a power loss. 

For example my ATO for topping up fresh water could have on reboot disable. 

Then I could have a normally disabled function that uses the same sensor that could have on reboot enable.

This function would now come on and fill the lost water on a reboot then disable and enable my ATO. 
This may not work for everyone but it enables a whole new level of controllability for complex reef tanks which no other model con provide.

**Comment by epicfatigue** [comment]
@ranjib

**Comment by ranjib** [comment]
I cant think of a robust way of detecting reboot (from normal reboot, reload or start). We can introduce a start wait time that can be specified for each ato or any general purpose controller which might address this. But lets discuss more. I would like to solve this issue (controlling the behavior of reef-pi upon restart)

**Comment by prsws** [comment]
I have already implemented a "stay off on boot" feature on my modified version of reef-pi, along with other enhancements. I'm waiting for @ranjib to let me know when can I submit the pull request so it can be included in the next release. If you would like to try it before then, check my repo at [github.com/prsws/reef-pi](url).

**Comment by ranjib** [comment]
Im closing this since theres no action item for us. As mentioned we have the stay off on boot function. It will be hard to detect reboot specifically. Feel free to reopen this if you want to discuss further
