### ISSUE TITLE
Error pH on smartphone

### ISSUE THREAD

**Issue by Raf714** [reef-pi/reef-pi#1499]
Hi,
In just installed reef-pi 4.1 (new setup).
Everething works like I think it should je, except when It open the pH Page on my smartphone.
When I pull down pH there is An error!
On my tablet everething is ok!
![Screenshot_20210209_104748_com android chrome](https://user-images.githubusercontent.com/78792922/107349903-0fbdcd80-6ac9-11eb-9ee0-66d4a82e5a27.jpg)

**Comment by ranjib** [comment]
https://github.com/recharts/recharts/issues/2385

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1520
