### ISSUE TITLE
Input validation messages - translation

### ISSUE THREAD

**Issue by schwabix-1311** [reef-pi/reef-pi#1518]
To simplify the translation of the messages shown by input validation, I'd suggest to make them more generic.
E.g. if "This entry must be numeric" is used instead of "The upper temperature limit must be a number" this message would be usable for all numeric fields.
Since the message is shown next to the input field, the relation would be clear.

This would reduce translation effort tremendously.

**Comment by schwabix-1311** [comment]
I started to work on this. Is there a way to self-assign?

And a generic question: some languages' grammar does not work with the string concatenation used e.g. in confirmation dialogs.
In English the message "<p>This action will delete {doser.name}.</p>" is fine. To allow translation it would ave to changed to something like <p>{i18n.t('doser:confirm_delete')} {doser.name}.</p>"
But German (possibly others languages too) grammar requires the verb at the end of this: "Dies wird OsmoDosierer löschen."

Would it be acceptable for translators to accept variable names enclosed in curlies inside the string? 
For instance  "doser:confirm_delete,Dies wird {doser.name} löschen."
Alternatively this could be solved by a String.format() as described here https://stackoverflow.com/questions/610406/javascript-equivalent-to-printf-string-format/4673436#4673436. This is more robust when var names change, but still the .csv file would include some strange syntax (perceived by a non-programmer).
Any other idea?
BTW, this is not limited to confirmation dialogs. Validation messages for minimum or maximum values could use "... ${min} ...", which is supported by Yup.

**Comment by jaz1968** [comment]
The same problem with Balto-Slavic languages like Polish which is example of fusional language.

**Comment by ranjib** [comment]
@schwabix-1311 while i like the idea, it will be hard to have this as a generic stance. There can be cases where we want a more specific sentence. The case you mentioned is reasonable. I suggest you take one case at a time and raise PR accordingly.

**Comment by schwabix-1311** [comment]
PR1575 contains several alternatives for the delete confirmation dialogs.
1. I didn't get the documented way of replacing variables by i18next to work -> [https://i18next.github.io/i18next/pages/doc_features.html], keyword "replacing variables"
2. My preferred solution does not get jest's approval. This would be the placeholder "${somename}" in strings combined with a `i18n.t("key").replace("${somename}",actualvar)`. Jest's concern is very likely the missing backticks for string template interpolation, which in this case is not the intent.
3. Accepted by jest and working is $[somevarname] in strings, and the corresponding .replace(...)

Do you have an example where this stance would not work? This does not aupport composition of sentences for all grammars of our planet, but insertion of names or keywords should be fine. And worst case an idividual translation could not use the placeholder, and use a phrase avoiding the insertion.

**Comment by ranjib** [comment]
@schwabix-1311 is this still relevant?

**Comment by schwabix-1311** [comment]
No, as I'm repacking most of these changes into several smaller PR.  Closing.
