### ISSUE TITLE
Make install fails on Ubuntu

### ISSUE THREAD

**Issue by revoohc** [reef-pi/reef-pi#1559]
Trying to create development environment in linux.  Getting error on make install

```
server:~/gospace/src/github.com/reef-pi/reef-pi$ make install
make go-get
make[1]: Entering directory '/home/<user>/gospace/src/github.com/reef-pi/reef-pi'
go get -u golang.org/x/tools/cmd/goimports
go: finding golang.org/x/xerrors latest
go: finding golang.org/x/sys latest
go: downloading golang.org/x/sys v0.0.0-20210910150752-751e447fb3d0
go: extracting golang.org/x/sys v0.0.0-20210910150752-751e447fb3d0
make[1]: Leaving directory '/home/<user>/gospace/src/github.com/reef-pi/reef-pi'
yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
make: *** [Makefile:48: install] Error 1
server:~/gospace/src/github.com/reef-pi/reef-pi$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
server:~/gospace/src/github.com/reef-pi/reef-pi$
```

**Comment by ranjib** [comment]
https://github.com/yarnpkg/yarn/issues/2821
i think this is yarn related. not exactly a reef-pi issue. Check if this is the case, and if so, fix your yarn installation as per that ticket.

**Comment by revoohc** [comment]
Appears yarn name it used by multiple programs.  Here is what I did from a clean install to get Ubuntu working.  Might want to add it to the developer docs.

'''
sudo apt -y install git
sudo apt -y install golang-go
sudo apt -y install build-essential
sudo apt install -y curl
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt install -y nodejs
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
Sudo apt -y install ruby-full

then follow developer doc on how to download and make
'''

**Comment by ranjib** [comment]
done. im assuming you were able to setup the dev environment. please use slack for dev help. github issues are mostly for reef-pi feature/bugs
