### ISSUE TITLE
ds18b20 Temperature Sensors in Temperature Tab do not match to PI 

### ISSUE THREAD

**Issue by nixoden** [reef-pi/reef-pi#1572]
In Temperature Tab, when I add a temperature sensor; I can find 3 different sensors address, they  do not match those found on the raspberry "/sys/bus/w1/devices/" directory.
the temperature read by these sensors is always about 25°C .

![reef-pi - Google Chrome](https://user-images.githubusercontent.com/86692972/133526608-4076008e-7ed5-4348-b941-1f1e17687d91.jpg)

![pi@raspberrypi sysbusw1devices](https://user-images.githubusercontent.com/86692972/133526663-e63f7edc-c977-458d-83a1-194494cca82c.jpg)

**Comment by nixoden** [comment]
I forgot:
Raspberry Pi 3 Model B Rev 1.2
Reef-pi 4.3

**Comment by ranjib** [comment]
you have dev mode enabled. disable dev mode and reload reef-pi. Configuration -> settings -> Capabilities
