### ISSUE TITLE
rename upper and lower function terms in UI:: Temperature using ezo-rtd revisited.

### ISSUE THREAD

**Issue by CTYReef** [reef-pi/reef-pi#1600]
Hello,
I saw your last post in issue #1414 before closing that issue.  You suggested using the Reef Pi PH ezo driver for for the ezo temperature probe. I have been doing that for two years but the temperature reading is only available in the PH tab (where it does work fine for displaying the temperature) but I do not see a way to use that input as the sensor source for reef pi's temperature function which is what I really want to do as it can then support the heater/cooler control function. I may just be ignorant of the additional steps needed. Thank you for addressing this matter.

**Comment by ranjib** [comment]
Hi
the ph module does support heater/cooler like function, it's just called an upper/lower function. It does not however provide a usage chart like the temperature module, and that's something we are planning to address. After that those two modules will be identical in features

**Comment by CTYReef** [comment]
Thank you, yes, I do see that now and I have tried it on a test implementation of Reef-Pi.  It works, but with one issue:  whatever equipment that I have set to the "Lower Function" (which I configured with a relay called Heater 1) comes on when the Temperature passes (gets hotter than) the "Upper Threshold".  I assumed that the "Lower Function" would activate when the Temperature passes (gets Lower than) the "Lower Threshold", which is why I configured it with a relay name that was intended to be used to turn a heater on.   Again, I admit that I might just be ignorant of the interface.

I have attached a screen shot of my test setup in Reef Pi's pH Tab.  Note that I have two instances set up: Coax Temp 1 and Coax Temp 2.  They are nested together using the same Ezo Temp Probe (named Coax), the intent here is to control two heaters with one probe and turn "Heater 2" on if the temperature is still falling when Heater 1" is on continuously.  Also, to potentially turn a second fan one if the temperature keeps rising while the first fan is on continuously.  I have used this with three nested heaters on the One-Wire interface and it works fine.  The screenshot shows how I configured it to work with the named relays operating when they should, (heaters coming on when the temp is below the "Lower Threshold" and fans coming on when it is above the "Upper Threshold".
This seems backwards to me, so please let me know if it supposed to work this way.
![Reef Pi Test 2021-12-14 021048](https://user-images.githubusercontent.com/49430745/145968388-b0c1a630-0080-424f-b612-7dbfcba9d8f3.png)

**Comment by CTYReef** [comment]
Sorry, I did not mean to close the issue.  And thanks for creating such a great application.

**Comment by ranjib** [comment]
This is as intended. Lower function stands for mechanism that will bring down the observed value (chiller for example), while upper function stands for mechanism that will increase the observed value (heater)

**Comment by CTYReef** [comment]
As always, Ranjib, thank you.  I am guilty of misunderstanding, however, I have one small recommendation.  The word "upper" does not lend itself as well as "lower" does to the meaning that you intended.  I recommend that you use the word "raise" instead of "upper".   This would have made your intent plain to me.

**Comment by ranjib** [comment]
thank you for that suggestion @CTYReef  . Being non native engliesh speak and a techi, sometime blinds us from coming up with a more intuitive terms. "Raise" sounds ok to me. Just a request, please think about any analog sensor, not just temperature sensor and think about the lower function as well. does "raise" and "lower" makes it intuitive? I can update the code accordingly.
sincerely,
ranjib

**Comment by CTYReef** [comment]
@ranjib For any analog measurement, I would say that the words "raise" and "lower" (both verbs in this context) do convey a clear meaning.  Thank you for considering my suggestion.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1889 i have settled for "raising mechanism" and "lowering mechanism" . Let me know if you have any thoughts
