### ISSUE TITLE
The driver combo box could be populated with just the drivers offering appropriate connectors

### ISSUE THREAD

**Issue by schwabix-1311** [reef-pi/reef-pi#1601]
On page Configuration/Connectors the combobox Pins has no entries for analog inputs, when in create or edit mode.

Last release version is ok, only observed with current builds from HEAD.

**Comment by ranjib** [comment]
this is for which driver?

**Comment by schwabix-1311** [comment]
hmm, good question ... for the driver rpi, which of course does not have analog inputs.
But then the problem is, why is driver rpi offered and selected in the driver combo?

Is this possibly an unnoticed side effect of my commit cf06bb5, part of pending PR 1575?

**Comment by schwabix-1311** [comment]
Ok, this is a nice-to-have.
The driver combo box could be populated with just the drivers offering appropriate connectors.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1895

**Comment by ranjib** [comment]
thank you for this ticket. 5.3 will ship this.
