### ISSUE TITLE
reef-pi 5 PWM manual mode latency

### ISSUE THREAD

**Issue by Ren108** [reef-pi/reef-pi#1686]
Just tried out the new version of reef-pi on raspberry 3 with lite os. PWM works right after reboot in manual mode but i have to wait several seconds after adjusting the level until i see the lights changing. In version 4.3 with raspberry desktop version it changed instant. (But only if i disable reefpi in systemctl and start reef-pi after boot see issue #1598)

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1691/files

**Comment by ranjib** [comment]
Thanks for reporting this. We have fixed this is in master branch and it will be released as part of 5.1
