### ISSUE TITLE
Temperature control fails on 5.0

### ISSUE THREAD

**Issue by 5ft24dave** [reef-pi/reef-pi#1687]
After upgrading to Reef-Pi 5.0, I noticed the temperature in my tank was dropping.  I verified settings under temperature, and also verified I can manually control the outlet to turn my heater on and off under equipment.  I re-installed reef-pi to a new SD card just in case, and it is the same issue.  Heater comes on after temp sensors are configured.  Once the temperature reaches the set point, it turns off the heater.  When it drops below the hysteresis point where it should turn the heater back on, it fails.  "ERROR: Failed to execute temperature control logic. Error: Item 'nothing' does not exist in bucket 'equipment'"
I have attached a screenshot of the temp config page.
Output of logging with journalctl -fu reef-pi.service:

Dec 05 14:21:29 LeviathanAquarium reef-pi[1498]: 2021/12/05 14:21:29 Reading temperature from device: 28-020192451a19
Dec 05 14:21:29 LeviathanAquarium reef-pi[1498]: 2021/12/05 14:21:29 Reading temperature from device: 28-020792458011
Dec 05 14:21:29 LeviathanAquarium reef-pi[1498]: 2021/12/05 14:21:29 health check: Used memory: 25.54  Load5: 0
**Dec 05 14:21:29 LeviathanAquarium reef-pi[1498]: 2021/12/05 14:21:29 temperature sub-system:  sensor Tank Temp value: 77.68
Dec 05 14:21:29 LeviathanAquarium reef-pi[1498]: 2021/12/05 14:21:29 Current value of 'Tank Temp' is below minimum threshold. Executing up routine
Dec 05 14:21:29 LeviathanAquarium reef-pi[1498]: 2021/12/05 14:21:29 Equipment: Heater On: true**
Dec 05 14:21:29 LeviathanAquarium reef-pi[1498]: 2021/12/05 14:21:29 temperature sub-system:  sensor Ambient value: 67.1
Dec 05 14:21:30 LeviathanAquarium reef-pi[1498]: 2021/12/05 14:21:30 API Request:'   GET /api/me' from: 192.168.1.43:51334
....
Dec 05 14:26:10 LeviathanAquarium reef-pi[1681]: 2021/12/05 14:26:10 API Request:'   GET /api/me' from: 192.168.1.43:51441
Dec 05 14:26:11 LeviathanAquarium reef-pi[1681]: 2021/12/05 14:26:11 Reading temperature from device: 28-020192451a19
Dec 05 14:26:11 LeviathanAquarium reef-pi[1681]: 2021/12/05 14:26:11 Reading temperature from device: 28-020792458011
Dec 05 14:26:11 LeviathanAquarium reef-pi[1681]: 2021/12/05 14:26:11 health check: Used memory: 25.3  Load5: 0
**Dec 05 14:26:12 LeviathanAquarium reef-pi[1681]: 2021/12/05 14:26:12 temperature sub-system:  sensor Tank Temp value: 77.68
Dec 05 14:26:12 LeviathanAquarium reef-pi[1681]: 2021/12/05 14:26:12 Current value of 'Tank Temp' is above maximum threshold. Executing down routine
Dec 05 14:26:12 LeviathanAquarium reef-pi[1681]: 2021/12/05 14:26:12 Equipment: Heater On: false
Dec 05 14:26:12 LeviathanAquarium reef-pi[1681]: 2021/12/05 14:26:12 ERROR: Failed to execute temperature control logic. Error: Item 'nothing' does not exist in bucket 'equipment'**
Dec 05 14:26:12 LeviathanAquarium reef-pi[1681]: 2021/12/05 14:26:12 temperature sub-system:  sensor Ambient value: 66.99
Dec 05 14:26:14 LeviathanAquarium reef-pi[1681]: 2021/12/05 14:26:14 API Request:'   GET /api/me' from: 192.168.1.43:51441

![Reef-Pi](https://user-images.githubusercontent.com/37747536/144766909-619a5056-390c-49b4-85bb-47bbb02eb024.jpg)

**Comment by 5ft24dave** [comment]
log entry from when temp is down below hysteresis temp and tries to turn on the up routine:

Dec 05 14:55:08 LeviathanAquarium reef-pi[1889]: 2021/12/05 14:55:08 Reading temperature from device: 28-020192451a19
Dec 05 14:55:08 LeviathanAquarium reef-pi[1889]: 2021/12/05 14:55:08 Reading temperature from device: 28-020792458011
Dec 05 14:55:08 LeviathanAquarium reef-pi[1889]: 2021/12/05 14:55:08 health check: Used memory: 25.26  Load5: 0.05
Dec 05 14:55:09 LeviathanAquarium reef-pi[1889]: 2021/12/05 14:55:09 temperature sub-system:  sensor Tank Temp value: 77.45
Dec 05 14:55:09 LeviathanAquarium reef-pi[1889]: 2021/12/05 14:55:09 Current value of 'Tank Temp' is below minimum threshold. Executing up routine
Dec 05 14:55:09 LeviathanAquarium reef-pi[1889]: 2021/12/05 14:55:09 ERROR: Failed to execute temperature control logic. Error: Item 'nothing' does not exist in bucket 'equipment'

**Comment by ranjib** [comment]
thank you so much for sharing these details. Its a bug :-( . I see whats happening, there was some UI changes that's making the temperature controller save target chiller equipment as "nothing" instead if empty.
Good news is, It has the details, and I;ll be able to get a fix asap.

**Comment by ranjib** [comment]
@5ft24dave while i work on getting a fix out, you can try with an explicit lower temperature threshold (say 81 F) and a fake equipment (create one with any of the available GPIO) as chiller in the temperature controller settings and it should work for now

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1689
