### ISSUE TITLE
Use same Light Channel for both Day and Lunar

### ISSUE THREAD

**Issue by ykri** [reef-pi/reef-pi#1690]
Dear Team,

I tried to use the same Light Channel (Royal Blue) for both Diurnal during daytime (07:00-21:00), and Lunar (21:15-06:59). It partially works as during daytime Royal Blue is ON at the correct light level for ~25sec and then switches OFF for ~3sec repeating this cycle. The same happens after 21:15 when the Lunar mode kicks in, ON at the Lunar light level and completely OFF for few secs.

Should I set it up differently, or there is an improvement to be made? It would be a waste to have to install an extra channel for Moonlight while I have the Royal Blues.

Many Thanks,

Yiannis

**Comment by ranjib** [comment]
theres no direct support for using multiple profiles with UI yet , reef-pi has a specific type of profile called composite profile, which will allow doing this in a complex way, but only through API).
But I think you can do this relatively easily in this way:
1) define two different lights , both using same channel with the profiles you like
2) use timers to enable and disable individual lights (corresponding to the profiles you want) to control the effective profile

keep us posted.
I'm closing this as I'm not taking any work item from this .

**Comment by ykri** [comment]
Thanks Ranjib!
It worked with your suggestion. 
Only problem now is that if I need to reboot or have a power lose, the problem comes back until the next timer is fired up.

**Comment by ranjib** [comment]
ack. i think once we add UI support for the composite profile, you should be resolve this
