### ISSUE TITLE
English language selected but German is shown on Lights Auto/Manual message box

### ISSUE THREAD

**Issue by Whentheworldends** [reef-pi/reef-pi#1692]
Added a new light channel and toggled with Auto button. I was presented with a message box containing a German language message. Thinking there was a simple mistake in my last visit to the configuration page I navigated there to insure I had selected English. Confirmed selection and then reloaded with the same result. Header topics are in English, "Dashboard, Equipment, Timers. Lights"....). 
![LED Message](https://user-images.githubusercontent.com/11824007/146783075-87203d4e-0589-4a88-aadc-c2221aece539.PNG)
![LanguageSelection](https://user-images.githubusercontent.com/11824007/146783218-917c1197-8c45-4a43-a22f-bb50268eeb80.png)
![Version](https://user-images.githubusercontent.com/11824007/146783371-3a3b590b-c8aa-4271-86a7-8d09febd1b24.PNG)

**Comment by schwabix-1311** [comment]
Should be addressed by pending PR 1694

**Comment by ranjib** [comment]
should be released in 5.2
