### ISSUE TITLE
Cannot unmarshal string into Go struct field Trigger.duration

### ISSUE THREAD

**Issue by schwabix-1311** [reef-pi/reef-pi#1738]
This is observed when a timer tries to include a duration:

1/10/2022, 11:46:02 PM | UI | ERROR | {"error":"Failed  to update. Error: json: cannot unmarshal string into Go struct field  Trigger.duration of type time.Duration"} \| HTTP 500
-- | -- | -- | --
1/10/2022, 11:31:06 PM | UI | ERROR | {"error":"Failed  to create. Error: json: cannot unmarshal string into Go struct field  Trigger.duration of type time.Duration"} \| HTTP 500

This article might describe the solution:  https://stackoverflow.com/questions/48050945/how-to-unmarshal-json-into-durations

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1782
