### ISSUE TITLE
reef pi Journal  cannot add entry (fixed)

### ISSUE THREAD

**Issue by ErenKarapinar** [reef-pi/reef-pi#1744]
Hello
I just setup up mu reef pi I have everything working in order for now I have 8 channel relay functional, I just tried to use journal section I click on "+" and I can add  Name, Description , Unit  and I can save but after that I do not see any where I can add my parameters or anything the only thing I can do is add name description and unit can you help me 
Thanks

**Comment by ranjib** [comment]
closing this. feel free to reopen if you want to discuss this further
