### ISSUE TITLE
Temperature control issue

### ISSUE THREAD

**Issue by indymx** [reef-pi/reef-pi#1756]
Unsure why this is happening, but my heaters are not turning on on one of my tanks.

I get an error message in the logs:

Feb 4 06:25:14 nempi reef-pi[6535]: 2022/02/04 06:25:14 Current value of 'temp' is below minimum threshold. Executing up routine
Feb 4 06:25:14 nempi reef-pi[6535]: 2022/02/04 06:25:14 ERROR: Failed to execute temperature control logic. Error: Item 'nothing' does not exist in bucket 'equipment'

I setup a dummy outlet and configured the chiller to control that and everything works. I can see some users never figuring this trick out and abandoning the program. This setting should be controllable. Perhaps a toggle for "Chiller" so that it skips that check if a chiller is not used?

**Comment by schwabix-1311** [comment]
Hi Gary,
What you report is affected by two things:
- The bug with  item 'nothing' was fixed Dec. 6 and should be in 5.1.
- The need to select a heater and a chiller (that needed some creativity if you have only one of the two) was addressed too, possibly post release of 5.1.
Are you possibly using pre-5.1? Or you preserved your configuration from pre 5.1, in which case you should re-create your temperature controller, to get rid of the item 'nothing'.

**Comment by indymx** [comment]
No, I am using a post 5.1 version. Built from src the day I posted the bug report.

**Comment by ranjib** [comment]
the error indicates a specific bug where equipment id was saved as "nothing". can you please update and credit that temperature probe settings?

**Comment by ranjib** [comment]
@indymx please test with 5.2, we have fixed this in 5.2. I just tried it out in main branch and was not able to reproduce this issue,  if the problem still persist, feel free to reopen this ticket and I'll take a look
