### ISSUE TITLE
[UX] The UI should warn about Dev Mode

### ISSUE THREAD

**Issue by richievos** [reef-pi/reef-pi#1778]
Awhile back I was first setting up my Reef Pi on Robotank and playing with settings. I was attempting to get a DIY ATO setup, using a peristaltic pump I built out of various parts I had / 3d printed. I for awhile had it mostly working, and then suddenly everything stopped working altogether.

I was spent awhile trying to figure out what was going on, and was incredibly frustrated, almost punting on the reef pi idea and just buying parts. I started thinking I must've fried the componentry somehow. Eventually I just walked away, and then a couple days later decided to give it one last try with a full reset.

Around then I started walking through the troubleshooting guide I found, and saw the "watch out for Dev Mode" warning. I almost immediately knew that was my problem, since I'd recently been trying to play with more settings and one of the things I saw was that, so I just flipped it on.

To me, [an Android user, Dev Mode means "Enable Advanced Features"](https://developer.android.com/studio/debug/dev-options). To me, a developer, I also understand the need for a stubbed out mode for testing. However, to me, reef pi newb, Dev Mode was a big shiny red button of pain :).

My suggestions:

A. [rename] Rename the Dev Mode checkbox to something else that's more explainy, such as "Disable all Outputs for Testing Purposes". Or at least put a big mouse over warning on it. This avoids an Android user misinterpreting it.
B. [save alert] Pop up a warning on the UI when you hit Update and save turning that feature on, warning that change just occurred.
C. [static alert] Throw a static alert into the UI when that mode is enabled. I'd ideally make it big and obvious, but at least putting something in the Footer saying "Test Mode: All Outputs Disabled" would be helpful. Fancy CSS tricks might involve throwing some text in the header under the reef-pi text: "reef-pi\n(Test Mode)"
D. Throw a warning on the Equipment page or elsewhere

I think _rename_ plus one of the alerts would be ideal. I again imagine both of those wouldn't be too hard, and am happy to take a pass at one/all if you agree.

**Comment by ranjib** [comment]
i think we should remove dev mode from capabilities and only detect it through environment variable or configuration file. Any changes to those things are assumed to be done by expert users. Normal users should not need dev mode. Does that make sense

**Comment by richievos** [comment]
> i think we should remove dev mode from capabilities and only detect it through environment variable or configuration file. Any changes to those things are assumed to be done by expert users. Normal users should not need dev mode. Does that make sense

That makes lots of sense to me. Worst case someone just restarts with the env var set vs unset.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1887
