### ISSUE TITLE
[UX] Use Deep Links in Header

### ISSUE THREAD

**Issue by richievos** [reef-pi/reef-pi#1780]
I commonly want to pop open multiple tabs of reef-pi things. For instance, seeing the dashboard while messing with ATO settings, or pop open ATO+Dashboard+Configuration. Right now because they aren't actually links, I have to dup the window and then navigate to them. I'd normally expect to just be able to right-click and "Open Link in New Tab" to pop open another one.

Generally being able to deep-link in to reef pi would be helpful.

Given this is a React app I think this is just a matter of some push state hooks or integrate switching to React Router.

Thoughts?

**Comment by ranjib** [comment]
i am ok to support this as long as it does not break the current single page user experience.

**Comment by ranjib** [comment]
thank you @richievos for addressing this. its in main branch now
