### ISSUE TITLE
Data logged into incorrect position in graph

### ISSUE THREAD

**Issue by dolezelk** [reef-pi/reef-pi#1795]
Dta are beeing logged into incorrect position in graph. 
![Untitled](https://user-images.githubusercontent.com/4452189/161151712-ed74aa99-d784-4fec-8486-b30f85f6ea32.png)
you can see on attache dpicture, please note X axis description 

Time is mixed starts with 22:54, then there is 21:39 and after 22:23
Every other graphs are also affected by the bug

running 5.2, on Raspberry Pi 3 Model B Rev 1.2

**Comment by ranjib** [comment]
i have fixed this in couple of places, but there might be few still remaining.. i'll try to reproduce it. does this problem persist even if you reload reef-pi?

**Comment by dolezelk** [comment]
Unfortunatelly, even after reload or even reboot of my PI will not ressolve it

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1888
