### ISSUE TITLE
Temp hysteresis validation errors when cooler disabled

### ISSUE THREAD

**Issue by richievos** [reef-pi/reef-pi#1836]
This is similar to #1786 and #910, but requires a couple steps to get yourself into a bad state. The problem is you can get the heater temp = the cooler temp by enabling/disabling them incrementally, and then you're stuck and can't edit and it's not clear why.

Series of steps:

## Setup
1. create a temp setup
2. enable the heater control, set it to 79 (pick whatever equipment just to get it saved, or a fake macro)
3. enable the cooler control, set it to 80 (pick whatever equipment just to get it saved, or a fake macro)

## Trigger the first issue
4. flip the cooler control to None
5. change the heater temp to 80

You'll now get a "Hysteresis is less than acceptable threshold" error and can't save.

## Trigger the second issue
6. flip the heater control to None

You now can save. This will result in heater value = cooler value = 80)

## Trigger the final issue
7. Re-enable the heater

You won't see any validation errors

8. Hit save

You'll get the hysteresis error again.

That's somewhat expected if you know what's going on, but you'll not have any reason why you're actually getting that error.

# Proposed fix
I'm still not exactly sure what hysteresis does honestly, but generally if only one of cooler/heater is enabled then the temp values for the other one should be completely ignored.

**Comment by ranjib** [comment]
This is one of those UI validation bugs. I'll line it up for patching. Thank you for reporting this with specifics, it helps a lot in patching

**Comment by richievos** [comment]
FYI, this appears to be worse on master than it was on my device. I just locally built reef-pi to try and start submitting PRs, and when I tried to add a temp sensor for the first time it failed.

1. fresh start
2. Add an outlet & a piece of equipment
3. go to temperatures
4. hit `[+]`
5. enter in a name, select sensor=28-devmodeenable
6. save
7. open up to edit
8. switch control to Equipment, Heater=that_equipment_you_added, Heater Threshold=80
9. Hit Save

Result: "Hysteresis is less than acceptable threshold" error. If you try and change that you still get an error. You have to go in, switch the Chiller to your equipment, set Chiller Threshold to something > heater threshold, then switch Chiller back to None, then you can finally hit save
