### ISSUE TITLE
[Feature Request] Make F vs C a display config versus a data config

### ISSUE THREAD

**Issue by richievos** [reef-pi/reef-pi#1838]
Right now when setting up a Temperature, you have to choose Celsius (C) vs Fahrenheit (F). This not only affects the data is displayed (expected) it also affects the way the data is recorded (unexpected). For instance, if you start as C and switch to F, the charts don't auto-update, it just shows the old C value which would be out-of-range for F.

Similarly, when mousing over charts it'd be nice to see both C & F not just one or the other.

From an implementation standpoint I can see how that occurs, but from a user standpoint it's unexpected.

Expected / desired behaviors:
* I can see in the temp graph C and F in the mouse-over
* if I switch the type (`F->C, C->F`) in the UI, I should see all the old data updated appropriately in the charts

I assume the default implementation would be do everything in C and handle F as a conversion in the UIs. As long as the data is stored to 1 decimal place, that should still translate well to F. I would not necessarily expect this to carry over to external integrations (Adafruit, Prometheus). For those I'd personally send both readings

**Comment by ranjib** [comment]
i like this idea and agree the current setup is not correct. Since the original sensor provides values in celsius, i think we should just use that for storage and in frontend convert it back to fahrenheit based on the configurartion. you want to work on it? else i'll pick up eventually

**Comment by richievos** [comment]
Regarding implementation, I took a look at this a bit and though I didn't really get very far, I did get a general idea of the gotchas.

The main gotchas I thought of:

* the temp isn't being passed around/stored with units, it's just a raw float. That's going to make it a bit difficult to feed the data through
* existing stored data is going to be persisted as whatever units they were originally on. Being backwards compatible may be tricky. I'd guess ideally there'd be a migration step to convert the data into a standard format, versus permanently having all the data support both variants
* the telemetry data needs to be converted to whatever the UI wants to see. Doing it on the frontend seems like a poor API and bad for responsiveness. Doing it on the backend, on-the-fly, seems bad for a CPU constrained raspberry pi.
* the notification / alert / equipment code would either still need to be unit aware, or converted to a standard format in the backend. Both have some complications.

For the data storage, I'm thinking the best solution may be to just dual-write the telemetry. Once in F, once in C. Then the read paths can either return both ala ` { "telemetry": { "fahrenheit": [], "celsius": [] } }` or just map whatever the current configured setting is to a single field `{ "blah": choose_data_set(fahrenheit, celsius, legacy_singular_val) }`. Then the conversion only has to happen once (on write) and the API and UI can be dumb/fast.

For remote storage (prometheus, adafruit), either everyone would have to migrate to `F` / `C` streams, or it could be written 3 times (`CurrentName.F`, `CurrentName.C`, `CurrentName`).

For the alerts/notifications, the simplest solution is just leave everything as-is and just read from whatever the appropriate unit data stream is. That part should be easy.

**Comment by ranjib** [comment]
after thinking through this i am leaning towards keeping the behavior as it is. Its a compromise in both side. We can call this out in the docs. Im closing this since i am not taking any action item from this. Feel free to reopen if you feel otherwise.
