### ISSUE TITLE
PWM dosing pumps not responding

### ISSUE THREAD

**Issue by AchiTG** [reef-pi/reef-pi#1840]
Dosing pumps (throw pwm) are not responding at all from doser menu. Tried to test the pumps from lighting menu and they was working fine.  I downgrade to 5.1 and again they was workink normal. I try for a second time version 5.2 with a clean installation but it gives me the same issue.

**Comment by ranjib** [comment]
Thank you for reporting this. i have landed a fix . It will be available in 5.3 release. Please reopen this ticket if you still encounter this issue
https://github.com/reef-pi/reef-pi/pull/1891
