### ISSUE TITLE
Dosing pump calibration button does not work

### ISSUE THREAD

**Issue by atrumblood** [reef-pi/reef-pi#1853]
Greetings, 

 I recently just tried to add another dosing pump to the reef-pi with robo-tank setup I have, and I noticed that the calibrate options don't work. I will enter the power % and the duration, click run and nothing happens. 

I am running Ver 5.2

These are not stepper motors and I tried to connect to all of the DC ports. 
It should be noted that the schedule I have assigned each pump does run when it is supposed to, and it only seems like the run button on the calibration isn't working.

Edit: added more details.

**Comment by loksiklubos** [comment]
I have a problem with the dosing pumps in version 4.2 they work properly when I enter a speed of 50 for 1 second, the engine starts nicely and dispenses a small amount.
When I upgrade to version 5.1 or 5.2, I have a problem that the motor does not start at speed 50. I have to set speed 80 to work. At this speed I can't give a low volume of chemistry as in version 4.2. In version 5.2, the pump calibration does not work and even the PH shows something that has gone wrong, it can be repaired. I'm also trying the new version 6.5, but I'm still having problems and I'm testing your procedures

**Comment by ranjib** [comment]
sorry for your trouble. I have landed a fix recently, it will be out in 5.3. If possible, please test and let us know if its working as expected. Feel free to reopen this if the problem still persist. 
https://github.com/reef-pi/reef-pi/pull/1891
