### ISSUE TITLE
After reload, new points are added to Graphs in the dashboard from start of time scale

### ISSUE THREAD

**Issue by vahegan** [reef-pi/reef-pi#1868]
After clicking "Reload" in Admin, all existing data points in Dashboard graphs are sorted based on their timestamps, i.e. oldest data points are on the left and newest on the right. This behavior is expected.

However, when new data points are added to the graph after this reload point, they are added on the left part of the graph, rather than continuing on the right part. Moreover, each new point is added to the left from the previous. When I click "Reload" again, these data points move to their proper places on the right part of the graph, but again any newer points are added in the left. 

For illustration, see the screenshots. The data point for June 14 is to the left of the data point of June 13. A reload was made at the data point with time stamp at 02:51 on June 14, 2022

![Screen Shot 2022-06-14 at 02 46 20](https://user-images.githubusercontent.com/3999569/173460393-13c5e56d-8f3e-4511-960d-5de67bfd15d6.png)
![Screen Shot 2022-06-14 at 02 46 04](https://user-images.githubusercontent.com/3999569/173460400-d5850f09-bcdc-4f15-9670-c9dd21d5ee61.png)

**Comment by vahegan** [comment]
The issue has resolved on its own, with no apparent reasons

**Comment by vahegan** [comment]
The issue is still there. I have to Reload every time before I view the dashboard, otherwise new data points are displayed in the middle of the graph

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1888
