### ISSUE TITLE
Confusion in pH section

### ISSUE THREAD

**Issue by danmrossi** [reef-pi/reef-pi#1954]
Hi All

When i go into the pH section and expand my configured ph probe (where you see chat unit, frequency etc) there is 2 ph graphs at the bottom.

Can anyone explain to me what the left/right one is and why they show different? tried my google fo, reef-pi docs etc to no avail

many thanks

![image](https://user-images.githubusercontent.com/50608357/193460278-82c28033-d4e6-4079-84c8-63223439eeb0.png)

**Comment by ranjib** [comment]
the graph on the left (Recent) is one data point at every check interval, e.g. if you have set ph probe at 15s interval, the graph on the left will be 15s interval for .
while the graph on right (historical) is for long term, individual data point is stored at 1 hour interval level (hence might last for a month). The number of data points stored in recent and historical graphs are configured under telemetry configuration tab
