### ISSUE TITLE
ESP32 with 2 ds18b20 temperature sensors

### ISSUE THREAD

**Issue by wbirriel** [reef-pi/reef-pi#2010]
I have a functional ESP32 with 2 ds18b20 temperature sensors confirmed to be working correctly.  I am able to configure the driver on the reef-pi UI running 6.0-24-g149ec245.  They have been configured as 2 analog inputs but they are not available for configuring as Temperature even after adding them as connectors.

**Comment by TheRealFalseReality** [comment]
I daisy chained my DS18B20 sensors (On an RPi3) to GPIO4 (1-wire pin) and got them on the Temperature tab, Using 3

**Comment by ranjib** [comment]
@wbirriel they are exposed as analog inputs from esp32 driver and can only be used from the ph module in main reef-pi, not temperature module. This is as expected. In future we'll merge the two modules into a single, analog sensor based control module. Im closing this as i think there is not action item for us. Feel free to reopen if you want to discuss this further
