### ISSUE TITLE
ATO logic is wrong when using alerts

### ISSUE THREAD

**Issue by mginster** [reef-pi/reef-pi#2117]
The current "Alert after" is a running total.  This counter needs to reset each time the topoff completes.   IE if you have an alert after of 10s and you have 2x5s topoff sessions, it will then throw the alert and disable the ATO (which you should have enabled to prevent sensor sticking on, etc).  

All ATO's operate in this manner (reset counter after topoff)....not sure how this was missed.

**Comment by ranjib** [comment]
currently it resets every hour :-) . Thoughts?

**Comment by mginster** [comment]
Very useful information, thank you.  I will configure a max/hour alert.
