### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'analog-input')

### ISSUE THREAD

**Issue by sam-e** [reef-pi/reef-pi#2193]
Getting this error with a Pi-4 running the latest 32 bit Bookworm version of Raspian

TypeError: Cannot read properties of null (reading 'analog-input')

**Comment by sam-e** [comment]
failed to initialize drivers:can't build hal pin 12: strconv.Atoi: parsing "20+rpt": invalid syntax

**Comment by danmrossi** [comment]
I believe Bookworm isn’t properly supported yet and as to when it will be is anyone’s guess, you’ll have to install “Bullseye”

**Comment by sam-e** [comment]
Thankyou

**Comment by 5ft24dave** [comment]
Bookworm works  However, the latest kernels (6.6.x and above) have removed the GPIOD libraries.  you can downgrade the kernel in bookworm to 6.1.74 with the command
`sudo  rpi-update d86b5843d68b9972a5430a6d3da1b271cfc83521`
it runs fine on Pi3, 4 and 5's
