### ISSUE TITLE
failed to initialize drivers:can't build hal pin 7: embd: your host ":" is not supported at this moment. request support at https://github.com/reef-pi/embd/issues

### ISSUE THREAD

**Issue by piwi3910** [reef-pi/reef-pi#2211]
Installed my robo-tank board today with a raspberry pi4

was running a pi 0 w2 first with no issues, 
reinstalled it now with a pi4 
and getting this error

failed to initialize drivers:can't build hal pin 7: embd: your host ":" is not supported at this moment. request support at https://github.com/reef-pi/embd/issues

not sure how to debug this.
i2c seems to be working

piwi@reef-pi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- 63 -- -- -- -- 68 -- -- -- -- -- -- --
70: 70 -- -- -- -- -- -- --

**Comment by apk-1989** [comment]
i am having the same issued have you found a solution yet
