### ISSUE TITLE
Implement data import  & export functionality 

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#280]
reef-pi should allow users to take backup of all their settings (configuration, connectors, equipment, lights etc) as well as restoring everything from a backup file.

**Comment by ranjib** [comment]
Tentative ideas:
- Store version information in database, and use it for computing automatic import, export
- Import = core controller import + sum of all modules imports
- Export = core controller Export + sum of all modules exports
- return types as []bytes

**Comment by ranjib** [comment]
we need the export in 1.5, and import in 2.0. Probably few other versions of reef-pi as well (1.x has a few breaking changes within minor versions as well :-( )

**Comment by zekth** [comment]
Maybe an idea would be to export the database in a zip file with a json file describing the context of export and it will be used during the import.
By this way after the upload the API check if the database is ok for import checking at the version of the database and the reefpi version. What do you think?

**Comment by dmolavi** [comment]
Upgrades from 2.x to 3.x will require some sort of data manipulation and should be done automatically, so users don't need to recreate macros, timers, etc.   It would appear the addition of the drivers bucket, along with the drivers attribute to inlets/outlets, and the analog_input are the only changes in the database and should be easily added to an upgrade routine...
