### ISSUE TITLE
Maintenance alerts

### ISSUE THREAD

**Issue by ryjc56** [reef-pi/reef-pi#288]
Is it possible to have alerts either scheduled (every day, 2 days, week, month, etc...) or for a specific day, for maintenance purposes. I think it would be most useful to have these user defined, and to set up interval and method of alert.
Method could either be message section in reef-pi, or text/email message (not at 00:00 of day of reminder)
A few examples:
-Reminder to clean skimmer every week.
-Reminder to clean pump every month.
-Reminder to change RO membrane a year from today.
-Reminder to mix water for next water change.

**Comment by ranjib** [comment]
Will it make sense to add an Alert target in the existing timer sub-system. 
Currently, reef-pi allows equipment on/off in timer. We can update it to use either equipment or an alert. With alerts details (title and body) specified by user.

**Comment by ranjib** [comment]
WIP: https://github.com/reef-pi/reef-pi/pull/291

**Comment by ranjib** [comment]
released as part of 1.2
