### ISSUE TITLE
When connecting a second Temp. Sensor, the reef pi does not recognize it.

### ISSUE THREAD

**Issue by ALPHAB3TS00P** [reef-pi/reef-pi#296]
When connecting a second Temp. Sensor, the reef pi does not recognize it.

The first sensor was connected to pin 4  in a cool area and and worked just fine.

I wanted to test a second, so I added it on the pinout in addition to the one on pin 4. the second was connected to pin 26 next to my computers heat sync fan so I could see a temperature change. 

I did not see it show up, so I removed the sensor on pin 4 from reef-pi (still connected to the physical pin) to try out the one on 26. I then rebooted the pi from the UI. There were no changes in temperature readings.
To be sure I moved the pin 4 sensor by the heater for a minute or to (please see attached) and sure enough, it went up. 

I believe that this is not desired behavior. 

I did a reboot between switching. I am wondering if there is some strange caching going on where it won't change the pin its reading from if its still connected ? 

Does this make sense? 
![image](https://user-images.githubusercontent.com/15350027/34911371-a4ad2656-f886-11e7-81c7-f0393e8228f9.png)

![image](https://user-images.githubusercontent.com/15350027/34911374-afa23a88-f886-11e7-8987-0f01a92ca2fe.png)

these are readings from pin 4 sensor still, even though I removed it from reef-pi and rebooted...
![image](https://user-images.githubusercontent.com/15350027/34911415-52a1bb82-f887-11e7-9807-47dd1b9d5dec.png)

**Comment by ranjib** [comment]
reef-pi currently support only one temperature sensor. If it detects more than one sensor, it will stop reading sensor data. If you are seeing data even after connecting second sensor, check if that sensor is detected by linux kernel or not,
```
ls /sys/bus/w1/devices/
```
should have two 28-xxxxx entries.
reef-pi will support multiple temperature and ato sensor soon. We have separate issue on this, hence I am closing this as duplicate. Please reopen this ticket if I am missing anything else. For any feature request around multiple temperature sensor support, feel free to comment here:
https://github.com/reef-pi/reef-pi/issues/278
