### ISSUE TITLE
Support providing an offset to the temperature probe

### ISSUE THREAD

**Issue by theatrus** [reef-pi/reef-pi#324]
Cheap Dallas 1wire sensors (or knockoffs) from China, while they claim 0.5C precision, aren't usually all that accurate. 

There should be a spot in the UI on the temperature sensor to enter an offset for it.

**Comment by ranjib** [comment]
I think having support for general 1 point (offset only), two point (offset and gradient) and three point calibration would be very useful.

**Comment by theatrus** [comment]
I was about to say that over normal tank temperature variance allowing for gain calibration or multi-point is a bet excessive, but the actual implementation is simple so why not.

**Comment by Ranthalion** [comment]
I'll add UI for single point calibration.  Respond if multi-point seems important for temperature calibration.

**Comment by ranjib** [comment]
Backend work for this has been done already. The UI support is remaining
