### ISSUE TITLE
Macro functionality 

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#382]
Macro or feed mode or group actions is a common requirement for day to day reef keeping chores whereby users have to switch on or off multiple equipments and disable timer jobs etc during water change or feeding fish / corals.

Users should be able to group a set of equipments,timers and specify actions against them (on/off for equipments, start/stop for timers ). Once specified users can trigger the macro to execute all those actions against target equipment/ timers . Macros should also provide a reverse feature where by all actions are reverted.

Users should also be able to trigger macros using timers.

**Comment by sjeff35** [comment]
Yes please.  I would love to see a "Feed" button.

Thanks

**Comment by ranjib** [comment]
Work in progress: https://github.com/reef-pi/reef-pi/pull/463
This will require extensive testing as the surface area is quite large
