### ISSUE TITLE
Change Tab with Sidebar

### ISSUE THREAD

**Issue by danggrianto** [reef-pi/reef-pi#386]
The tab is not responsive, in the mobile view it will become stacked. I propose to move it to sidebar and for the mobile view it will be hidden in the hamburger menu. I will attach the prototype later.

**Comment by danggrianto** [comment]
![desktop](https://user-images.githubusercontent.com/1197594/40757893-b04f296c-6458-11e8-9245-b50644b91c67.png)

**Comment by ranjib** [comment]
I like the idea of using side bar, and I definitely want to see a better user experience in mobile devices.
I am wondering if theres any other way to achieve this. I like the tab UI on laptop/larger screens. Is there a way we can use media query and then fall back to a mobile friendly UI instead ?

**Comment by ranjib** [comment]
oops. closed by accident, reopened

**Comment by danggrianto** [comment]
that was the plan. something like this https://blackrockdigital.github.io/startbootstrap-sb-admin/. what do you think? if you are okay with it, i will start working on it on my free time

**Comment by ranjib** [comment]
@danggrianto I have removed react-tab with stock bootstrap navbars recently, this should simplify the work that needs to be done for making the navbar as side bar (or just show sidebar instead of navbar in mobiles using media query)

**Comment by zekth** [comment]
Implemented on last build. Configuration tabs are still in development. Closing issue.
