### ISSUE TITLE
Adafruit.io telemery tab will not save AIO key

### ISSUE THREAD

**Issue by Massild** [reef-pi/reef-pi#440]
Issue:  No telemetry or feeds created on adafruit.io
When attempting to setup telemetry I found that the AIO key is not saved.  I am testing this by typing in the AIO key, then I click update, then go to another tab and then back to telemetry.  Then I see the username and prefix are saved but not the AIO key.  I have this running on a "production" Raspberry Pi 3B+, a test Raspberry Pi 3B+ and a test Raspberry Pi Zero W.  All of these exhibit the same issue.  I believe this is the root cause for it failing to update the or even create the feeds at adafruit.io.

**Comment by Massild** [comment]
I forgot to mention that I have run into this on all variants of 2.0.0 beta (beta, beta 2 and beta 3)

**Comment by ranjib** [comment]
When you say AIO key is not saved, do you mean AIO key is not visible in the configuration UI ? If so, thats as design (i know its confusing). Its an UI improvement that I have to do, the AIO key is actually saved, its just reef-pi does not show the saved sensitive data (AIO key and reef-pi password) in UI

**Comment by Massild** [comment]
Thank you for the feedback.  I was trying to diagnose the adafruit.io issue and made the assumption that it was not saving since it was blank in the 2.0 version which did not work and present in the 1.5 version where it did show.  Thank you.

**Comment by Craigo1972** [comment]
Noob question, what is the prefix is that the "aio_" part of the key and if so do I put "aio" or "aio_"
