### ISSUE TITLE
Add ability to select graph colors for lighting widget.

### ISSUE THREAD

**Issue by Massild** [reef-pi/reef-pi#442]
It would be helpful to have the ability to set the graph display color to match the light color in a graph. 
For example: There are multiple color channels controlled by jack 1.  In the settings for that jack there would be a color drop down box for each channel.  This would allow a more complete visualization of the current lighting program.

Thank you for your consideration.

**Comment by ranjib** [comment]
Implemented in the channels details for every light:
https://github.com/reef-pi/reef-pi/pull/445
Will be available in next beta release , and stable release as of 2.0

**Comment by Massild** [comment]
Thank you for the quick development. It is highly appreciated
