### ISSUE TITLE
Add another light option "Diurnal Cycle"

### ISSUE THREAD

**Issue by Massild** [reef-pi/reef-pi#443]
In addition to the slider value or auto mode, I suggest a third option of diurnal cycle.  This would use a function to calculate the light amount along a curve.  This has the advantage of being a smoother, more natural lighting cycle as well as being simple to setup as you would only specify the max and min value for that channel, the time of day to start the ramp up and the time of day to end the ramp down.  I am attaching a suggested UI for what I think this would look like.

Operationally the max value would set the upper limit for that channel.  In my case, my lights are far more powerful than needed so this would be in the 50% range.  The min value could be used to keep a light on.  For instance if you wanted a "moon" light.

I have done this in an arduino application that I ran my last aquarium with.  Reef-pi has a nicer UI and more capability than the program I wrote so I switched earlier this year.  I am including an excel file that I used to dial in an accurate representation of the solar cycle for reference.  

Here is an explanation of what the function does:
We want to calculate the value from 0-1 to represent the percent of light at this time in minutes and we will call this value PercentLight.
PercentLight is calculated as a function of the negative cosine of the daylight hours, defined by the user, divided by 2 pi to get the step.
The value in the cosine function is cubed to get a steeper rise and a flat top.  The function is as follows:
Calculate the steps... This gives the number of steps in a full cycle of radians for day hours.
**All times are in minutes elapsed since midnight**
(Current time - Start time)* 2*pi / (End time - Start Time) 

Then cube the cosine of that value.  This produces a shape with a second peak (First plot in the excel file graph).  Use a min or ceiling function to eliminate this peak (second plot in the excel file graph).  Finally multiply this value by the Max Lights value - Min Lights Value and then add the Min lights value.  PercentLight * (Max - Min) + Min  
=(1-COS((minutes-startMinutes)*2*PI/(End Minutes-startMinutes))^3) * (Max - Min) + Min 
Let me know if this makes sense or if you would like clarification.

![diurnal light ui](https://user-images.githubusercontent.com/3534181/42522638-7872a586-8420-11e8-9791-f93e9ae3513d.png)
[sun simulation.xlsx](https://github.com/reef-pi/reef-pi/files/2181298/sun.simulation.xlsx)

**Comment by Massild** [comment]
To put this in a more programmatic way...

Prelevel=(1-COS((CurrentMinute-StartMinutes)*2*PI()/(EndMinutes-StartMinutes))^3)

IF CurrentMinute<StartMinutes THEN 
PctLights = 0 
ELSE IF CurrentMinutes > EndMinutes THEN 
PctLights = 0 
ELSE IF PreLevel > 1 THEN
PctLights = 1
ELSE PctLights = PreLevel
END
PctLights = PctLights * (MaxValue-MinValue)+MinValue

**Comment by ranjib** [comment]
I like the idea. Let me think through about the implementation

**Comment by ranjib** [comment]
I am thinking to implement this in reef-pi, but in more generic format. My current thoughts are
- Introduce a notion of profile in individual channels
- A profile has type and profile specific configuration
- Implement fixed, auto and diurnal all as separate profiles 
Does this sound ok ?

**Comment by Massild** [comment]
If I understand you correctly this sounds good.  
I think you mean that this would be similar to the screenshot I made up but with a combobox to select a specific profile instead of a checkbox type?
The profile also would have a configuration (say start end time, min max etc.).  Do I understand you correctly?

I am very impressed with reef-pi overall so I am sure that what you plan on implementing is going to be great.  

Thank you for being so open to suggestion.

**Comment by ranjib** [comment]
As mentioned earlier in this thread, I have introduced a notion of profiles for individual channels. Fixed intensity, auto (12 values each spaced at 2 hours) and diurnal are all implemented as separate profile.
Here are the screen shots (work ub orogress)

Light
<img width="992" alt="screen shot 2018-07-18 at 8 33 42 am" src="https://user-images.githubusercontent.com/316306/42891989-88a0c24e-8a65-11e8-8cd6-f41651445d98.png">

Details of individual channels under a single light
<img width="1005" alt="screen shot 2018-07-18 at 8 33 53 am" src="https://user-images.githubusercontent.com/316306/42891988-8884d778-8a65-11e8-97b2-bd0450f8908d.png">

Profile choices under individual channels
<img width="1056" alt="screen shot 2018-07-18 at 8 34 21 am" src="https://user-images.githubusercontent.com/316306/42891987-886a8972-8a65-11e8-83b2-24b02297ea70.png">


Pull request: https://github.com/reef-pi/reef-pi/pull/455

Diurnal logic implementation: https://github.com/reef-pi/reef-pi/pull/455/files#diff-a9027c13e87105204283f26b41d0af03R30
Example diurnal chart:
<img width="606" alt="screen shot 2018-07-18 at 8 39 03 am" src="https://user-images.githubusercontent.com/316306/42892185-0ec381cc-8a66-11e8-8baa-e4e22dbb83dc.png">

**Comment by Massild** [comment]
I like the implementation.  It is a little different than I had thought from our discussion, but reading back through, I see this is what you meant.  This abstraction will be a huge benefit for future development as well.  Very nice work and I appreciate the graph.   I am very happy with this implementation.

What I thought you meant would likely be more complicated and would not add a lot of value at this stage.  

Just for information, this is what I thought you meant.

A generic profile would be created in a separate dialog or screen where the parameters would be set.  This could be a function, points on a graph etc.  Then you would save the generic profile with a name.  Then when you were in the lighting screen, or wave maker screen, you would have the option to choose a profile to apply to the object (lights, wave maker etc)
When you click update, the object would then follow that profile.  This would be similar to how a pitch or throttle curve is setup in a radio controller (open-tx as an example)
This is a 12 point curve (same as auto).  You can manually move the points or type in values.
![12 point](https://user-images.githubusercontent.com/3534181/42897127-e2009900-8a73-11e8-84ad-026742fcd512.jpg)
This is an example where there are only 2 points.  This is for a flat or linear option.  
![fixed](https://user-images.githubusercontent.com/3534181/42897128-e21b1bae-8a73-11e8-89ea-b0e40e6c3241.jpg)

As you can see, you just create a bunch of generic curves and then select them in the lighting interface as to which curve fits your needs.  I like your solution better as it is less complicated.
