### ISSUE TITLE
Send alert when temperature sensor is not detected

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#469]
Often time ds18b20 sensors are not detected in linux , either due to circuit issue or sensor going bad or sometime for no obvious reasons. reef-pi should send alert (if configured) and stop temperature controller when this happens

**Comment by robertobuti** [comment]
I suggest a further improvement, a second optional temperature probe, comparing the two probes you can verify the measurement and discharge the wrong one (with alarm), when you manage heater and chiller it's important feature. 
Temperature probes sealing process is not sure at 100% and often they break in short time when salt water infiltration work.

**Comment by ranjib** [comment]
supporting multiple temperature probe will involve signifcant refactoring. We may also decide to do the same for all other probes. Let have a general design discussion around this. i.e. a general mechanism to support multiple probe based decision making,

**Comment by dansmout1983** [comment]
Ranjib Im stumped !
Both my DSB temp sensors went AWOL.   No serial number in the drop down, graph showed them drop out for no obvious reason.


No sign of lufe on reboot/replug. :/

Worked for about 3 months perfectly without a glitch.

**Comment by robertobuti** [comment]
Probably is a salt water problem infiltration on probe, it's common problem , sealed process is not done as required.
Now you need to reaplce them, i suggest to seal each probe inside a small PVC tube closed on one end (with pvc stop), PVC is easy to work and with specific glue become a single item. Seal the probe inside with epox resin. If done correctly the probe will survive to your tank. Redundancy probes with alarm are mandatory for temperture management. I'm Sure Ranjib is thinking about.... :-))
