### ISSUE TITLE
Timers not working in R2 beta 7

### ISSUE THREAD

**Issue by nhtones** [reef-pi/reef-pi#486]
I have been unable to get a timer to trigger in the latest beta release 2.0.0-beta 7.  I reverted to an earlier release 1.0  and was able to trigger a timer and was able to see the output in the system journal.

I am running on a pi 3 mobel B.

Happy to provide assistance diagnosing this issue.

**Comment by ranjib** [comment]
This bug was introduced during the UI change, where the new timer jobs had the "enable" field set as false. In 2.0 , timers can be stopped and started.

I have already fixed this in master, it will be released as part of the first alpha
https://github.com/reef-pi/reef-pi/pull/485

**Comment by ranjib** [comment]
released: https://github.com/reef-pi/reef-pi/releases/tag/2.0.0-alpha-0
