### ISSUE TITLE
Outlet shows in-use even if removed from ATO

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#500]
ATO control equipment is not freed up after dis-association, the equipment still shows as in-use

**Comment by Ranthalion** [comment]
This may also be present on Equipment.  
Steps to reproduce:
1. Create an equipment choosing an outlet (i.e. Outlet A).
2. Edit that equipment and choose a different outlet (i.e. Outlet B).
3. Create a new equipment choosing the outlet selected in step 1 (i.e. Outlet 1)
