### ISSUE TITLE
Get rid of confusing error message on reload

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#510]
In-stead show helpful message and request for browser refresh

**Comment by zekth** [comment]
With invalid credentials or just make a standard component for handling message from api?

**Comment by zekth** [comment]
@ranjib could you describe a scenario?

**Comment by ranjib** [comment]
When we hit Configuration -> Admin -> Reload, reef-pi restarts, causing a bogus 5xx http error in the UI. We can either solve this in the UI (just dont show the alert, since its expected), or in the backend  (return the http response and then start the reload mechanism)

**Comment by zekth** [comment]
We may need to do a restart screen like the one for Fatal error. Unless we have to refactor a lot in the app within states and so on. I'd prefer to block UI while it's restarting. What do you think?

**Comment by ranjib** [comment]
Works for me. I think its ok if we reuse the fatal error component and add some more informative message there,, like "do a browser refresh in few seconds".. 
@Ranthalion any thoughts?

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/624
