### ISSUE TITLE
Telemetry setup throws bogus ui alert during setup

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#524]

**Comment by ranjib** [comment]
@zekth you are still interested in working on this?

**Comment by zekth** [comment]
@ranjib yes, but still need a scenario to reproduce.

**Comment by ranjib** [comment]
@zekth Navigate to Configuration -> Telemetry -> Select adafruit.io checkbox, and you'll see a validation alert appearing. This is an old ui component which is using showAlert instead of formik schema based validation, i think
