### ISSUE TITLE
ATO improvement suggestion

### ISSUE THREAD

**Issue by robertobuti** [reef-pi/reef-pi#547]
Hello, 
ATO function it's ok, however i think a useful improvement can be easily done. 
The function expected a pum to refill the tank / sump from a fresh water tank, when the fresh water tank is empty the pump risk to run dry and break it. More then no water will add to your tank....
So the suggested solution is provide a settable timeout counter, if expected water level is not reached within the timeout value the pump will be stopped and a alarm generated.

**Comment by zekth** [comment]
Nice remark. I think the default timer on the Tunze one is 3 minutes if i remember well.

**Comment by jmurjr** [comment]
Another method other than time out for safety would be a second sensor above the first that if water is detected it turns off the power to the fill pump.  Personally I run all three right now (normal float, time elapsed, and secondary eye sensor) and hope to move the functions to reef-pi.

**Comment by ranjib** [comment]
Theres a similar discussion on the temperature controller as well. I am thinking of a generic mechanism to use multiple sensor for decision making. Lets share any thought you may have around this.

**Comment by ranjib** [comment]
We have implemented this using alerting when usage is above a threshold and disable on alert
