### ISSUE TITLE
LogBook Suggestion

### ISSUE THREAD

**Issue by zekth** [reef-pi/reef-pi#548]
As we store metrics data in reef-pi, it would be great to add a log book for parameters in the app. For example those parameters:

- Alcalinity
- Calcium
- Magnesium
- Nitrates
- Phosphates

**Comment by Ranthalion** [comment]
Can you provide additional details to flesh out this functionality?  
 - Does it interact with any other functionality?
 - How does the user interact with this feature (read, edit,delete)?
 - Do you have any mockups for UI (I've used draw.io and ninjamock)?
 - Describe potential data model

This doesn't directly contribute to automating a reef tank, however reef-pi currently collects ph and temperature data.  It will be worthwhile to consider this feature when designing other features that can take actions based on measurements.

**Comment by zekth** [comment]
> Does it interact with any other functionality?

In my own view not really. It would be if we have an alkalinity probe and and a ph probe to log all the changes between those two.

> How does the user interact with this feature (read, edit,delete)?

Yes, it is just a CRUD API. Nothing really fancy.

> Do you have any mockups for UI (I've used draw.io and ninjamock)?

Will work on it so.

> Describe potential data model

Something like this

```Typescript
interface MeasureType {
  ID: Number
  Name: String
  Unit: String
}
interface Measure {
  ID: Number
  Date: Date
  Value: Float
  Type: MeasureType
}
```

> This doesn't directly contribute to automating a reef tank, however reef-pi currently collects ph and temperature data. 

True. But i see a lot of people messing around with mutiple apps for doing this or that. In this way it would be centralized in it. It is a really simple feature to code which offers a logbook for people who want to log all their tests.

**Comment by ranjib** [comment]
I like this idea and 👍  for getting it in reef-pi. The thing we have to be careful though is, currently reef-pi database almost always stays under 1MB (heck, less than 300Kb in most of my builds). With the current data model, it should be OK, but if we are also allowing things line "comment" or "note" then we should be careful about performance. Not only that database size will grow, it will also incur pretty decent I/O against raspberry pi SD card, which is kinda heaters of Raspberry Pi, the most frequently failed component. Anyway, we should get this going. I am assuming this for users to add custom metrics/values for things. I am also assuming we'll be providing some sort of graphing/ charting capabilities?

**Comment by zekth** [comment]
Exactly.

For the hardware limitation we may have to discuss about it to optimize the use of it.

**Comment by ranjib** [comment]
@zekth are you planning to work on this. If not lets close it.

**Comment by zekth** [comment]
Closing for now. May open another one if needed in 3.0
