### ISSUE TITLE
Outlet deletion gives inconsistent list

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#555]
Steps to reproduce:
- Create 8 outlets.
- Delete an outlet from top of the list
- Notice the outlet remains on the list, and outlet below is shown as deleted.
- Refresh shows correct outlet list. This is UI only bug, i.e. in the backend, the proper outlet is deleted
- This does not happen if outlets from the bottom of the list are deleted

**Comment by Ranthalion** [comment]
This has also been reported as an issue with connectors.  It's likely also present with the inlets.  We can fix all 3 at one time.
