### ISSUE TITLE
Macro run to running state update in UI should be instantenous

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#556]
Currently, macro "run" button stays enabled for few seconds after clicking it, before transitioning to "running" text and disabled state. This should be instantenous,

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/issues/888

**Comment by stvnmbr1** [comment]
I have this issue in 3.0 rc and previous beta. When i click run UI still shows run, even after refresh. tried different browsers and mobile, same issue. Creating a new macro and running that one also doens't show running.
I can see the post gets sent to reef-pi with OK status
