### ISSUE TITLE
Notification / Log Feature

### ISSUE THREAD

**Issue by zekth** [reef-pi/reef-pi#570]
In a need to refactor the UI notifications for events in the app with @Ranthalion we worked on a component to handle it. After working on it, an idea of using a websocket channel to notify the user of any specific event on the server side appeared and we thought about a bigger feature which will resolve Diagnostic / debugging the app.

The feature consist in storing specific events in the bucket of the API. For example : Warning / Error / Critical. And give the availabity to the UI to Read / Export / Delete it. Once the user is connected to the UI the events are still stored in the bucket but a websocket channel is openned to directly notify the user of any event of this kind.

Benefits of this feature:
- Log centralization UI / API
- Easiness of debugging

**Comment by ranjib** [comment]
We have already an /api/errors endpoint to see critical failures and delete them, via the UI. Its part of the "summary" component in UI, which gets refreshed every 10s (polls using timer). We can change that part to use websocket instead to make it more instantaneous. What about compatibilty? Does all browser/mobile support this?

**Comment by zekth** [comment]
Websocket support: https://caniuse.com/#search=websockets

**Comment by zekth** [comment]
https://github.com/reef-pi/reef-pi/commit/0eb5557021dad432021462cf014c7bfbd853e6e6 has implemented UI log  features.

**Comment by zekth** [comment]
closing
