### ISSUE TITLE
Dont show footer information always in mobile

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#575]
Currently, footer information (IP, date, uptime etc) are always visible in every screen, even on mobile. Other than giving summary information which helps users debugging & troubleshooting, this was designed to streamline to bug reporting as well since all metadata (including reef-pi version) is available straight from screenshots.  Though on the desktop this is ok, on mobile this takes up significant space. Remove it from mobile view always, and make it accessible as a separate tab/nav item.

**Comment by Ranthalion** [comment]
As an additional tweak, could the current page name show on the mobile header?   On desktop, the current tab is bold, but there is no indication of current tab on mobile once the menu is collapsed.

**Comment by ranjib** [comment]
Yeah that will be cool too
