### ISSUE TITLE
Triggers for Macros

### ISSUE THREAD

**Issue by Ranthalion** [reef-pi/reef-pi#581]
As a reef keeper, I want to trigger macros based on inputs from sensor readings.  This would allow me to press a physical button to initiate a feed timer, or photo timer.  It would also allow for PH thresholds to turn off reactors, and temperature to selectively turn off certain equipment.  For example, if the temperature raises above a threshold, reef-pi could turn off non-essential heat producing equipment like reactor pumps and metal halide lamps.

This would probably require a significant system refactor since the current modules seem to directly control specific functionality.  This feature may have some implications or interactions with the log book feature if sensor reading may be written to log book as well.

**Comment by ranjib** [comment]
@Ranthalion tagging this for 3.0 , I am assuming you are not aiming for 2.0, let me know if thats not the case. 

I too would like to have this feature.

**Comment by ranjib** [comment]
@Ranthalion you think you'll have time to work on this. Let me know if you need any help or just want to deprioritize it for later

**Comment by ranjib** [comment]
Ok, I just double-checked. All control mechanism in temperature and ph and temperature module now uses a common homeostasis module which is responsible for equipment control. The homeostasis module allows either equipment or macro to turn on or off. This should address the use case described here. We have to add UI support for the same. Im closing this, feel free to reopen if you think we are missing something. We'll track the UI work in a separate ticket
