### ISSUE TITLE
Multilingual Support

### ISSUE THREAD

**Issue by zekth** [reef-pi/reef-pi#582]
A good feature would be to add multilingual support for the app. After some quick research this library may be fitting our needs : https://github.com/i18next/react-i18next

Language i can contribute:
- French
- English

Aim for the v3 release would be:
- English
- French
- Spanish
- German

**Comment by ranjib** [comment]
We should ask in reef2reef as well.
An additional doc on how to contribute to reef-pi ui for new language under the docs section will be good as well

**Comment by zekth** [comment]
I will prepare a branch for the support files to work on it while we continue to work on v2. Storing the translations in /jsx/translations.
Then it will be easier for everyone to contribute on this translations without having potential merge issues.
Seems right to you?

**Comment by ranjib** [comment]
+1

**Comment by robertobuti** [comment]
if you like i can provide for Italian

**Comment by bijookha** [comment]
I can do hindi/urdu, if it is needed...

**Comment by zekth** [comment]
So as v2 is out i'll write some scripts to make the translation work easier for contributors.

**Comment by elijanio** [comment]
I would like to contribute with the translation of language into Portuguese. How can I help you?

**Comment by zekth** [comment]
Portuguese has been added recently, for contribution you can follow this guide : https://github.com/reef-pi/reef-pi/blob/master/docs/internationalization_contributing.md
