### ISSUE TITLE
Repository organization

### ISSUE THREAD

**Issue by zekth** [reef-pi/reef-pi#589]
As we contribute more and more, and some other projects related to reef-pi are in development i suggest to organize repository a little bit because it starts to be a little mess between UI / API parts. Everything in the root folder is little bit a mess IMO.

i suggest:

```
/bin
/build
/ci
/src
  /API
    /tests
      *.test.go
    *.go
  /UI
    /assets
    /tests
      /*.test.js
    *.jsx
  /MobileApp (if we do one)
```

I can do it. If agree, prefer to wait the v2 release?

**Comment by ranjib** [comment]
What if we split out the backend in separate repo altogether?

**Comment by zekth** [comment]
> What if we split out the backend in separate repo altogether?

We could but in this way we have to link submodule so. Like Reef-pi has link to reef-pi-API and reef-pi-UI for example.

**Comment by Ranthalion** [comment]
I would prefer to keep front end and back end together as a coherent full product.  If additional front ends are created, then it would make sense to have a separate repo.

**Comment by zekth** [comment]
Agreed with @Ranthalion .
Does my organization good for you guys?

**Comment by zekth** [comment]
As the v2 release is out now. Do we consider to organize the repository like this? @ranjib any thought?

**Comment by ranjib** [comment]
I am ok with this. I was also thinking of moving the entire controller backend code out of it. in a separate repo. And we can do the same for ui as well. have a separate repo for it. This repo (reef-pi main) can have all the packaging stuff and add frontend/backend as a mono repo. Thoughts?

**Comment by zekth** [comment]
As @ranthalion already mentionned back and front end are tied together. So his point is valuable too. But to build the final artifact we will have to have a repository with submodule of ui and backenf right? Like reef-pi-stack importing repository: reefpi-ui , reefpi-server.

I havent any problem with both vision. Just the separation of projects will need more work in the beginning but seems to be cleaner for further development.

**Comment by ranjib** [comment]
@zekth I am closing this with an assumption that we have achieved this goal now. Feel free to reopen if needed
