### ISSUE TITLE
Add Cache Busting to webpack build

### ISSUE THREAD

**Issue by Ranthalion** [reef-pi/reef-pi#598]
Users may experience problems after upgrading reef-pi since browsers cache static content.  This issue can be fixed by using a cache busting scheme during the production webpack build.  This should solve the problem of asking users to make sure they clear their cache after upgrade.

**Comment by zekth** [comment]
@Ranthalion you want to add HASH in the file path?

**Comment by Ranthalion** [comment]
I don't have any implementation in mind.  I think HASH is a typical solution, but I have not researched any alternatives.

**Comment by zekth** [comment]
> I don't have any implementation in mind. I think HASH is a typical solution, but I have not researched any alternatives.

We can use HASH for release number / revision. Depends on how you want to implement it. Also http server can handle it too. But in our case the best is hash or revision. I'm taking care of it.
