### ISSUE TITLE
Allow configuration ato notification over UI

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#603]
This was removed from UI during refactoring. The backend / API supports this.

**Comment by Ranthalion** [comment]
@ranjib I don't recall seeing inputs for this when I updated the UI for ATO.  I do see UI schema validation for fields, but no inputs.  Would this feature simply include a boolean for enable alerts and a numeric field for Max?  If so, what is that max values compared against?  

If that is the intention, I could add something like the following to the ATO UI.

![image](https://user-images.githubusercontent.com/1632746/46987211-39b18180-d0c1-11e8-950d-5cc25c5fc3b7.png)

**Comment by ranjib** [comment]
It was there in the 1.x series, I cant recall when we lost it during 2.0 refactoring. 
The proposed UI looks perfect to me. An information message mentioning this(the alert threshold) is the "total number of seconds ato pump is on" will be useful as well
thank you for taking on this :-)
