### ISSUE TITLE
Introduce wavemaker

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#631]
- WaveMaker is a separate tab
- Each wavemaker has a jack associated with it.
- Number of pins in a jack will control the number of pumps. Each pin is represented as one pump (analogous to channels in light )
- Each pump/pin can have a profile, similar to light profile, except these are more similar to wave making. 
- reef-pi ships with random, gradual, profiles
- users can create their custom profile

Open questions
- Coordination among pumps? Gyres?
- Macro integration?
- Profile details

**Comment by lhuffhines** [comment]
Each pump should be able to be selected as a master or a slave to offer coordination between 2 or more units.  

Masters alternate with slave units when in a pair or sequential order if more than 2. 

Each pump should have a max % and min % (0 for off), run time (mm:ss:ms). Off time is equal to run time.

**Comment by ranjib** [comment]
@lhuffhines  I lost you on the last sentence. "Off time is equal to run time" means what? and runtime (mm:ss:ms), denotes what? From an implementation perspective, we need speed (pwm value) and duration (how long), so anything thats user facing has to be broken down to these two basic properties in software

**Comment by lhuffhines** [comment]
On a wave function the off time is equal to the on time.  Or the pulse time.   The MM:SS.MS. Is minutes:seconds.milliseconds

So, to apply for implementation I want pump 1 (master) to run at 60% for 1.2 seconds (00:01.2) then be off (or a minimum speed) for the same length of time. Pump 2 (slave) will run opposite of that to make the wave. Once pump 2 has had it's on time, they swap back.

**Comment by stvnmbr1** [comment]
awesome ! just started to do all research and parts needed :D 

I think it would be great if it would be possible to simply connect a pump with the same dmx connector and do the same on reef pi as the controller.

W1/W2/C/else-random  & Night mode (lowest constant flow setting)
speed selection of wavemaker and frequency of pulse

I think this could be implemented quite ez, use the same code for lighting without schedule and add patterns. But then again, i'm not such a badass at coding .. ^^


Master slave would be a nice to have but hey, you got to start somewhere ;)

**Comment by ranjib** [comment]
We have added the support for arbitrary pwm profile and better timers and macros. And collectively they encompass all wavemaker use case. As a result, I have decided to not introduce a dedicated wavemaker module as it will just increase the complexity/things in UI. Instead I plan to streamline the UI in future to have all the dimmable things together (light or doser or wavemaker) and all the sensor based control things together (temperature , ph) this will reduce complexity and improve ease of use. We'll have to do some work on the UI to make the tabs more generic and please help us making that easier by suggesting name, ideas etc.

**Comment by ranjib** [comment]
The 3.0 tutorials will definitely cover wavemaker using the pwm profile, timers etc. Just that there wont be a dedicated wave maker tab.

**Comment by robcamer** [comment]
Hi there, where can I find the 3.0 tutorials?

**Comment by ranjib** [comment]
@robcamer unfortunately we didnt include any wave makers in reef-pi 3.0 or later. This was deprioritized due to the lack of externally controllable power heads and that most commercial power heads (vortech, gyres, even hydor) comes with their own controlles.
However, we do have those pwm profiles from lighting profiles. So if you have a controllable powerhead, you can use those , just model them as lights in reef-pi for the time being
