### ISSUE TITLE
Validate dashboard configuration before saving

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#640]
reef-pi allow users to configure dashboard configuration including row and column size and specifics of individual charts in an individual cell. Though currently reef-pi does not validate the details of the individual cells and row/column number are appropriate. For example, users can save following dashboard config which is invalid (details of one cell is missing):

```json
{
  "column":1,
  "row":2,
  "width":500,
  "height":100,
  "grid_details":[
     [{"type":"equipment","id":"current"}]
   ]
}
```

Other than this missing semantic validation (that row X column == grid matrix) there is also missing general validation (column, row should be positive integer .. etc). The scope of this issue is to bring [dashboard configuration UI](https://github.com/reef-pi/reef-pi/blob/master/jsx/dashboard/config.jsx) code under formik based validation as well as enforcing semantic validation

**Comment by zekth** [comment]
Is it still an issue? I can't reproduce it. Some validations has been done during the development fixing this issue i think. Could you confirm?
