### ISSUE TITLE
Cookie expiration for API connections

### ISSUE THREAD

**Issue by sfgabe** [reef-pi/reef-pi#667]
Xpost from reef2reef:
I've been sending commands and getting data to/from reef-pi via the API (from/to Home Assistant) for about a month now and I have to say it works flawlessly @Ranjib. Fantastic job on that!

One question though - is there a way to disable the cookie expiration? It seems like I'm getting about two weeks before I have to update the auth code by logging in and capturing a new one manually. I'm not super worried about security since it's only LAN anyway.

**Comment by zekth** [comment]
It's possible, just have to set an environment option to handle the endless cookie. @ranjib your thoughts?

Here is the place where it needs to be changed:
https://github.com/reef-pi/reef-pi/blob/master/controller/reef_pi.go#L37

Documentation:
http://www.gorillatoolkit.org/pkg/sessions
https://github.com/gorilla/sessions/blob/master/options.go

**Comment by sfgabe** [comment]
Hi @ranjib I see this was implemented and quickly reverted when it broke some stuff. Are there plans to get it working? If not is there a local workaround I could use? I don't feel I need a password security-wise, is there a way I can bypass auth?

**Comment by zekth** [comment]
I'll check this.
