### ISSUE TITLE
Ability to trigger local scripts

### ISSUE THREAD

**Issue by sfgabe** [reef-pi/reef-pi#668]
This is also from a reef-pi question that got buried:

Can we have a macro (or something else) that triggers a local python or bash script? This would basically function as a container for expanding into customized code territory.

**Comment by theatrus** [comment]
Running as root feels like a bad idea for arbitrary programs, though as a whole this isn't the worse integration method.

**Comment by sfgabe** [comment]
For example, I want to be able to "Feed the fish at 3pm" which could be a macro that 1. shuts off the pumps for 15 minutes and 2. triggers a python script to activate the feeder. I assume anyone running python scripts would be able to navigate chowning them to the proper user.

**Comment by sfgabe** [comment]
This is basically what I'm doing now. I would prefer to activate a script through the gui but I suppose at the least complex, the use case is simply to have some mechanism in the reef-pi gui so I can see that the script has been run. 

Perhaps there can be a configurable data point that could accept a flag sent from the script through the api? Then we could see a 1/0 dashboard chart like a float sensor

**Comment by ranjib** [comment]
@sfgabe closing this as we are not planning to work on this. Feel free to reopen it if you have compelling use case. I may comeback  to this in 4.0 with some nifty systemd timer/job integration for executing programs outside reef-pi but with systemd dbus api, in async mode. It will be quiet a bit of work, but it will be an awesome addition for all the hackers , in a really robust not-hacky fashion.
