### ISSUE TITLE
New installation HTTPS issue

### ISSUE THREAD

**Issue by bishoptf** [reef-pi/reef-pi#676]
Clean install of raspbian and installed the latest version, I have a model 3 A+ and I assume I should use this version - reef-pi-2.0-pi3.deb, I am able to log on with the default, change username and application name but when I try to enable https, I get an error message and when I try to connect via https I receive a connection refused.  When I try to connect via port 80 it wants to download a binary file, basically I am locked out unless I blow it away and start over (remove package that is). Tried, chrome and firefox bowsers.

I would like to enable https for obvious issues but not sure what the issue is, if you need any logs or information please let me know.

additional information from service:

http: TLS handshake error from x.x.x.x:43626: tls: first record does not look like a TLS handshake

**Comment by bishoptf** [comment]
Nevermind, dumb user, forgot to change the address and port before selecting https option, working now.

:)

**Comment by theatrus** [comment]
:+1:

**Comment by ranjib** [comment]
yeah, this is a common issue. We have a separate issue to address the UX issue where reef-pi should warn user if they choose https without changing the port

**Comment by bishoptf** [comment]
Understand, having a major pain trying to access https version from any
chomre based version, chromium, chrome or opera.  I know its the self
signed cert issue but I cannot for the life of me figure out how to make it
go away.  I'm not a winblows user, I only use linux and usually am using
opera. ive tried to import the cert and still no luck. Firefox works once
it balks and I add the exception but opera and chrome are giving me this
error "You cannot visit tankpi right now because the website sent scrambled
credentials that Opera cannot process. Network errors and attacks are
usually temporary, so this page will probably work later."

Guess I'm going to go to bed for now, I really appreciate the work you have
done with this, I'm just a freshwater guy and I am about to build me one up
but just for on and off stuff, lights, heaters etc.  I do have one question
is I do want to add more temp controllers and you stated it was simple to
add more but not sure how you add the additional temp sensors, wiring that
is.  Any input into how to go about that would be welcomed.

Thanks :)

**Comment by zekth** [comment]
I will write the warning of the user for https selection
