### ISSUE TITLE
Https certificate issue with Chromium/Opera

### ISSUE THREAD

**Issue by bishoptf** [reef-pi/reef-pi#678]
The self sign certificate appears to work fine from Firefox but I am unable to connect via chromium or Opera.  Here is the message for Opera, similar on Chromium:

x.x.x.x normally uses encryption to protect your information. When Chromium tried to connect to x.x.x.x this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be x.x.x.x, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chromium stopped the connection before any data was exchanged.

You cannot visit x.x.x.x right now because the website sent scrambled credentials that Chromium cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

Not sure what the issue, did some google searches but nothing worked to allow the connection. Probably a can be a low finding, since it appears to work with firefox, currently I'm running arch linux with the latest kernel, I tend to use opera the most but will use FF to access reef-pi.

**Comment by ranjib** [comment]
I have tested on Firefox and chrome . I know users who run reef-pi on windows/ie . I have not tested in opera, not sure this is specific to reef-pi or self signed certificates and opera

**Comment by bishoptf** [comment]
Understand, I will do some more poking looks like it effects chromium and opera which uses the same baseline.  If I want to generate my own cert and replace the existing one, where do I go to do that.  I will try changing the certificate up and try to determine what the issue is, not sure where I can substitute the cert to play around with it.

Thanks

**Comment by ranjib** [comment]
@bishoptf is this still an issue. I really dont know if we can do anything about this on our side. I am closing this due to that.
