### ISSUE TITLE
PH Value Action

### ISSUE THREAD

**Issue by tiredofit** [reef-pi/reef-pi#679]
Nice project. I was wondering if in the future you are planning to be able to trigger actions based on PH Value. For example, If I am running a calcium reactor, I would like to trigger a power switch when the PH is either too high or too low.

**Comment by ranjib** [comment]
This is something I want to ship as 3.0 feature. Should be before May/june

**Comment by tiredofit** [comment]
Fantastic! I'm actually not in the reefkeeping game at this point in time, Have been chomping at the bit for the last 13 years without one. Expecting a new setup in the next 6 months, so right now designing enclosures with my 3d printer for power boxes, probes, display etc. I was planning on building my own software via Angular and Python, but seeing your project gives me some motivation to learn Go and submit some pulls. Nice work.

**Comment by ranjib** [comment]
thank you for the kind words. We could use any and all help with software development :-) . go and react both are pretty easy to learn. Drop me an email if you want to join the developer slack channel (reef-pi.slack.com)

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/813

**Comment by ranjib** [comment]
this will be shipped in 3.0
