### ISSUE TITLE
HTTPS server not starting up on power on/reboot

### ISSUE THREAD

**Issue by bishoptf** [reef-pi/reef-pi#681]
Shutdown Pi to do some work, new install, when I powered it back on the HTTPS server is not accessible.  Pulled this from systemctl status:

Dec 28 08:37:59 tankpi reef-pi [337]: 2018/12/28 08:37:59 failed to run https server Error:listen tcp x.x.x.x:443

Doing a systemctl restart reef-pi and it comes up properly.  Running latest raspbian stretch version.  I did check journalctl but did not see any error's, if you need any additional information let me know.

Thanks

**Comment by ranjib** [comment]
You have something already running on pi that’s using port 443 . Try running “netstat -tulnp | grep 443”

**Comment by bishoptf** [comment]
New install, I do not have anything else  loaded, in fact the only thing I have to do in order to get it working is to restart reef-pi via systemctl.

systemctl status reef-pi
● reef-pi.service - raspberry pi based reef tank controller
   Loaded: loaded (/lib/systemd/system/reef-pi.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-12-28 13:35:52 CST; 25s ago
 Main PID: 282 (reef-pi)
   CGroup: /system.slice/reef-pi.service
           └─282 /usr/bin/reef-pi daemon -config /etc/reef-pi/config.yml

Dec 28 13:35:53 tankpi reef-pi[282]: 2018/12/28 13:35:53 INFO: equipment subsystem: Finished syncing all equipment
Dec 28 13:35:53 tankpi reef-pi[282]: 2018/12/28 13:35:53 Successfully started subsystem: equipment
Dec 28 13:35:53 tankpi reef-pi[282]: 2018/12/28 13:35:53 Successfully started subsystem: timers
Dec 28 13:35:53 tankpi reef-pi[282]: 2018/12/28 13:35:53 Successfully started subsystem: ato
Dec 28 13:35:53 tankpi reef-pi[282]: 2018/12/28 13:35:53 Successfully started subsystem: temperature
Dec 28 13:35:53 tankpi reef-pi[282]: 2018/12/28 13:35:53 Successfully started subsystem: macro
Dec 28 13:35:53 tankpi reef-pi[282]: 2018/12/28 13:35:53 reef-pi is up and running
Dec 28 13:35:53 tankpi reef-pi[282]: 2018/12/28 13:35:53 Starting https server at: 10.x.x.x:443
Dec 28 13:35:53 tankpi reef-pi[282]: 2018/12/28 13:35:53 ERROR: Failed to run https server. Error: listen tcp 10.99.99.9:443: bind: cannot assign requested address
Dec 28 13:35:53 tankpi reef-pi[282]: 2018/12/28 13:35:53 Starting health checker

sudo netstat -tulnp | grep 443
[sudo] password for bishop: 
bishop@tankpi:~ $ 

Nothing is running on port 443, raspian stretch lite.

**Comment by bishoptf** [comment]
Here is the information when booting from journalctl:
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Successfully started subsystem: system
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Setting GPIO Pin: 27 State: 0
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Setting GPIO Pin: 22 State: 0
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Setting GPIO Pin: 23 State: 0
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Setting GPIO Pin: 24 State: 0
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Setting GPIO Pin: 25 State: 0
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Setting GPIO Pin: 5 State: 0
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Setting GPIO Pin: 6 State: 0
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Setting GPIO Pin: 12 State: 0
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 INFO: equipment subsystem: Finished syncing all equipment
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Successfully started subsystem: equipment
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Successfully started subsystem: timers
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Successfully started subsystem: ato
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Successfully started subsystem: temperature
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Successfully started subsystem: macro
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 reef-pi is up and running
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Starting https server at: x.x.x.x:443
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 ERROR: Failed to run https server. Error: listen tcp x.x.x.x:443: bind: cannot assign requested address
Dec 28 13:45:58 tankpi reef-pi[282]: 2018/12/28 13:45:58 Starting health checker

**Comment by bishoptf** [comment]
I think I figured it out, not sure how you identify this but on the IP line I was putting my IP address in for the 0.0.0.0:443 and that would not start up on boot. Changing it to 0.0.0.0:443 works on boot.  Close out the issue, not sure but maybe adding some words to describe what is needed to enable https.

:)

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/issues/625
