### ISSUE TITLE
Monthly Timers

### ISSUE THREAD

**Issue by GiuseppeYoghi** [reef-pi/reef-pi#688]
Is it possible to set monthly timer in the current version?

**Comment by ranjib** [comment]
Its should be doable with the current version already. If you let us know your exact schedule, I can share an example configuration
https://crontab.guru/

**Comment by GiuseppeYoghi** [comment]
Thank you for your reply!
I would like to set the ligth reflecting the temporal chronology of the year, without edithing the schedule each month); i.e. times of first of February different of first of March and so on...
you think that is it possible?
thanks again

**Comment by ranjib** [comment]
Not with the UI. You can use the API to do something like this. I am closing this issue, since monthly timer is possible with reef-pi. We'll be working on custom pwm profile which may allow this. Feel free to reopen this if you are hitting any bug.
