### ISSUE TITLE
ATO: separating test rate and set points

### ISSUE THREAD

**Issue by lironalm** [reef-pi/reef-pi#701]
in ATO for example, if you set the test rate to 180 seconds, it will check the sensor state every 180 seconds.
if it decides that the ATO pump needs to be turned on, it will test whether to turn it off in 3 minutes, not earlier.
i suggest testing at the set interval, but once decided to turn on, test every second to check if to turn off.

just a suggestion though.. :-)

**Comment by ranjib** [comment]
After giving this some thought I feel we dont need this if we can run ato with check interval much lower. I am running multiple ATOs at 1, 3 or 5 second check interval pretty successfully for serveral months now.
