### ISSUE TITLE
V2.2, dashboard shows single column even if 2 is selected

### ISSUE THREAD

**Issue by lironalm** [reef-pi/reef-pi#706]
V2.2, dashboard shows single column even if 2 is selected.
V2 was OK

**Comment by kevinmic** [comment]
I find the dashboard will show multiple columns if I refresh the page (ctrl+r) when I am on the Dashboard page. If I navigate away and back it is always a single column.

**Comment by ranjib** [comment]
@zekth could use your help here

**Comment by zekth** [comment]
I've tried to reproduce the problem but can't. Could you describe the flow of showing this problem? Which metrics are you using? On my dev env i only have the CPU chart usable.

**Comment by ranjib** [comment]
This is still a pain point and im frequently encountering this. Just refresh the UI  and 50% of times in shows all charts in a single column. @zekth let me know if you are looking into this. Else I'll get back to this

**Comment by spaelectronics** [comment]
I have this same problem using version 3.. Seems to only happen if using more than 2 rows.

**Comment by Simonv92** [comment]
Same problem on version 3.3.1, after some refreshes it goes ok. Tested on Firefox and Chrome

**Comment by ranjib** [comment]
I have encountered this sporadically . Generally this resolves if i resize window.
