### ISSUE TITLE
add an "inputs" status

### ISSUE THREAD

**Issue by lironalm** [reef-pi/reef-pi#707]
add inputs stats page or add a section at the "connection" section in order to debut inputs
(High / low, green / red..)

**Comment by ranjib** [comment]
hmm.. unlike outlets, we dont store the state of inlets , since its read on the fly, and does not make sense to store in the database. I can see the value in showing this information though. Let me think through how we can achieve this,.

**Comment by ranjib** [comment]
Closing this as we do not have a plan to work on this. Currently you can infer this information in the ATO or any other consumer module.
