### ISSUE TITLE
Suggestion: Add an ability to enable/disable timers

### ISSUE THREAD

**Issue by rryerson-ps** [reef-pi/reef-pi#711]
As a user it would be useful to disable and then re-enable timers in order to perform maintenance on the associated equipment.

**Comment by ranjib** [comment]
reef-pi does allow enabling/disabling timers. You can check the ui, theres a field name "enabled" that you can toggle to enable/diable the timer

**Comment by zekth** [comment]
Maybe duplicate of #724 

Closing.
