### ISSUE TITLE
Suggestion: Allow timers to run only during particular times of day.

### ISSUE THREAD

**Issue by rryerson-ps** [reef-pi/reef-pi#712]
As a user, it would be useful to specify when a timer starts, have it run it's own schedule, and then specify a time that the time stops for the day.

Example: I schedule my powerhead timer to turn on the powerhead at the 30 minute mark of every hour, run for 30 minutes and then shut off. However, I would like this to only happen between 8 am and 8 pm.

**Comment by kevinmic** [comment]
I believe this is already possible. The "day of month", "hour", "minute", "second" fields allow for "cron" like entries.  So in your case the "hour" should be "8-20".

https://godoc.org/gopkg.in/robfig/cron.v2

In each of the above fields you should be able to do things like
* (every hour)
*/2 (every other hour)
2,5,8 (2nd, 5th, and 8th hours)
2-14 (hours 2AM - 2PM)
