### ISSUE TITLE
Allow partial second duration for dosing pumps

### ISSUE THREAD

**Issue by kevinmic** [reef-pi/reef-pi#713]
In trying to fine tune my dosing pump I have found that adjusting the "power" level is neither intuitive nor linear when dosing multiple times a day.  Adjusting the time however is both intuitive and linear. I would like the dosing pump feature changed so that it allows for sub second dosing.

My goal is to dose 100 ml per day. Rather than dosing all at once I prefer to dose once per hour. This means I run the pump for about 5 seconds every hour. As I try and fine tune the pump I find that adjusting the "power" level does not produce linear results. I calibrated the pump at 100% for 60 seconds produced 56 ml.  I decreased the power from 100% to 90% and it dropped amount dosed to 54 ml (4%) change.  I decreased from 90% to 80% and once again the change was not linear. Each time I am having to run a 60 second calibration in an attempt to guess the power level that will produce the results I want. If however I were able to increase/decrease the time by partial seconds I believe the changes would produce both predictable and linear results. If in the future if I find that my dosing pump is slightly under producing or over producing all I have to do is adjust the time slightly and I can expect the amount dosed will change similarly.

I have experience in programming Java and have done a little Go. I would be happy to help with the work if someone could help with the desired design and finding my way around the code.

**Comment by ranjib** [comment]
This is because we are using/recommending DC motors for dosing pumps. Bulk of these issues will go away one we move to stepper motor based dosing pumps.
I think allowing sub-second duration is valuable. We can just accept float/real values in duration field (and still treat it as second) to support that.
On a side note, did you tried playing with dilution of your dosing liquid?

**Comment by kevinmic** [comment]
I have a smaller 30 gallon tank and need to dose 10 ml of calcium and alkalinity per day. Due to my own pi dosing project I started diluting my solution so 9 to 1 so would dose 100 ml instead of 10.  Further dilution would force me to either use a container larger than 1 gallon or fill the container more often.  (Currently lasts for about 1 month).

For the stepper motor dosing pumps do you have a source location for those? With my own pi doser I originally tried 3d printing a peristaltic pump to work with a stepper motor but kept struggling with having enough power in the motor to turn my pump. I eventually gave up and went to a dc motor.

**Comment by kevinmic** [comment]
#718

**Comment by kevinmic** [comment]
This has been merged.
