### ISSUE TITLE
Temperature history lost if pi is power cycled 

### ISSUE THREAD

**Issue by kevinmic** [reef-pi/reef-pi#715]
If I unplug my raspberry pi without turning it off, when I turn it back on all of the temperature history is lost.

If I power off the pi by going through the UI, when I turn it back on all of the temperature history is still there.

Why is a forced power cycle causing the reef-pi to lose temp history?

**Comment by ranjib** [comment]
reef-pi stores all stats in memory ring buffers and writes them to disk during normal shutdown. If its power down abruptly then you will loose the usage data.

**Comment by zekth** [comment]
Would it be a good idea to cron the writing on the disk of those informations? like every hour for example? (to not stress the sd card)

**Comment by theatrus** [comment]
I'd just not worry about all of the memory buffering we are doing. An average Linux system will be writing to disk every few seconds anyway (logs, journals, filesystem sync points, ext4 logs), scribbling telemetry isn't going to impact anything.

**Comment by ranjib** [comment]
@theatrus can you try changing this (from in memory to disk based stats retention) and share the perf data with us?

**Comment by ranjib** [comment]
Fixed by: https://github.com/reef-pi/reef-pi/pull/732
