### ISSUE TITLE
PCA9685 PWM Frequency wont change.

### ISSUE THREAD

**Issue by bigtroutpa** [reef-pi/reef-pi#721]
The pwm frequency of the PCA9685 will not change from 1500hz, no matter what frequency is entered in the setting box.

**Comment by MelanieT** [comment]
There are major issues with the PCA9685 driver. I have commit ready for PR but I need to find the time to test it on an actual PCA9685, I've only tested it against an ATTINY841 emulating a PCA9685 so far. PR will be forthcoming once i've tested with the actual chip

**Comment by ranjib** [comment]
@MelanieT you can raise the PR, i can run some field testing on my end with my test builds and report back you the results

**Comment by bigtroutpa** [comment]
This is fixed in the 2.3 release
