### ISSUE TITLE
dosing chart should show daily pump run time

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#725]
"the dashboard for dosing appears to keep a running time for each pump which starts on the date in which it first runs, it does not show a daily total. It would be very helpful to look at a historical account of each day’s total time for each pump. That way, if you were on vacation for a week you could look to see if there were any problems and if do when it may have occurr" - Jhollowell41 (R2R)

**Comment by zekth** [comment]
Do you have mocked data for this that i could use for Development purposes? I can handle this only if i have those data available.

**Comment by ranjib** [comment]
Fixed by: https://github.com/reef-pi/reef-pi/pull/732
