### ISSUE TITLE
API auto-documentation

### ISSUE THREAD

**Issue by zekth** [reef-pi/reef-pi#727]
As read on R2R

> Any chance you could share what did get written for documentation of API v2? I'm seeing some API v1 endpoints returning 404 though the module is enabled (and running).

It would be nice to implement Swagger v2 to the project to have documentation for the API. Reference:
https://github.com/go-swagger/go-swagger

**Comment by zekth** [comment]
I've worked on a dynamic generation of spec file with the Go side but unfortunately it does not work. Because the `path` part of the file is a map with dynamic members. Golang does not give the availability to use dynamic struct so Marshal / Unmarshal for yaml/json spec files is not possible.

Another idea is to make a check beetween the api.txt file generated by the `summarizeAPI` method and the spec file. When doing a release a check is done to ensure that the spec file is revelant of the real exposure of the api. Any thought?

At the moment i have no other idea to implement this specifications without making huge changes in the api.

**Comment by zekth** [comment]
Here is an example of implementation with go-swagger: https://github.com/ribice/golang-swaggerui-example

**Comment by ranjib** [comment]
I the idea is to just document the v2 API? or to also generate client code?
I would prefer to punt this. I can document the API, if theres enough interested, I have the client code done already, I am not very happy with swagger generated client code :-( . But if theres more reasoning then lets hear it out.
I am also worried about this making the learning curve for new developer higher..

**Comment by zekth** [comment]
The idea was to generate to document of v2 api using open api v3 standard with scanning of the code. But after few tries it's really a pain and too intrusive. Using generated client code is not even thinkable in our case.

The point here is to write the open api spec file to be used by a middleware which filters the queries througth the api and also to make the automatic documentation of it. Will push this today.

**Comment by zekth** [comment]
I've found this project which is not really intrusive in our case: https://github.com/getkin/kin-openapi
I'll give a try after the redaction of the current api specs.

**Comment by ranjib** [comment]
@zekth  I am planning to expand the minimal go based middleware for this. Will update this thread soon as I have something concrete

**Comment by ranjib** [comment]
We have the basic plumbing for generating documentation good enough for the website. I think we can extend this to cover openapi 3.0 or any other compliant system (also upgrade the renderer to a template based implementation) if there are benefits(client-side code auto-generated)
