### ISSUE TITLE
Add button to lights for quick on/off

### ISSUE THREAD

**Issue by DragonPrincess78** [reef-pi/reef-pi#729]
When working in the fish tank after dark  or for quick checks it would be very convenient to have the ability to quickly switch the lights on or off without having to resort to configuration and overriding the schedules and/or cycle times.
Said button might be available at the dashboard diagram (most convenient) or with at the configuration page, similar to the doser calibration.

**Comment by ranjib** [comment]
You can directly switch on /off equipment, even if they are on timer. Timers should interfere only during the exact moment when they need to take an action. If the equipment is under a temperarure or ato controller, then define a macro to turn them on/off , as you have to combine both disabling/enabling the temeperature or ato controller and then turning on/off the target equipment. In any case, this should be possible with the existing features

**Comment by DragonPrincess78** [comment]
Well, that's for equipment only, but not possible for lights (PWM jacks). Switching between modes deletes the previous times and settings there.

**Comment by ranjib** [comment]
Got it. Agree, this has been a pain for me as well. I'll triage this once our current major feature/bugfix work backlog is done

**Comment by ranjib** [comment]
Getting back to this, now that the pwm frequency issues are sorted out :-) . I am thinking of doing this along side custom pwm profile thing, and ship it as next set of light improvements.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/854 this will be out in 3.0 release

**Comment by sfgabe** [comment]
Will this be available for dosing pumps too?
