### ISSUE TITLE
Timer duration and forced power cycle has unexpected behavior

### ISSUE THREAD

**Issue by kevinmic** [reef-pi/reef-pi#731]
I setup a timer to turn on equipment "A" and then turn it off after a given duration. While the timer is running the duration I force power cycle the pi. When the pi turns back on it will turn back on equipment "A" and run it for a duration longer than the original duration.

Here are my 3 test cases.
1. 60 second timer duration. After the timer has been running for 7 seconds I force power cycle the pi. After reef-pi loads up it turned on the equipment for 193 seconds.

2. 20 second timer duration. After the timer has been running for 7 seconds I force power cycle the pi. After reef-pi loads it turned on the equipment for 105 seconds.

3.  20 second timer. After the timer has been running for 7 seconds I power off the pi. After 25 seconds I turn it back on. After reef-pi loads it turned on the associated equipment for 120 seconds.

My desired behavior is that it leaves the equipment off rather than attempting to continue the duration.

**Comment by MelanieT** [comment]
Could this be caused by the fake_hwclock driver, being overridden only later on by ntp? This is probably a case for running ntpdate against a reasonably high stratum time server from /etc/rc.local.
As for resuming vs. not resuming, both can be harmful, depending on the equipment. Should probably be an option.

**Comment by ranjib** [comment]
I'll try to reproduce this. The extended duration should not be impacted by ntp, as system time only impacts the start/trigger time, the run duration, once time is triggered, should not be impacted by ntp/system time as it relies on tick based logic (thats what I am assuming). I'll test this out on my end. 
@kevinmic whats the schedule you are using? I understand the duration of timer is 20s, but how frequently ? Is it an hourly or every minute job? If possible share a screenshot , it will help me easily reproduce the issue.

**Comment by kevinmic** [comment]
For the schedule I was leaving everything default and setting the minute to 1 + current minute. I would save and then it would execute in the next minute.  So year=*, day=*, minute=23, second=0, action=TurnOn, andThen=TurnBackOff, after=60 seconds.

**Comment by ranjib** [comment]
@kevinmic super sorry for getting back late. I am bit conflicted on this, as a force power reboot will complicate timers with revert features. Currently, this is as expected risk. Its not good, but its known, and my recommendation will be to use two separate timers to on/off when the revert duration is large. If you can think of a better way to address this (or just remove the revert feature from equipment target all together) please reopen this issue. We are redesigning the ui and some backend logic in 3.0
Thank you so much for taking the time and providing feedback
