### ISSUE TITLE
Timer Day of Week

### ISSUE THREAD

**Issue by kevinmic** [reef-pi/reef-pi#733]
The timer feature has the ability to schedule reminders, but I cannot do this on a weekly basis. I would like to say "Every Wednesday send me an email reminding me to do a water change". The field is available in cron but right now is set to "*" in timer/job.go

**Comment by zekth** [comment]
This is possible and interesting example. Not really hard to achieve on backend side but we have to find a go way to include this feature in the GUI.

**Comment by TheMaxik** [comment]
> This is possible and interesting example. Not really hard to achieve on backend side but we have to find a go way to include this feature in the GUI.

how about a (radio-)button oder slider to switch?

**Comment by ranjib** [comment]
This has been implemented in the backend. We are yet to finish up the frontend/UI part. Im closing this as we have separate issue to tack this,. https://github.com/reef-pi/reef-pi/issues/830
