### ISSUE TITLE
Suggestion:  Telemetry GUI improvements

### ISSUE THREAD

**Issue by DaveCBr** [reef-pi/reef-pi#737]
Please make both the AdafruitIO and Email passwords stick.  It is both difficult and frustrating to continuously need to insert both fields when simply attempting to adjust something on that tab.  It gets even more difficult concerning email when you have two step verification implemented with the provider.

**Comment by ranjib** [comment]
I dont have a very easy answer to this, but I do understand this is not an acceptable behavior, let us discuss on whats the best practice

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/issues/783

**Comment by DaveCBr** [comment]
I see that this was closed.  Actually the issue was not fixed in 3.0.  Passwords still do not stick.
