### ISSUE TITLE
Conditional Actions

### ISSUE THREAD

**Issue by kevinmic** [reef-pi/reef-pi#740]
I would like to have actions taken based on conditions in/around my tank
A couple examples - 
1. If there is water on the floor. Send me a notification
2. If the water in my FreshWater reservoir is low. Send me a notification.
3. If my salt water reservoir is low, Turn off salt water reservoir pump.

One way to do this would be to add Conditional statements to a "Timer". The timer would only execute the action if the given condition is met. Such as "If InputPin-1 is ON then ..."

**Comment by ranjib** [comment]
You can do pretty much all of this with the ATO module. By setting the notification threshold same as check interval

**Comment by ranjib** [comment]
bump.

**Comment by kevinmic** [comment]
I will attempt this with the ATO and open a new ticket if I find anything I can't do.
