### ISSUE TITLE
[Request] Driver pin selection improvement

### ISSUE THREAD

**Issue by zekth** [reef-pi/reef-pi#750]
As @theatrus said
```
It would be nice to not have to specify pins, the driver/hal model can return all known pins
```

So there is 2 part of feature request. 

- Make the API returns the available pins for the selected driver.
- Make the UI take those new informations while configuring inputs

**Comment by ranjib** [comment]
I would love to know how this will be used? Currently we have what is offered by hal.Metadata

**Comment by ranjib** [comment]
@zekth are you planning to work on this? If not lets punt it post 3.0

**Comment by zekth** [comment]
> @zekth are you planning to work on this? If not lets punt it post 3.0

ATM not really but i can tackle it. Also is API providing those infos already?

**Comment by ranjib** [comment]
The HAL abstraction provide methods for this but theres nothing that exposes this information in some structured fashion via /drivers api. Lets tackle this after 3.0 release

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/841
