### ISSUE TITLE
[Request] get ph data from serial?

### ISSUE THREAD

**Issue by krheigh** [reef-pi/reef-pi#766]
I think the possibility of pulling ph data from a serial port eg "/dev/ttyACM0" would be an advantage. I and probably many more use arduino to measure ph. it is a simple istallation via usb
and some code on arduino. and way cheaper than the Atlas Scientific kit

**Comment by ranjib** [comment]
Is this based on any popular opensource project? The core reef-pi software is not aware of device details, it uses Hardware Abstraction Layer (reef-pi/hal) for pwm, analog reading etc, and a set of drivers (reef-pi/drivers) hides the implementation details and just provide HAL compatible interfaces. If this is a popular opensource driver, we can write a hal driver for this and reef-pi will be integrated with it just fine. But if this is just a one off thing, it might be harder to maintain / have  a decent user base to even test this

**Comment by ranjib** [comment]
@krheigh closing this for the time being as i am not planning to work on this. Let me know if you have any specific driver in mind, happy to reopen it if needed
