### ISSUE TITLE
(half)Hourly schedule for light channels

### ISSUE THREAD

**Issue by EdelHert** [reef-pi/reef-pi#770]
First of... awesome program! Took some time to get everything up and running (but was more hardware related), but works like a charm.

I am using this to create a sunset/sundown light effect, but find the 2 hourly brightness settings a bit too long. E.g. if I want to use the red light for a sunset I have set it from 0 at 6pm to 70 at 8pm and back to 0 at 10pm, but this way it takes 4 hours in total, while it would be nice to set it more specific, so hourly of maybe even every 30 minutes. 
I'm sure this is possible to implement, but don't know it that's a lot of work for you as developer...

Anyway, to me that would be a great feature.
Thanks again.

**Comment by EdelHert** [comment]
Oke, think I got it working, at least in the developer package.. just don't seem te get the 'make deb' command to work, but that's probably just on my system

**Comment by ranjib** [comment]
I want to support a meta feature, arbitrary pwm profile to allow doing something like this.
https://github.com/reef-pi/reef-pi/issues/659

**Comment by ranjib** [comment]
We'll track progress of this as part of the main customizable pwm profile work
