### ISSUE TITLE
ATO disable leaves pump in a running state.

### ISSUE THREAD

**Issue by kevinmic** [reef-pi/reef-pi#776]
Setup ATO with run every 1 minute, disable after 2 minutes.  Pull water level sensor out of water for 5 minutes. Put water level sensor back in the water.

What I have observed is that the ATO gets disabled but the pump is left running.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/781

**Comment by ranjib** [comment]
This is fixed in master (3.0.0-alpha-2 onwards and 2.4). Let me know if you still encounter this
