### ISSUE TITLE
Doser does not work at 100% speed

### ISSUE THREAD

**Issue by clownfish44** [reef-pi/reef-pi#779]
Title says it all.

**Comment by trackerit1** [comment]
> Title says it all.

What kind of tests have you done? what voltage do you have the pwm output connected to your doser

**Comment by kevinmic** [comment]
If you are using the PCA9685 then this is a known issue in reef-pi. I believe it has been fixed in the master branch. Not sure if there has been a release for it yet.

**Comment by Ranthalion** [comment]
This seems like the same issue I addressed in https://github.com/reef-pi/drivers/pull/19.

**Comment by trackerit1** [comment]
> This seems like the same issue I addressed in [reef-pi/drivers#19](https://github.com/reef-pi/drivers/pull/19).

yes, is the same issue, i have the version 2.3, when you set 100% dont work. but 99% yes work

**Comment by ranjib** [comment]
https://github.com/reef-pi/drivers/pull/25

**Comment by ranjib** [comment]
This is fixed in master (3.0.0-alpha-2 onwards and 2.4). Let me know if you still encounter this
