### ISSUE TITLE
Change Email Alert to Address without rentering password[Request] 

### ISSUE THREAD

**Issue by kevinmic** [reef-pi/reef-pi#783]
If I want to change the email address that receives alerts I have to reenter my email password. I used this feature with gmail and generate app specific passwords. I have no idea what the password I used was and have to go generate a new one when changing the email address.

Changing the email address does not happen very often but is very useful when going on vacation and want to send the emails to the person watching your tank.

**Comment by ranjib** [comment]
I think this is a ux bug :-( . Not an enhancement . Let me think about how can I address this, currently we dont return back any password from reef-pi via API, which is the root of this bug.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/issues/737

**Comment by ranjib** [comment]
Closing this as we are already tracking it on 737
