### ISSUE TITLE
Allow multiple email recipients for email alerts[Request] 

### ISSUE THREAD

**Issue by kevinmic** [reef-pi/reef-pi#784]
When going on vacation it would be nice to be able to enter a second email address to receive alerts so that I still get alerts but that the person watching my tank would also get alerts.

**Comment by ranjib** [comment]
Agree, this is a nice to have feature.

**Comment by ranjib** [comment]
This has been implemented in master. Will need more testing, but its feature complete and will be out with 3.0 release
