### ISSUE TITLE
reef-pi showing # instead of text

### ISSUE THREAD

**Issue by GiuseppeYoghi** [reef-pi/reef-pi#789]
reef-pi showing # instead of text 

**Screenshots**
![Cattura](https://user-images.githubusercontent.com/43232818/59967836-7119dd00-9530-11e9-96f0-ea154cd7fede.JPG)

 - Device Pi3 b+
 - rasbian stretch
 - reef-pi version 3.0.0-pre-alpha-2
 - Browser chrome

**Comment by badhabit1** [comment]
ive never seen this and i was the worst without having knowledge of
programming. have you deleted and tried to reinstall?

**Comment by badhabit1** [comment]
ahh i just looked and im running 2.0 i wonder if im missing things? i would
try 2.0 its working great on 2 tanks for me currently.

**Comment by zekth** [comment]
Oo seems like there is missing translations in there. I'll try to adress this.
