### ISSUE TITLE
Got this error when I want to help add Chinese support.

### ISSUE THREAD

**Issue by chendx79** [reef-pi/reef-pi#797]
I added a zh.csv in front-end/assets/translations, inserted a line in it:
Key,Translation
and saved the file.

Then I ran "npm run translations:sync" and got followed error.

➜  reef-pi git:(master) ✗ npm run translations:sync

> reef-pi@1.0.0 translations:sync /Users/Derek/Documents/reef-pi
> node ./build/translations/csv-sync.js

/Users/Derek/Documents/reef-pi/build/translations/csv-sync.js:5
const MasterTranslations = fs.readFileSync(`${PATH_CSV}${masterFile}`, 'utf8')
                                           ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 18.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "translations:sync"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! reef-pi@1.0.0 translations:sync: `node ./build/translations/csv-sync.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reef-pi@1.0.0 translations:sync script 'node ./build/translations/csv-sync.js'.
npm ERR! This is most likely a problem with the reef-pi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build/translations/csv-sync.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls reef-pi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Derek/Documents/reef-pi/npm-debug.log

**Comment by zekth** [comment]
Ew. Could you provide the zh.csv file? or a link to your branch? I'll look into this.

**Comment by chendx79** [comment]
[zh.csv.zip](https://github.com/reef-pi/reef-pi/files/3354153/zh.csv.zip)

**Comment by zekth** [comment]
there is nothing in it :/

**Comment by chendx79** [comment]
[zh.csv.zip](https://github.com/reef-pi/reef-pi/files/3354488/zh.csv.zip)
I think I misunderstood the guide. I copied the keys from en.csv and translated some translations. But the error didn't change.

**Comment by zekth** [comment]
Ok there is an encoding issue. I'll work on this. Also you don't need to copy. Just create an empty zh.csv file with the headers `Key | Translation` and run `csv-sync`. The file will be filled.

**Comment by chendx79** [comment]
I still got the same error. I translated all keys and requested a pull request. Please check it. You might need do some relevant change in your menu.

**Comment by zekth** [comment]
Just tried it from the sources, not experiencing any issue. Maybe we can close it?

**Comment by ranjib** [comment]
@chendx79 what version of node and npm you are using?

**Comment by chendx79** [comment]
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
@ranjib You just don't read the error message. :D

**Comment by chendx79** [comment]
![reef-pi](https://user-images.githubusercontent.com/7203022/60705631-2ccc0b00-9f3a-11e9-88db-a7e9d8b37608.png)

**Comment by zekth** [comment]
Node 12 is not stable, we use node 8 in reefpi.

**Comment by chendx79** [comment]
I checked the version history of nods.js. It looks like my node.js 0.12 is a very old one. I update it to a relatively new one v10.16.0 and the error disappears.

**Comment by zekth** [comment]
Could we close it so?
