### ISSUE TITLE
Temperature probe not found after update

### ISSUE THREAD

**Issue by BraddBice** [reef-pi/reef-pi#806]
I updated to the new beta release from 2.4 and now reef pi won't find my temp probe in pi/sys/bus/w1/devices.  It was working just fine before.

I reinstalled 2.4 and am still unable to get it working.  No wiring has changed so I can't figure out why it isn't showing up.

Any ideas/help would be appreciated.

Thanks

**Comment by CaseyWagner** [comment]
Did you enable the Equipment subsystem and then the Temperature subsystem?
It was driving me bonkers trying to figure out why I no longer had temp after upgrading and it turned out all I needed to do was check Equipment first  :)

**Comment by BraddBice** [comment]
Yes, I am starting to think it is the sensor itself or the resistors keep going bad. I am about to give up on it all together. 

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 1, 2019 at 5:17 PM, Casey Wagner<notifications@github.com> wrote:   
Did you enable the Equipment subsystem and then the Temperature subsystem?
It was driving me bonkers trying to figure out why I no longer had temp after upgrading and it turned out all I needed to do was check Equipment first :)

**Comment by ranjib** [comment]
if the sensor is not detected by raspberry pi/raspbian then reef-pi will not be able to do much. This can happen due to sensor going bad, but what we have seen most is some connection being loose or wrong or shorted. I'd suggest you double-check your audio connector, plug/unplug sensor etc. 
You can check if pi is detecting the sensor or not by 
```
ls /sys/bus/w1/devices/
```
and you should see a device , with name starting with 28-

You can almost always confirm the sensor detection is having some issue using the dmesg command. It should show several kernel error/warning logs mentioning w1 bus.

**Comment by BraddBice** [comment]
I had it working just fine for 3 days and then it suddenly stops. I am not using an audio connector. I am using a breadboard, sensor, and resistor along with the raspberry pi. 

Sent from Yahoo Mail on Android 
 
  On Sat, Aug 3, 2019 at 2:10 AM, Ranjib Dey<notifications@github.com> wrote:   
if the sensor is not detected by raspberry pi/raspbian then reef-pi will not be able to do much. This can happen due to sensor going bad, but what we have seen most is some connection being loose or wrong or shorted. I'd suggest you double-check your audio connector, plug/unplug sensor etc.
You can check if pi is detecting the sensor or not by
ls /sys/bus/w1/devices/

and you should see a device , with name starting with 28-

You can almost always confirm the sensor detection is having some issue using the dmesg command. It should show several kernel error/warning logs mentioning w1 bus.

**Comment by ranjib** [comment]
@BraddBice I think this is not a reef-pi software issue. The temperature sensor is notorious for unstable experience for a varied set of reasons. Bad probe, bad connections, wrong circuitry , interference with other equipment, and long length of wires are few of those. I think in your case its either a bad probe or you have some equipment thats interfering with it. Its hard to pin point without doing some experiement (like use the probe outside tank or swap it with another probe etc). In past three years we have troubleshoot numerous such issue, though they are frequent for new setup, once dialed in, they are fairly reliable. If you are in reef2reef please reach out and we can help you out with end to end testing/troubleshooting. There are folks across freshwater and local reef forums that may be easier to use as well.

We use this issue tracker exclusively for the software side of things. Hence I am closing this
