### ISSUE TITLE
Implement ph based control ui

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#822]
Similar to the temperature module, ph sensors can now control a set of equipment that will be turned on/off when ph is outside a range (min, max). 
Temperature and ph module now share a common homeostasis library for the control mechanism, and it can take either equipment or macro id for switching. A boolean homestasis.IsMacro property is used for detecting where the swithing target is macro or equipment. Check controlller.HomestasisConfig, temperature.TC, phprobes.Probe for detail.

**Comment by ranjib** [comment]
@zekth

**Comment by zekth** [comment]
So ph control UI will be a mimic of the temperature one now right?

**Comment by ranjib** [comment]
Yes. And eventually the ATO ui as well. They all now uses a common library called homestasis.

**Comment by gminton86** [comment]
How can I test this new feature out?? I would love to get my calcium reactor up and running and need this for it to work.

**Comment by gminton86** [comment]
By the way thank you for all your hard work Ranjib and others I really like this system and have been talking other friends into getting reef tanks and using this setup to make it less of a hassle to own.

**Comment by ranjib** [comment]
@gminton86 :hugs: 
Wait for 3.0 release if you want a stable bug free experience. If you want to help us test and willing to take some risk, try the next beta release. these features will be present in the next 3.0  beta release.

**Comment by gminton86** [comment]
I will help you out and test for bugs I wish I knew how to write code and I would help you out on that aspect. If there is anything you need me to do, or can think of that doesn't involve any coding but is a time killer to you and could easily be done by someone like me then let me know and I will take care of it for you. I'll download 3.0 beta as soon as its released. Thanks!

**Comment by gminton86** [comment]
I also have oscilloscopes and lots of equipment and other tools for the hardware side of things so if you need something in that area? Let me know Ranjib!

**Comment by Ranthalion** [comment]
[Planned UI layout](https://ninjamock.com/s/9SWHKTx)
![image](https://user-images.githubusercontent.com/1632746/66716592-6021ff80-ed9d-11e9-9cff-ca3c0d5b9ab0.png)
