### ISSUE TITLE
Cannot reset after timeout alert

### ISSUE THREAD

**Issue by lironalm** [reef-pi/reef-pi#825]
After the ato pump is disabled because of timeout settings,  there is no way to reset it back.
Parameters shows ato as disabled,  but when editing the settings to "enable" it goes back to disable after saving. 
It seems like the timeout is not being reset. 
V2.5

**Comment by lironalm** [comment]
Just confirmed that only deleting the ato program and re configure it works

**Comment by zekth** [comment]
And you got no error on the log in UI or server when trying to enable it? will investigate
