### ISSUE TITLE
Reactive dosing / dosing calculator [Enhancement] 

### ISSUE THREAD

**Issue by stvnmbr1** [reef-pi/reef-pi#827]
**Is your feature request related to a problem? Please describe.**
This would lean on log to work succesfully. maybe with notifications

Dose X ml / X times per day / at a given time,
Calculated by desired values, measured values, how many ppm + the used products are, how many times per day 
or using the PH sensor with ph - and + products

**Describe the solution you'd like**

eg.
KH measures 8, 1 week before 8.5, desired 8.5
1. calculate drop -> 0.5 / 7 days
2. products  300ml= +1°
3. calculate products needed -> 0.5 = 150ml
4 calculate dosing -> 150 / 7 (and round) ->  = 21 ml / day
 ---->>> dosing set to 8 dosing / day -> 21ml/8 = 3ml / dose

set this value for selected dosingpump

**Describe alternatives you've considered**
setting manually

**Comment by ranjib** [comment]
@stvnmbr1 this will be definitely a good addition. The current UI/UX for dosing is not optimal, I realize, its based on speed (pwm) and time and in reality we really dont think like that. 
That said, we are heads down on 3.0 release, and will be pretty busy with bug fixes for next couple of months. I'll surely pick this up soon after 3.0 release.
