### ISSUE TITLE
{"error":"Failed to reboot reef-pi. Output:. Error: fork/exec /bin/systemctl: cannot allocate memory"} | HTTP 404

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#836]
Getting Error when trying to reboot after changes 

{"error":"Failed to reboot reef-pi. Output:. Error: fork/exec /bin/systemctl: cannot allocate memory"} | HTTP 404

 - Device [e.g. Pi3]
 - reef-pi version [e.g. 2.4]
 - Browser [firefox]

**Comment by ranjib** [comment]
Its due to memory leak i think. You have to ssh and manually reboot for the time being. I'm experiencing this in few cases as well. We'll update this ticket soon as I work on a fix (for the memory leak)

**Comment by sfgabe** [comment]
I'm also getting this error on my new build. I've set it to reboot every night which partially takes care of the problem, but it reoccurs some time during the day. It seems to be logging and displaying sensors correctly, but none of the web interface buttons work (reboot, take picture, change settings).

**Comment by gminton86** [comment]
![more info](https://user-images.githubusercontent.com/22088453/68268946-f1476780-0025-11ea-9471-e5438d359928.JPG)

**Comment by gminton86** [comment]
just got this error again and it looks like this

**Comment by ranjib** [comment]
@gminton86 Can you share what type of modules you are using? ATO or temperarture or ph or all of them? And what stats retention values you are using.  Does reducing the default values help (its under telemetry settings)?

**Comment by ranjib** [comment]
Closing this as I am not hitting this with my builds. Feel free to reopen if this issue is still present and share the details.
