### ISSUE TITLE
Add support for USB 10-key (or other physical buttons) to initiate macros

### ISSUE THREAD

**Issue by burningbaal** [reef-pi/reef-pi#848]
**Is your feature request related to a problem? Please describe.**
Many people don't want to pull out a computer to interact with this and would benefit from allowing a physical button to initiate things like 'feed mode' or an auto water change macro. 

**Describe the solution you'd like**
Allow a USB 10-key to be plugged into the RPI, or some other physical button (10key is nice because you get 10 things in one), allow a MacroInitiator type class to be listening to keystrokes from that 10key (or other physical button) such that each macro can be mapped to a physical key. Thus when someone presses the physical key, the macro begins. Perhaps allow enter key as an uprompted confirmation (or press button twice within 5 seconds in order to actually happen)

**Describe alternatives you've considered**
An Android/apple app could get nearly the same effect, but pulling up the browser, logging in, navigating to the macros page...kinda a lot for just starting feeding.

**Additional context**
I'm happy to participate in the coding, but don't know go (I'm a C# dev). Also, I expect this is triaged post-3.0 release

**Comment by burningbaal** [comment]
or perhaps something like this, but it's PS/2
[KB-17CABLE](https://www.barcodegiant.com/logic-controls/part-kb17cable-psm.htm?aw&adtype=pla&CAWELAID=120087310000012355&utm_medium=pla&utm_campaign=Shopping-Accessories&gclid=Cj0KCQjwivbsBRDsARIsADyISJ9tL_TLoZElEbhXEr2Eej2qY9-ScHkjMJug3AGYDP6IDX_WQFKlja8aAnJQEALw_wcB&gclsrc=aw.ds#tab_additional_tabbed_contents)

**Comment by stvnmbr1** [comment]
I think you could just use an inlet with button attached, controlling the macro. If i'm not mistaking activating macro with an action or sensor state is coming in the future and also gpio expander.

sorry to mingle in but i was just scrolling through the repo :)

**Comment by Ranthalion** [comment]
USB Keyboard is an interesting idea.  I'd also like some physical buttons to interact with reef-pi for Feed and Water Change.  I think it could be possible for reef-pi to monitor std in, but I'm not sure if an ssh connection would interfere.

Inlet doesn't quite work since it is not interrupt driven.  Since it is polling based, the check interval would have to be pretty tight.

**Comment by burningbaal** [comment]
Ssh is a definite liability. I wonder if we could relegate the serial bus away from stdin and accept byte data more directly... Though I'm not used to working at that low of a level, and quite green with Linux (I'm a .net/windows/desktop Dev)

**Comment by ranjib** [comment]
I think a physical control mechanism can be implemented externally using the api. I am unsure about this specific 10 key usb device. I would prefer to start with something simple and common. Like  a common spst button for feedmode/macro and then extend from there. This can  be a separate repo and language.

I have a repo sitting on my laptop called "phys" , which I had prototype way back in 2017. We can start with that in post 3.0, unless there any takers by then.  Thoughts?

**Comment by burningbaal** [comment]
My primary thought in the 10key (or other byte-data input) was that it gets multiple buttons without claiming a bunch of GPIO space; it seems those USB slots are a bit less utilized than the GPIO, so it made some sense. But certainly the implementation is more straightforward with a GPIO interface due to the stdin conflict potential. I think it makes a lot of sense to start with a simple SPST button and get that working for at least two buttons, then it can be extended later to include a byte-type data input.
I could take some of a look at it, but I'll have to start by familiarizing myself with the codebase, particularly around the macros...obviously. I'll try to read/understand a bit, but welcome anyone else to contribute (post 3.0 release)
