### ISSUE TITLE
Integrate Alexa (4.0 milestone) [Feature] 

### ISSUE THREAD

**Issue by stvnmbr1** [reef-pi/reef-pi#850]
**Creating an Alexa skill for reef-pi**

Be able to ask alexa for latest stats from reef-pi equipment, in a later state be able to activate macros like feeding time, cleaning time, ...

I will start with the ability to retrieve stats first, in a later stage controlling macros/equipment and try to cover the entire API.

As of now the skill is hosted in an AWS Lambda instance, which requires amazon & AWS developer accounts(and CC credentials).
In a later stage I would like to host the Lambda instance on reef-pi to handle requests (easing end-user setup as no additional AWS lambda setup would be needed. API needs to be accessable through internet so Auth will be needed.

**Additional context**

Created a repo hosting progress so far.

Any input on what you would like Alexa to be able to do is welcome.

**Comment by ranjib** [comment]
@stvnmbr1 open up your repo for public view, nothing to worry in this openwork :-), we all are learning and others can help you better in that way.

For context, @stvnmbr1 is working on a nodejs based alexa skill integration.

**Comment by stvnmbr1** [comment]
https://github.com/stvnmbr1/Reelexa

seems to be public already ;) first time using this to upload stuff so let me know if it isn't.

**Comment by stvnmbr1** [comment]
@ranjib could you give me an overview of what you want to be able to ask alexa ?

Overviews with details like pin are covered with 3.0 release in mind. Abilitity to run a macro by giving the name to alexa works with some naming kinks but i'll get that fixed eventually.

Since I don't use reef-pi on a tank / real setup, you or someone else could provide more info

**Comment by stvnmbr1** [comment]
switching to MQTT, also new for me but looks promising.
gives support for google home next or iftt or anything that can use MQTT.
Lightweight (and secure through tls, username, password and cert), pretty simple setup for endusers and opens a lot of doors to IOT.

You could eg. light up a hue bulb in red color when something is wrong or soothing blue when all is ok fairly easy. Or control smartoutlets ;)

**Comment by stvnmbr1** [comment]
depends on #999 for further progress
