### ISSUE TITLE
Update lighting ui for 3.0

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#859]
In 3.0 reef-pi lighting is going through a major overhaul. There will be a top level enable/disable button for every light which will add or remove the light from reef-pi's control (not equivalent to switch off). Each channel can be either in manual (a fixed intensity) or profile mode. In profile mode user get to choose one profile among a set. Each profile has their own configurartion (e.g. start time, end time, max intensity, special dates etc ).

- Remove active low/high option from light. Its been moved to jack
- Remove unused field "start"
- Add top level toggle button to enable/disable light.
- Add manual vs profile mode for every channel
- In Manual mode user gets to set a fixed intensity for the channel. Exactly same as manual profile in 2.0
- In profile mode, user get to choose a profile among: auto, diurnal, lunar, random, arbitrary interval,

**Comment by ranjib** [comment]
@zekth can you help us with this?

@Ranthalion review please.

**Comment by zekth** [comment]
I can help for sure. So about the pinning, if i setup my env in dev mode i declare an equipment on pin 1 right? Last time i've tried it doesn't seem to work on my Windows env. May i try on Mac?

**Comment by Ranthalion** [comment]
@zekth I am also unable to set an outlet to GPIO1.  Even though we're not running on the actual hardware, I think GPIO 1 is reserved for i2c communication.  I recommend starting with GPIO 5 since since the the lower pins are i2c and 1 wire.   

https://github.com/reef-pi/rpi/blob/master/hal/gpio.go lists the pins available for gpio.

**Comment by Ranthalion** [comment]
I would recommend addressing lunar, random, and arbitrary interval profiles as separate issues.  The UI for lights is a bit complex, so an incremental approach to implementation and delivery could make it easier to make sure we're ready in time for next release.  
I think the first step should be to add the toggle and make the needed updates for the existing fixed, auto, and diurnal profiles to work.

**Comment by ranjib** [comment]
Here are the previews of the key profiles. Most profiles have a given time span (start and end) and return zero ouside that span. Most profiles inherit min and max bounds from the channel's setting and will return values accordingly.
- Fixed: Generates a fixed intensity for a given time span. 0 outside that time span
Input:
```json
{
  "start": "15:04:05" ,
  "end": 15:04:05",
   "value": 12
}
```
Will generate:
<img width="527" alt="Screen Shot 2019-10-20 at 11 40 01 PM" src="https://user-images.githubusercontent.com/316306/67182044-1b94f600-f393-11e9-9e37-0b7a676ea8b4.png">
Theres not much use of fixed profile. It can be  useful in constructing more complex profiles.

- Interval: For a given time span, it allows user to define a set of intensities with at fixed time interval in between them.  This profile can be used to build reef-pi 2.0 style two hour spaced intensity values.
Input:
```json
{
"start": "09:30:00",
"end": "16:30:00",
"interval": 3600,
 "values": [11, 20, 30, 40, 50, 60, 30,12 ]
}
```
Will produce
<img width="614" alt="Screen Shot 2019-10-20 at 11 51 56 PM" src="https://user-images.githubusercontent.com/316306/67182763-b2ae7d80-f394-11e9-8b7c-2a1682e7b244.png">

- Sine: For a given time span sine profiles create a sine curve (normal sun light)
Input:
```json
{
"start": "09:30:00",
"end": "16:30:00"
}
```
Will produce:
<img width="607" alt="Screen Shot 2019-10-20 at 11 59 00 PM" src="https://user-images.githubusercontent.com/316306/67183144-9f4fe200-f395-11e9-925c-fec50e3c45c9.png">

- Diurnal: Very similar to sine, except uses dual cubic functions to generate an exponential ramp-up to max intensity. And similar ramp down. Geared for maximum intensity with a smooth transition.
Input:
```json
{
"start": "09:30:00",
"end": "16:30:00"
}
```

<img width="523" alt="Screen Shot 2019-10-21 at 12 03 44 AM" src="https://user-images.githubusercontent.com/316306/67183461-5d736b80-f396-11e9-8a85-5220d86b2f83.png">

Will produce:

- Random: Generates random intensities for a given time period.
Input:
```json

{
"start": "09:30:00",
"end": "16:30:00"
}
```
Will produce:

<img width="511" alt="Screen Shot 2019-10-21 at 12 36 54 AM" src="https://user-images.githubusercontent.com/316306/67185811-821e1200-f39b-11e9-91a0-725103cc3601.png">

- Lunar: Attempts to mimic moonlight by running daily sine profile with the maximum intensity varying each day leading to new moon after every 27th day. 
Example config:
```json
{
"start": "22:30:00",
"end": "5:00:00",
"full_moon": "Mar 13 2019"
}
```
will produce, 3 months values
<img width="940" alt="Screen Shot 2019-10-21 at 12 46 22 AM" src="https://user-images.githubusercontent.com/316306/67186345-c65de200-f39c-11e9-98e7-5ab28705b235.png">
WIth a a typical daily cycle like a sine curve
<img width="769" alt="Screen Shot 2019-10-21 at 12 48 58 AM" src="https://user-images.githubusercontent.com/316306/67186395-dc6ba280-f39c-11e9-88d3-ecd7e39d05e1.png">
 

- Composite: An ordered array of profiles (sine, fixed, diurnal, random, interval) for a specified duration (in seconds) with each sub profile having their own min/max values. Example:
```json
{
    "profiles":[
      {"type":"diurnal", "span":6600, "min":13, "max":100},
      {"type":"fixed", "span":1500, "config":{"value":13}},
      {"type":"sine", "span":3800,"min":20, "max":60},
      {"type":"fixed", "span":1000, "config":{"value":20}},
      {"type":"random", "span":4100, "min":10, "max":50},
      {"type":"fixed", "span":1000, "config":{"value":23}}
    ]
  }
``` 
will produce:
<img width="691" alt="Screen Shot 2019-10-21 at 1 08 09 AM" src="https://user-images.githubusercontent.com/316306/67187562-52710900-f39f-11e9-98fb-e2bad87ba193.png">

**Comment by zekth** [comment]
Could we add thresholds for the random? Like random at 70% with a threshold of 10%, so max would be 80% and min 60%, also adding the parameter of max ramp up? Like 5% per 30min?

**Comment by ranjib** [comment]
Yes.  Channel minimum and maximum will be propagated to random profile

**Comment by Ranthalion** [comment]
Here's a proposed mock up of the Light UI.  I'm not sure about the Interval profile, but the intention is to allow the user to dynamically add and remove interval points and automatically calculate the interval value.

![image](https://user-images.githubusercontent.com/1632746/67820821-22a5bd80-fa91-11e9-9a5e-5b45d8a73bff.png)

This is the Manual/Auto control modal.  It allows to switch all channels between manual and auto. 
![image](https://user-images.githubusercontent.com/1632746/67820877-5da7f100-fa91-11e9-9904-529bd71d2394.png)

Feedback is welcome.

**Comment by zekth** [comment]
Looks ok to me but why not separate the setuping of channels and the scheduling? It makes the UI a little bit too full. Also you setup channel only once but you change the schedule more often. You don't think so?

**Comment by Ranthalion** [comment]
That's an interesting idea.  
I'm not sure how to effectively split the set up and the schedule since each channel is scheduled individually.  The set up is definitely full, and it will get even more full once we support composite profile.  Post some mock ups if you can.

**Comment by zekth** [comment]
![ESL_02](https://user-images.githubusercontent.com/6959636/67825141-f2930480-fafa-11e9-9630-6d619870e35b.jpg)
The one from ecotech marine is really nice. Like on each point you click and you have the details of each channel on the left.

**Comment by Ranthalion** [comment]
I just checked out a few ecotech videos.  That's a nice UI, but I don't think it will be possible for release 3. I think it's a good aspirational goal.

**Comment by sfgabe** [comment]
It looks like there's some kind of remnant of the tests above in the latest release. I get the following error on my light setup:

`Nov 05 22:53:57 reef-pi reef-pi[247]: 2019/11/05 22:53:57 API Request:'  POST /api/lights/3' from: IP.XXX.XX.XXX:46320
Nov 05 22:45:24 reef-pi reef-pi[247]: 2019/11/05 22:45:24 ERROR: lighting-subsystenL failed to load profile for channel channel-1 light Kessil Error: Failed to parse start time. Error:parsing time "" as "15:04:05": cannot parse "" as "15"
Nov 05 22:45:24 reef-pi reef-pi[247]: 2019/11/05 22:45:24 ERROR: lighting-subsystenL failed to load profile for channel channel-2 light Kessil Error: Failed to parse start time. Error:parsing time "" as "15:04:05": cannot parse "" as "15"`

I was perplexed as to where that time 15:04:05 came from, since i didn't enter it anywhere - it looks like it was in fixed intensity test.

**Comment by ranjib** [comment]
@sfgabe the 15:04:05 is go's refernece time. Actually its "Mon Jan 2 15:04:05 MST 2006" , this reference time is used to represent any arbitrary format for . example hh:mm is represented as 15:04. It unique, confusing and very simple all at the same time :-)
