### ISSUE TITLE
Set default macros with id : feeding time & water change - Reelexa [Request] 

### ISSUE THREAD

**Issue by stvnmbr1** [reef-pi/reef-pi#860]
**Is your feature request related to a problem? Please describe.**
imo it would be nice to have a fixed id or 2 preset macros with fixed id's to have a nice end user experience with alexa

**Describe the solution you'd like**
instead of defining the macro with slots and extensive dialog, a simple intent (feeding time & water change) gives a more fluent end user experience. I took these 2 as these will be the most common macro's an end user is going to setup.

**Describe alternatives you've considered**
getting the correct macro by filling slots takes longer and the naming could be different for any end user.
fixed id with unremovable preset macro & name would do the trick, we could include this name in translations file.

**Additional context**
no prio, thinking ahead :) 

and only if this brings not to much hassle with coding and upgrading from a previous version?

**Comment by stvnmbr1** [comment]
maintenance would be a good one too, as not everyone does water changes (me included), so that's 3 preset macros with fixed id

**Comment by ranjib** [comment]
It will complicated to declare any specific set of macros as special and then expose it over UI. I think its better to use the macro list api to enlist the macro and then choose one with a given name convention (e.g. start with  feed) and then use that ID from there on.
This seems like a problem coming from the lamda architecture, does it provide any storage option?

**Comment by stvnmbr1** [comment]
naming convention would work best, didn't think about that one. Easily included in manuals 2.

just got the run macro skill with specfic intent up and running. Ran into a problem with caps letters in the macro name, but getting this fixed by parsing it to normal. Alexa doesn't do caps when you speak to her. Still need to test extensively but looking great.
You can get an overview of macros by asking for it and then triggering the run macro with the name of the macro. so that fixes the biggest part, but i will need to set some guidelines on naming the macros to work with alexa.
Bedtime nao, 4:35AM over here, more update soon
