### ISSUE TITLE
Temperature graph errors!!

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#861]
Temp Graph shouldnt log anything over 100 to keep the graph visible when temp data error spikes for 1 reading over 100 as seen in picture this might be something in my wiring but it happens randomly all the time and ive just overlooked it ive changed sensors and pi's and wiring and it still happens. So easier fix for me would be to cap the graph height. 

![Capturetemp page](https://user-images.githubusercontent.com/22088453/67154425-8dedd380-f2ca-11e9-83ea-792fe8ff5879.JPG)

**Comment by ranjib** [comment]
We are discussing on how to best address this. In next two week we'll have an answer to whether we want user to be able to set a min/max range or this will be as expected

**Comment by gminton86** [comment]
what if you took a couple readings then averaged them to get the reading that is displayed and then ignore any reading that is over by a set percent. just a thought

**Comment by gminton86** [comment]
I found out that if you set the refresh for the temperature to 10 seconds or less I don't get errors like that

**Comment by ranjib** [comment]
Moving average or something of that sort. But at the same time, i am very suspicious about this particular case, with ph this is common, with temperature this is not. I have not seen one case where this was normal, almost always there was some other issue. So even if we do get some moving average or other types of smoothing scheme and integrate it as a failsafe mechanism, I want to call out that this particular case is not normal (30F spike) and likely represent some other type of issue.

**Comment by Ranthalion** [comment]
I was also thinking about adding some kind of rejection logic, as well.  Rolling average has a drawback that it makes the measurements less responsive to changes.  Perhaps another option can be to reject readings outside of a normal expected range and retry a few times.
