### ISSUE TITLE
I would love to be able to hear an audible buzzer alarm from any parameter I set that is too far out of range    

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#863]
I would love to be able to hear an audible buzzer alarm from any parameter I set that is too far out of range. That can be silenced with a physical button from an input if wanted. Such as ATO running to long or PH HIgh/Low and/or Temp to High/Low. This would be great since 3.0 will have PH controlling outlet capabilities.

**Comment by ranjib** [comment]
Yes . I am planning to work on it for some time as well. My current thought is to use an active buzzer and have an option in setting to enable this with a specific GPIO. One enabled, reef-pi will beep the buzzer at 1s interval once any type of alert is triggered.

**Comment by gminton86** [comment]
awesome
