### ISSUE TITLE
[Request] Task reminder page 

### ISSUE THREAD

**Issue by burningbaal** [reef-pi/reef-pi#878]
FWIW, I assume this is a low priority, but something I feel would bring unique value to reef-pi no other option offers.

Be able to setup a set of tasks much like the existing timers page, but instead of taking 'real' action, the timer expiration merely raises an alert (via telemetry and/or on the dashboard) to tell the user it is 'due'.

I would recommend each task can be set as either a 'fixed schedule' or 'rolling schedule' task. The distinction would be that some things (like feeding corals maybe, or perhaps testing) can be set on a fixed schedule (every saturday, for example). Other things (like a water change, trimming macro algae, filling ATO reservoir) are rolling in that when the person 'marks' the task as 'done', it would reset the timer so it won't be raised as necessary for the whole task interval.

**Describe alternatives you've considered**
I have looked at a few apps, and at other controllers. Some have maintenance reminders (in fact, reef-pi kind of does), but the idea of rolling intervals is novel and I think foundational to maintaining our tanks. Obviously one can just use any old calendar app for the fixed things, but it's not much use at reminding me to refill my dosing containers or do a water change because as soon as I do it off-schedule, I have to rebuild the calendar items manually.

**Additional context**
I want to put GAC in my tank once a month. If something weird happens and I want to do it after only a couple weeks, I want to not be reminded for another month. But I want to test every single Sunday, even if I do an extra set of tests, I want to see them on my calendar each sunday.

**Comment by ranjib** [comment]
The reminder feature in timer module should solve the periodic reminder use case. For the sensor based stuff alert should cover right?

**Comment by burningbaal** [comment]
I don't think the timer based approach covers the rolling timing aspect.
There are many things your want to do "at least weekly" or "at least
quarterly". You should clean your protein skimmer twice a year, but what
about when you notice it's dirty early and clean it at the 4 month mark.
You want to mark it as done at that time and have the clock reset for a new
6 months.

**Comment by ranjib** [comment]
In 3.0 we have ability to specify every wenesday or every january like schedule. Is there anything else missing?

**Comment by burningbaal** [comment]
yes, it's actually the very core of what I've wanted to find that is
missing, it seems to be missing from every similar product.
* Let's say I set a reminder to clean my skimmer every 6 months.
* 4 months later, I realize I've got some extra time, I was doing some
extra tank work, and I clean my skimmer, even though it isn't due
* 2 months later, my tank reminds me it's time to clean the skimmer, but
that's not true, so I just let it go
* 6 months later, the reminder pops up and I realize I'm actually 8 months
out because I got off-schedule and my skimmer is overdue.

Same idea for replacing carbon every 4 weeks, what if I decide it needs it
early this time and stick in new carbon after only 2 weeks, now my schedule
is off.

Of course, I could go rebuild the reminder each time I do it off schedule,
but many of these things are really intended as 'do this on-or-before
periodicity'.

What I really want is an easy button to reset the periodic task because I
did it today, so reset the clock.

**Comment by ranjib** [comment]
So this is not really just a timer. You are asking that the system should provide a way to reset itself as and when you miss / prempt schedule. I think its best to re-configure the timer.  I dont have any plan to work on something like this in the current road map. Im closing this since theres no plan to work on this. If there enough ask for this feature, reopen, happy to discuss this.
Thank you for taking the time to file and discuss this issue. All ideas are welcome and your effort means a lot to us.
