### ISSUE TITLE
Can we get some sort of option to cancel a timer based on some event?

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#887]
Basically if I have a relay controlling a pump/blade in kalkwasser stirrer/reactor which stir's the solution. I would want the ATO to either not add water at that point the reactor is stirring or stop the stirrer from running while the ATO is adding water. Maybe a switch inside the ATO tab that enables you to pick a piece of equipment that you want it to control. That is labelled "Kalwasser Reactor" I think this would be useful.

**Comment by stvnmbr1** [comment]
you could achieve the first part by creating a macro that disables ato, then enables stirrer, wait some time, disable stirrer, enable ato.

Other way around you can also achieve by letting the ATO run a macro instead of equipment but in 3.0Beta it is not included as far as I can see.

**Comment by ranjib** [comment]
How frequently you want to run the kalk stirrer. You can have a timer that triggers a macro. The macro disable ato, wait some time, start stirrer, wait some more , stop stirrer, enable ato

**Comment by gminton86** [comment]
ok thanks for the tips ill try it out.

**Comment by ranjib** [comment]
Closing this as I think this is already doable. Feel free to reopen this if thats not the case,
