### ISSUE TITLE
change heater threshold parameter to a heater range pair of parameters[Request] 

### ISSUE THREAD

**Issue by burningbaal** [reef-pi/reef-pi#889]
The temperature sensor may give values ever-so-slightly above/below a set point and in a relatively stable system, this can cause the tc to trip on and off at almost every check of the temperature when it really isn't needed and only wears out the relay.

I suggest we offer two parameters instead, either of these I think would be fine, in both the value can be checked every 5 seconds, but it wouldn't actually move the relay very often.
* on-temp and off-temp (say, 25c and 25.5c) to hold it within a 0.5c range
* target-temp and range-width (say, 25c and 0.5c) and the code doesn't change the equipment state unless the value is outside [24.75c - 25.25c]

Big picture, Ranjib suggests this can be expanded to allow any two sensors' combined data to be used to raise an alarm (or maybe change equipment state or initiate a macro?). This may require a new class that is an overlord over multiple sensors, where the temperature sensors may be able to have a class member of 'linked probe'. I think more of an overlord class may be required in order to make any sense of dissimilar units. I suppose someone might say 'when pH is under 7.7, temperature is over 78, and ORP is...then...' and that's a bit odd to put together except in an overlord class

**Comment by ranjib** [comment]
For the first part, we have recently introduced hysteresis where you can specify set point 25, and threshold .5 

For the second bit. I am thinking of some features that will allow us to combine different sensor value and do something with it.

**Comment by gminton86** [comment]
IMO hysteresis in the new 3.0 is hard for someone that is new to understand? or maybe its just me but I feel like you should use threshold instead of hysteresis in the ui

**Comment by Ranthalion** [comment]
hysteresis can be renamed to threshold on the UI, but that term is already used for heater and chiller set points.  I think we have the functionality we need, but I agree that we can find a better way to express this functionality.

**Comment by ranjib** [comment]
Given that we have the feature now, its about how we can best document this. Im closing this, will make sure temp/ph guides call this out

**Comment by burningbaal** [comment]
to be fair, this thread ended up covering three separate things.  the title
is about linking two sensors to one effect/output/result...
