### ISSUE TITLE
I cannot get PH to work in 3.0

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#890]
I just updated to the 3.0 and I cannot get my PH Probe to work I have the scientific atlanta EZO PH Board and it keeps asking for a analog input in the PH tab. when i try to add an analog input it asks for pin but Im not sure?

**Comment by ranjib** [comment]
In 3.0, all connectors are attached to a driver. Navigate to Configuration -> Drivers section and create a new driver, choose type as ph-ezo from the drop down and specify the i2c address. Afer that go to connectors section and crate an analog input with pin 0 and the newly created driver. Now you can attach the .analog input to ph probe and proceed monitoring/controlling with the readings. Im closing this for the time being, if you encounter any issue , feel free to reopen. Thank you for testing out. Im in process of updating the adafruit guides , I'll make sure to add this in the guide.
