### ISSUE TITLE
SWomething went wrong

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#891]
Something went wrong.
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20e.drivers.filter(...)%5B0%5D%20is%20undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

    in td
    in tr
    in tbody
    in table
    in div
    in div
    in t
    in Connect(t)
    in t
    in div
    in div
    in div
    in div
    in t
    in Connect(t)
    in t
    in a

**Comment by stvnmbr1** [comment]
had that when I upgraded from 2.5 to 3.0b, deleting the db file worked for me.

**Comment by gminton86** [comment]
do you remember the string i need to delete the db?

**Comment by ranjib** [comment]
This is expected. 3.0 is a major version upgrade, the 2.0 data will cause some missing properties in 3.0 which then manifest as ui errors. We are trying do a better job in exposing these errors. Instead of this raw react dom errors. Thank you for reporting this,

**Comment by gminton86** [comment]
I found it. Here it is if anybody else runs into this problem.

Resetting reef-pi’s database

sudo systemctl stop reef-pi.service
sudo rm -rf /var/lib/reef-pi/reef-pi.db
sudo systemctl start reef-pi.service
