### ISSUE TITLE
(bug) default driver selection of analog connector does not work

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#897]
Steps to reproduce
- Add a ph driver 
- Add an analog connector, without changing the driver, by default it shows the newly created ph driverr
- Error returned saying driver is not set.

I think by default the driver is set to "" instead of what shown in the drop down box

**Comment by gminton86** [comment]
why does it ask me to choose a analog input for my PH probe when I try to set it up on 3.0? and also will a ADS1115 work for this analog input? it says ADS1119 in the documents i read for the PH board. also why does it ask me for which pin im using if i try to setup an analog input? How do I find out what pin it is when its i2C and uses addresses? 

Thank You ahead of time

**Comment by ranjib** [comment]
In 3.0,  analog inputs represent ph board, pico board etc.. the choices depend on the available drivers. Currently, we have ph board, pico board, ezp and tplink. I have not checked if the ph board i2c protocol is same as ADS1115. The protocol details are present on the ph board repository readme. I followed the author's instruction on how to program it.

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/900
