### ISSUE TITLE
3.0 RC Can't select dutch language

### ISSUE THREAD

**Issue by stvnmbr1** [reef-pi/reef-pi#904]
Language selection : Dutch not available in dropdown 

I thought I adding dutch,nederlands to all other language files would do the trick in previous PR?
Sorry if I did something wrong or forgot to add something somewhere

**Comment by zekth** [comment]
We need to add it in the language provider inside yhe code not only add the csv files. I'll look into

**Comment by stvnmbr1** [comment]
@zekth aha, i did miss something, sorry for that :)
