### ISSUE TITLE
Can we get PH to only show 2-3 digits and not the whole number thats 10 digits long its useless info

### ISSUE THREAD

**Issue by gminton86** [reef-pi/reef-pi#917]
![ph capture](https://user-images.githubusercontent.com/22088453/69258703-088c6600-0b8b-11ea-8ba3-123ab767d0b6.JPG)

**Comment by ranjib** [comment]
Thank you for reporting this. I have addressed this in:  https://github.com/reef-pi/reef-pi/pull/923
