### ISSUE TITLE
(bug) Lighting ui sending wrong number or interval points in interval mode

### ISSUE THREAD

**Issue by ranjib** [reef-pi/reef-pi#922]
Steps to reproduce:
- Set light in auto mode. 
- Choose interval as profile type
- Set start time 07:30:00, end time: 19:30:00
- Set peak intensities for each provided interval points
- Save
- Backend throws error during PWM value calculation using profiles. It expected one more value in the argument list config.values ,

@Ranthalion  FYI

**Comment by Ranthalion** [comment]
I'll review.

**Comment by Ranthalion** [comment]
This is due to fractional seconds.  The UI calculated the internal as 3927 instead of 3927.27272727...
I can remove the floor call that limits to whole seconds, but that may not fully resolve this issue.
