### ISSUE TITLE
Chart / Grid Colour Customisation

### ISSUE THREAD

**Issue by roolimited** [reef-pi/reef-pi#944]
Hello, I am able to change basic colour settings in CSS file for top and bottom banners etc for customisation (have this mounted on a wall next to the tank) but I'm unable to customise the chart colours themselves. Has anyone managed to do this via SSH without having to dpkg, edit and recompile? A Customisation feature would be great in future releases if possible. 
thanks

**Comment by ranjib** [comment]
@roolimited front end codes are all in : https://github.com/reef-pi/reef-pi/tree/master/front-end 

Some of the global style declarations are here: https://github.com/reef-pi/reef-pi/tree/master/front-end/assets/sass

Most of the chart specific plumbing are in their respective front end code directory, for example here is the ATO chart: https://github.com/reef-pi/reef-pi/blob/master/front-end/src/ato/chart.jsx

**Comment by ranjib** [comment]
And development environment setup guide is here: https://reef-pi.github.io/additional-documentation/development/

Let us know if you need any help or any of the docs are  outdated
