### ISSUE TITLE
Update from 2.2 -> 3.0 failure

### ISSUE THREAD

**Issue by DaveCBr** [reef-pi/reef-pi#945]
After the update, connection to the outlet relays was not recognized and resulted in no control power.  Also, temperature sensors were picked up but not reporting temperature.  I rolled back to 2.2 and now have sort of half of an update.  Relay control was restored but lost temperature sensors.

**Comment by ranjib** [comment]
@DaveCBr unfortunately, you have to delete the database and recreate everything as part of the upgrade process

**Comment by DaveCBr** [comment]
Oh.  I missed that.  Can you point me to some documentation on what to delete?

**Comment by ranjib** [comment]
resetting database: https://reef-pi.github.io/guides/troubleshooting/

Im closing this for the time being, since this is as expected. Feel free to open if you encounter other issues
