### ISSUE TITLE
ATO data resetting

### ISSUE THREAD

**Issue by AmaDewd** [reef-pi/reef-pi#987]
**Describe the bug**
I have 3 ATO's on my Reef-Pi installation.  One was set up about 6 weeks ago when I set up the Reef-pi.  The other two are part of my Auto Water Change system and are about 2 weeks old.  On the original ATO, it keeps good track of the ATO usage and I currently have data going back to 26 November.  On the other 2 ATO's, the usage data disappears every time I have a power outage.  (which is daily at this stage in South Africa).  If I reload Reef-Pi, I also lose the usage data on the 2 additional ATO's, but not on the original one.  This seems to happen regardless of how long it has been since the ATO data was saved.  ie ATO data from 6 hours ago is lost when the Pi loses power unexpectedly.

**To Reproduce**
I think what I said above covers this

**Expected behavior**
I expected the additional 2 ATO usage to be saved despite restarts / reloads like the original.

**Screenshots**
![2019-12-09](https://user-images.githubusercontent.com/58691543/70436403-dedfa400-1a91-11ea-8141-23b8405f8d09.png)
![2019-12-06 (2)](https://user-images.githubusercontent.com/58691543/70436469-09c9f800-1a92-11ea-915e-288e231d2429.png)

![image](https://user-images.githubusercontent.com/58691543/70436153-4ea15f00-1a91-11ea-96c5-24eec27f5808.png)

Screenshot shows the ATO data going back to 26 Nov, but the AWC ATO data is gone after a recent reload

**Desktop (please complete the following information):**
 - Device [Pi3]
 - reef-pi version [3.0]
 - Browser [Chrome]
 - Version [Version 78.0.3904.108 (Official Build) (64-bit)]

**Additional context**
I'm new to this GitHub stuff.  I hope what I've done is correct.

**Comment by gminton86** [comment]
mine resets sometimes also but I just disregard it as once its history I really don't need it anymore

**Comment by AmaDewd** [comment]
The reason I created this issue is to report reef-pi not working consistently across the board. In this case between ATO’s. If all data was always lost, that’s fine. My point is some is retained and some is lost

**Comment by ranjib** [comment]
@AmaDewd thank you so much for filing this bug. I'm getting back to speed from vacation and will take a look into this shortly. Can you share the ATO configuration screen for these. I need those to reproduce this scenario
