### ISSUE TITLE
Left Hand Y-Axis on Temperature Sensor shows wrong scale v3.0

### ISSUE THREAD

**Issue by adityaduggal** [reef-pi/reef-pi#993]
**Describe the bug**
The bug is in the graph for heater control where the left hand axis of the heater control for temperature is taking the values from deg F and not from deg C as shown in the screenshot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select the temperature sensor graph scale to Celsius.
1. Now the left hand graph for temperature is correctly shown and in the screenshot but the right hand graph which shows the time for heater ON is skewed since its taking the values from deg F scale as well for the maximum values.

**Expected behaviour**
The left hand side is taking the values from deg F scale instead it should be showing the deg C scale which would make the temperature line more visible even for the heater graph

**Screenshots**
![image](https://user-images.githubusercontent.com/1057509/70845725-0068d300-1e78-11ea-8592-4f109ce1d7bb.png)

**Desktop (please complete the following information):**
 - Device [Pi0-wifi]
 - reef-pi version [3.0]
 - Browser [safari]

**Comment by ranjib** [comment]
@adityaduggal did you created the temperature controller with celsius as unit? I just tried and it worked for me. If you switch unit once a sensor is created then it will have this effect, we can back comput and fix it, but it will be lot more work and not sure if we can maintain all other related things coherently (like chart etc) as we dont have all the historical data. We can make sure that the unit is immutable after creation (i.e. users wont be able to change it once created) , i deliberately chose not to. but we can revisit this. I am closing this i dont am not taking any action item from this.  Feel free to reopen this ticket if you have other thoughts,

**Comment by adityaduggal** [comment]
Hi @ranjib 
I have created a new temperature sensor with Celcius selected and again I am getting the issue of the left hand axis range on temperature historical graph is skewed goes upto 86 deg Celcius ideally it should have gone upto 25 deg celcius as in the Temperature current graph. I know you have closed this issue but I think this issue is persisting.

![image](https://user-images.githubusercontent.com/1057509/74022518-b73e8680-49c3-11ea-866c-ef50cfbd45a9.png)
