### ISSUE TITLE
Publish telemetry over MQTT

### ISSUE THREAD

**Issue by stvnmbr1** [reef-pi/reef-pi#999]
**EDIT**
misread concept of blackbox exporter. Digging through the code on how to get mqtt integrated with reef-pi.

https://github.com/inovex/mqtt_blackbox_exporter

what do you guys think about implementing the mqtt exporter in prometheus?
I checked out the code and it looks like this could be integrated with not to much hassle as only the prom deamon would be affected.

This adds an mqtt publish function to the metrics collected by promhttp in reef-pi code to a set broker ip and topic(only 1 topic), with encryption available. 
I believe it's the prometheus code in the deamon package that would need to have the extra code from blackbox exporter

IMO this would add a lot of dashboarding opportunities and integration with iot domotics homeassistant,OPENHab,../Virtual assistants alexa,google home/any graphing tool ... If you have a db already run and some tool storing to db, prometheus server setup could be optional in some cases

**Comment by ranjib** [comment]
I think the existing Prometheus integration  coupled with grafana is more robust and feature-rich graphing/alerting option. But given mqtt is fairly popular in IOT devices and there exist a number of broker/ecosystem that is based on mqtt, I think we should definitely make sure reef-pi integrates seamlessly with them.
Let's use this ticket to discuss what features (think of end to end use case) we would like to see using mqtt and derive the technical implementation from there.
To start with im thinking of publishing reef-pi telemetry via mqtt. This should be fairly straightforward, we here an example code: https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/stdinpub/main.go

we can expose the necessary configuration under the telemetry section and have mqtt based metric publishing as part of that.

**Comment by stvnmbr1** [comment]
It all depends on what you have running in your home. I'm running openhab, homeassistant and IFTTT. I do agree that prom and graphana works like a charm but it does have limits and only allows graphing, not controlling or controlling based on triggers (homeassistant,IFTTT).
MQTT is the way to go nowadays and i keep being amazed at how fast this works. It also simplifies integration with any platform.

MQTT would not only target telemetry but actually functions as the api, where you can control equipment, macros, ... and get stats.
MQTT would be a way to expose reef-pi to the internet, secure and lightweight, without exposing the API itself and reducing performance.

EG: equipment 1 subcribes to equipment/1/stats topic and publishes relevant data to that topic, which can be picked up by any platform.
you can control equipment 1 by sending ON or OFF to the equipment/1 topic, which you can send from any platform.
I think the biggest challenge in this actually creating the landscape of topics to monitor and control, but i would use the same adresses as the api is using to keep it simple (driver/ID; equipment/ID, info, ....)

I did try to dig through the code as we could use the bucket storage, the same way prom uses it. But this is new territory for me.
Paho-mqtt is the one I use for my own integrations and is pretty straight forward.

I also used https://github.com/jpmens/mqtt-launcher which subscribes to topics and handles the requests sent. The launcher then runs a script (say GET or POST to the local API) and returns that response value to the relevant topic or set topic by script. But I'm not sure this could be at help in this case.

**Comment by ranjib** [comment]
i have pushed an mqtt branch with example code.

**Comment by stvnmbr1** [comment]
https://www.home-assistant.io/docs/mqtt/discovery/
https://github.com/arendst/Tasmota/wiki/Domoticz---Automatic-discovery

some info on how the topics work with auto discovery. I  use this with my wemos and tasmota firmware. Super EZ setup and once connected to broker, everything(sensors, switches,....) is added automagically.

**Comment by ranjib** [comment]
@stvnmbr1 i understand the things possible with mqtt as you have explained in the examples, but reef-pi is not exactly that right? If we all an user want is to turn on/off equipment or just read a sensor and integrate it with something then just pi or arduino or anything that interfaces with that device and exposes them as mqtt will do. reef-pi itself is a controller, i.e. it controls the equipment in response to some input. This process gets very complicated if another thing also controls the same equipment.
I would like to understand end to end use case before implementing mqtt driven changes in core reef-pi. Such functionality can be easily done already by using an external program (home assistant plugin?) right now,so its not impossible. Till we have those details (end to end use case) , i'll prefer to reduce the scope of this work to only publish telemetry data over mqtt.

**Comment by stvnmbr1** [comment]
I agree that integration for controlling reef-pi through mqtt can mess things up if you want to control every aspect.
I would not use mqtt to control reef-pi persé (but it could be possible), but to use the stats of reef-pi on any platform/dashboard/smart assistant/mobile app/database with much ease, for any use, without exposing the api itself to the internet (main reason for me). I don't like to expose these kinds of things directly to the internet and VPN connection is not always a possibility.

The only control over mqtt that would make sense to me, without messing with reef-pi's working, is to run/stop macros and timers.
In my case telemetry over mqtt should actually be good enough but controlling macro/timer would be a nice-to-have extra.

l did come across a topic in reef2reef with someone who used the rest plugin to add everything to his own systems( with his own automations: not what i want to do)
This proves a lot of hassle and lots of seperate api call codes and is not user friendly. This includes other platforms as well.
With MQTT there is no need to setup an extra prom server to scrape the api to write to a time-series DB.

**Comment by stvnmbr1** [comment]
I created a bridge from the api to mqtt for testing

https://github.com/stvnmbr1/Reelexa/blob/master/mqtt/reefpimqttbridge_listener.go
First time coding golang so it won't be perfect :) 

publish eg "/api/macros" to reefpi/in topic, and the json response from the API is forwarded to reefpi/out topic.
This way I can integrate alexa and google home in a more secure way for now and start testing furter.

I was also trying to parse those json responses and publish them to relevant topics like /reefpi/macros/1/status (on/off) or /reefpi/tcs/1/sensor (temperature value)
Trying with unmarshal but JSON works a bit different in golang it seems? i can't parse the json to get the values for the keys, to create a new JSON string to publish to mqtt.


I don't know how you feel of implementing a mqtt publish on, for instance equipment? 
Eg. If the state changes of equipment 1 post that to reefpi/equipment/1/status

Or sensors 
Eg. sensor 1 is being polled , post that result to reefpi/tcs/sensor

This is actually more what i meant with implementing mqtt but i didn't find the correct words. 

As always, many thanks and love your work !

**Comment by stvnmbr1** [comment]
@ranjib 
can the mqtt branch be merged to the latest version of reef pi?

picking things up again, lot of sh*t going on. Reeftank issues included :(

also thinking about mqtt / espeasy integration for standalone thing with esp8266 wemos d1. Thinking about a tds sensor for my rodi unit for starters. Could be a usefull extra feature imo :)

Could expand this to eg. standalone doser units running on esp's, programmed and controlled by reef pi (could be an extra pcb unit for this 2. wemos d1 costs 5bucks instead of pi 40bucks

**Comment by ranjib** [comment]
https://github.com/reef-pi/reef-pi/pull/1278

**Comment by ranjib** [comment]
this will be shipped as part of 4.0

**Comment by stvnmbr1** [comment]
many thanks !
in a later stage i'll see to get a hassio/domoticz discovery part(just monitoring, no controls at first, maybe macros or settings control later). This way current hassio users can switch to reef pi as controller and still monitor in their own home automation platform. I've come across many in my search for aquarium automation using hassio as controller.

as always, you da best !
